import javax.swing.*;import javax.swing.event.*;import javax.swing.table.*;import java.awt.*;import java.time.*;import java.util.*;import java.io.*;

/** Monthly attendance sheets; edits are debounced to durable storage after one second. */
public class AttendancePanel extends JPanel {
 private final AttendanceDAO dao=new AttendanceDAO(),persistence=new AttendanceDAO();private final EmployeeDAO employees=new EmployeeDAO();private final AttendanceSettingsDAO settingsDAO=new AttendanceSettingsDAO();private final JTabbedPane months=new JTabbedPane();private int year=FinancialYear.currentStart();private static final String[] COLS={"Employee ID","Employee Name","Absent Days","Casual Leaves","Earned Leaves","Days Payable","OT Hours","Others","Remaining CL","Remaining EL"};
 public AttendancePanel(){setLayout(new BorderLayout(6,6));setBorder(UIStyleUtility.compactModuleBorder());JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT,5,2));JComboBox<String> yearInput=FinancialYear.selector(year);JButton open=new JButton("Open Year");open.addActionListener(e->{year=FinancialYear.parse((String)yearInput.getSelectedItem());buildTabs();});JLabel heading=new JLabel("Attendance Register - Financial Year ");heading.setFont(new Font("SansSerif",Font.BOLD,23));top.add(heading);top.add(yearInput);top.add(open);months.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);months.addChangeListener(e->loadSelectedSheet());add(top,BorderLayout.NORTH);add(months,BorderLayout.CENTER);buildTabs();}
 public void refreshEmployees(){buildTabs();}
 private void buildTabs(){int selected=Math.max(0,months.getSelectedIndex());months.removeAll();for(int i=0;i<12;i++){YearMonth month=FinancialYear.month(year,i);months.addTab(FinancialYear.shortName(month),loadingSheet());JLabel tab=new JLabel(FinancialYear.shortName(month),SwingConstants.CENTER);tab.setPreferredSize(new Dimension(80,30));tab.setFont(new Font("SansSerif",Font.BOLD,15));tab.setForeground(Color.WHITE);months.setTabComponentAt(i,tab);}months.setSelectedIndex(Math.min(selected,11));loadSelectedSheet();revalidate();repaint();}
 private JComponent loadingSheet(){JPanel panel=new JPanel(new GridBagLayout());panel.add(new JLabel("Loading attendance…"));return panel;}
 private void loadSelectedSheet(){int index=months.getSelectedIndex();if(index<0)return;JComponent current=(JComponent)months.getComponentAt(index);if(Boolean.TRUE.equals(current.getClientProperty("loading"))||Boolean.TRUE.equals(current.getClientProperty("loaded")))return;current.putClientProperty("loading",Boolean.TRUE);int activeYear=year;YearMonth month=FinancialYear.month(activeYear,index);ApplicationTasks.execute(()->{JComponent loaded;try{loaded=sheet(month);loaded.putClientProperty("loaded",Boolean.TRUE);}catch(Exception ex){loaded=new JPanel(new GridBagLayout());loaded.add(new JLabel("Could not load attendance: "+ex.getMessage()));}JComponent result=loaded;SwingUtilities.invokeLater(()->{if(year==activeYear&&months.getSelectedIndex()==index&&FinancialYear.month(year,index).equals(month)){TabStyle.apply(result);months.setComponentAt(index,result);months.revalidate();months.repaint();}});});}
 private JComponent sheet(YearMonth month){
  double savedWorking=dao.workingDays(month.toString());JTextField working=new JTextField(String.valueOf(savedWorking),8);JLabel attendanceError=new JLabel();attendanceError.setForeground(new Color(190,20,20));attendanceError.setVisible(false);JButton saveWorking=new JButton("Save Working Days"),importAttendance=new JButton("Import Attendance"),exportAttendance=new JButton("Export Excel");
  JPanel bar=new JPanel(new BorderLayout());JPanel workingControls=new JPanel(new FlowLayout(FlowLayout.LEFT));workingControls.add(new JLabel("Working Days for "+month.getMonth()+":"));workingControls.add(working);workingControls.add(saveWorking);workingControls.add(attendanceError);JPanel fileActions=new JPanel(new FlowLayout(FlowLayout.RIGHT));fileActions.add(importAttendance);fileActions.add(exportAttendance);bar.add(workingControls,BorderLayout.WEST);bar.add(fileActions,BorderLayout.EAST);
  AttendanceSettings leaveLimits=settingsDAO.load();java.util.List<Employee> list=employees.listForMonth("",month);Object[][] rows=new Object[list.size()][10];
  for(int i=0;i<list.size();i++){Employee employee=list.get(i);AttendanceRecord record=dao.load(employee.getId(),month.toString());boolean saved=dao.hasSavedAttendance(employee.getId(),month.toString());LeaveLedgerService.Balance clb=LeaveLedgerService.balance(employee,month,true,leaveLimits),elb=LeaveLedgerService.balance(employee,month,false,leaveLimits);rows[i]=new Object[]{employee.getId(),employee.getName(),record.absentDays,record.paidLeaveDays,record.unpaidLeaveDays,saved?payable(employee,month,savedWorking,record.absentDays,record.paidLeaveDays,record.unpaidLeaveDays,leaveLimits):0,employee.isWagesStructure()?record.overtimeHours:0.0,employee.isWagesStructure()?record.otherHours:0.0,clb.remaining(),elb.remaining()};}
  DefaultTableModel model=new DefaultTableModel(rows,COLS){public boolean isCellEditable(int row,int column){return column>=2&&column<=7&&(column<6||list.get(row).isWagesStructure());}public Class<?> getColumnClass(int column){return column<2?String.class:Double.class;}public void setValueAt(Object value,int row,int column){if(column>=2&&column<=4){if(attendanceNumber(value)>month.lengthOfMonth()){attendanceError.setText(maximumDaysMessage(month));attendanceError.setVisible(true);return;}double absent=column==2?attendanceNumber(value):attendanceNumber(getValueAt(row,2)),casual=column==3?attendanceNumber(value):attendanceNumber(getValueAt(row,3)),earned=column==4?attendanceNumber(value):attendanceNumber(getValueAt(row,4)),total=parse(working);if(absent+casual+earned>total){attendanceError.setText("Absent + CL + EL cannot exceed total working days.");attendanceError.setVisible(true);return;}attendanceError.setVisible(false);}super.setValueAt(value,row,column);}};
  JTable table=new JTable(model);configureCellSelection(table);UIStyleUtility.applyProfessionalTableStyle(table);table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);ExcelTableSupport.enableNumericMultiFill(table,true);for(int c=0;c<10;c++){int width=c<2?220:c==5?190:175;table.getColumnModel().getColumn(c).setMinWidth(width);table.getColumnModel().getColumn(c).setPreferredWidth(width);if(c>=2)table.getColumnModel().getColumn(c).setCellRenderer(TabStyle.numericRenderer());}
  DefaultCellEditor numberEditor=new DefaultCellEditor(new JTextField()){public Component getTableCellEditorComponent(JTable t,Object value,boolean selected,int row,int column){JTextField field=(JTextField)super.getTableCellEditorComponent(t,value,selected,row,column);field.setHorizontalAlignment(JTextField.LEFT);field.selectAll();return field;}};
  for(int c=2;c<=7;c++)table.getColumnModel().getColumn(c).setCellEditor(numberEditor);
  final boolean[] updating={false};
  Runnable recalculate=()->{if(updating[0])return;updating[0]=true;double days=parse(working);for(int r=0;r<model.getRowCount();r++)model.setValueAt(payable(list.get(r),month,days,n(model,r,2),n(model,r,3),n(model,r,4),leaveLimits),r,5);updating[0]=false;model.fireTableDataChanged();};
  model.addTableModelListener(event->{int column=event.getColumn();if(event.getType()!=TableModelEvent.UPDATE||updating[0]||!(column>=2&&column<=7))return;int row=event.getFirstRow();updating[0]=true;if(column>=2&&column<=4){model.setValueAt(payable(list.get(row),month,parse(working),n(model,row,2),n(model,row,3),n(model,row,4),leaveLimits),row,5);model.fireTableCellUpdated(row,5);}else if(column==6)splitExtraHours(model,row);updating[0]=false;autoSave(model,list,month,parse(working));});
  working.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){workingChanged();}public void removeUpdate(DocumentEvent e){workingChanged();}public void changedUpdate(DocumentEvent e){workingChanged();}private void workingChanged(){double days=parse(working);if(days<0||days>month.lengthOfMonth()){working.setBackground(new Color(255,239,239));attendanceError.setText(maximumDaysMessage(month));attendanceError.setVisible(true);return;}working.setBackground(Color.WHITE);attendanceError.setVisible(false);recalculate.run();AutoSaveService.debounce("working-"+month,()->saveWorking(month,days));}});
  saveWorking.addActionListener(e->{double days=parse(working);if(days<0||days>month.lengthOfMonth()){attendanceError.setText(maximumDaysMessage(month));attendanceError.setVisible(true);working.setBackground(new Color(255,239,239));return;}saveWorking(month,days);recalculate.run();JOptionPane.showMessageDialog(this,"Working Days saved for "+month.getMonth()+".");});
  importAttendance.addActionListener(e->importAttendance(model,working,list,month));exportAttendance.addActionListener(e->exportAttendance(model,working,month));JButton save=new JButton("Save "+month.getMonth()+" Attendance");save.addActionListener(e->{save(model,list,month,parse(working));JOptionPane.showMessageDialog(this,"Attendance saved for "+month.getMonth()+" "+year);});
  JPanel north=new JPanel(new BorderLayout());north.add(bar,BorderLayout.NORTH);north.add(EmployeeIdSearch.create(table,model),BorderLayout.SOUTH);JPanel out=new JPanel(new BorderLayout());out.add(north,BorderLayout.NORTH);out.add(UIStyleUtility.frozenEmployeeColumns(table),BorderLayout.CENTER);JPanel bottom=new JPanel(new FlowLayout(FlowLayout.RIGHT));bottom.add(save);out.add(bottom,BorderLayout.SOUTH);return out;
 }
 private void saveWorking(YearMonth month,double days){try{persistence.saveWorkingDays(month.toString(),days);AutoSaveService.markDirty();}catch(Exception ignored){}}
 private void configureCellSelection(JTable table){TabStyle.configureTable(table);}
 private void autoSave(DefaultTableModel model,java.util.List<Employee> list,YearMonth month,double working){java.util.List<AttendanceRecord> snapshot=records(model,list,month,working);AutoSaveService.debounce("attendance-"+month,()->{try{persistence.saveAll(snapshot);PayrollEvents.attendanceSaved();PayrollEvents.dataChanged("attendance");}catch(Exception ignored){}});}
 private static final String[] ATTENDANCE_HEADERS={"Employee ID","Month","Year","Total Working Days","Days Payable","Casual Leave","Absent Days"};
 private void exportAttendance(DefaultTableModel model,JTextField working,YearMonth month){java.util.List<Object[]> rows=new ArrayList<>();for(int r=0;r<model.getRowCount();r++)rows.add(new Object[]{model.getValueAt(r,0),month.getMonth(),month.getYear(),parse(working),model.getValueAt(r,5),model.getValueAt(r,3),model.getValueAt(r,2)});PayrollExcel.export(this,"Attendance",month+"-Attendance.xlsx",ATTENDANCE_HEADERS,rows);}
 private void importAttendance(DefaultTableModel model,JTextField working,java.util.List<Employee> list,YearMonth month){try{PayrollExcel.Sheet sheet=PayrollExcel.importSheet(this);if(sheet==null)return;PayrollExcel.requireHeaders(sheet,ATTENDANCE_HEADERS);int count=0;for(int i=1;i<sheet.rows.size();i++){java.util.List<String> v=sheet.rows.get(i);String id=PayrollExcel.cell(v,0);for(int row=0;row<model.getRowCount();row++)if(String.valueOf(model.getValueAt(row,0)).trim().equals(id)){double wd=PayrollExcel.number(PayrollExcel.cell(v,3));if(wd>0)working.setText(String.valueOf(wd));model.setValueAt(PayrollExcel.number(PayrollExcel.cell(v,5)),row,3);model.setValueAt(PayrollExcel.number(PayrollExcel.cell(v,6)),row,2);model.setValueAt(0.0,row,4);count++;break;}}autoSave(model,list,month,parse(working));JOptionPane.showMessageDialog(this,count+" attendance records imported and auto-saved.");}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
 private String maximumDaysMessage(YearMonth month){return month.getMonth()==Month.FEBRUARY?"February cannot exceed "+month.lengthOfMonth()+" days.":month.getMonth()+" cannot exceed "+month.lengthOfMonth()+" days.";}private int column(Map<String,Integer> columns,String... names){for(String name:names)if(columns.containsKey(name))return columns.get(name);return -1;}private double number(String value){try{return Double.parseDouble(value.trim());}catch(Exception e){return 0;}}private double parse(JTextField field){try{return Double.parseDouble(field.getText().trim());}catch(Exception e){return 0;}}private static double attendanceNumber(Object value){try{return Double.parseDouble(String.valueOf(value));}catch(Exception ignored){return 0;}}private double n(DefaultTableModel m,int r,int c){try{return Double.parseDouble(String.valueOf(m.getValueAt(r,c)));}catch(Exception e){return 0;}}private void splitExtraHours(DefaultTableModel model,int row){double otLimit=Math.max(0,CompanyPolicyStore.maxOtLimit()),totalLimit=Math.max(otLimit,CompanyPolicyStore.maxTotalLimit()),total=Math.min(totalLimit,Math.max(0,n(model,row,6))),ot=Math.min(total,otLimit),others=Math.min(Math.max(0,total-otLimit),totalLimit-otLimit);model.setValueAt(Money.round(ot),row,6);model.setValueAt(Money.round(others),row,7);}private double payable(Employee employee,YearMonth month,double work,double absent,double casual,double earned,AttendanceSettings limits){return LeaveBalanceService.payableDays(employee,month,work,absent,casual,earned,limits);}
 private java.util.List<AttendanceRecord> records(DefaultTableModel model,java.util.List<Employee> list,YearMonth month,double working){java.util.List<AttendanceRecord> records=new ArrayList<>();for(int i=0;i<list.size();i++){AttendanceRecord r=new AttendanceRecord();r.employeeId=list.get(i).getId();r.month=month.toString();r.workingDays=working;r.absentDays=n(model,i,2);r.paidLeaveDays=n(model,i,3);r.unpaidLeaveDays=n(model,i,4);r.daysPayable=n(model,i,5);r.overtimeHours=n(model,i,6);r.otherHours=n(model,i,7);records.add(r);}return records;}
 private void save(DefaultTableModel model,java.util.List<Employee> list,YearMonth month,double working){try{dao.saveAll(records(model,list,month,working));PayrollEvents.attendanceSaved();}catch(Exception e){JOptionPane.showMessageDialog(this,"Could not save attendance: "+e.getMessage());}}
}
