import javax.swing.*;import java.awt.*;import java.sql.SQLException;
public class AttendanceSettingsPanel extends JPanel {
    private final AttendanceSettingsDAO dao=new AttendanceSettingsDAO();private AttendanceSettings settings;private JTextField weekOff,holidays,cl,el,clCarry,elCarry,otRate,threshold,bonus,late;private JCheckBox bonusEnabled,bonusPercent;private JLabel bonusHelper;
    public AttendanceSettingsPanel(){setLayout(new GridBagLayout());GridBagConstraints c=new GridBagConstraints();c.insets=new Insets(7,7,7,7);c.fill=GridBagConstraints.HORIZONTAL;settings=dao.load();weekOff=f(settings.weeklyOffDays);holidays=f(settings.publicHolidays);cl=f(settings.casualLeaveLimit);el=f(settings.earnedLeaveLimit);clCarry=f(settings.maximumClCarryForward);elCarry=f(settings.maximumElCarryForward);otRate=f(settings.overtimeRatePerHour);threshold=f(settings.attendanceThresholdPercent);bonus=f(settings.bonusIsPercentage?settings.attendanceBonusPercent:settings.attendanceBonusAmount);late=f(settings.lateArrivalGraceMinutes);bonusEnabled=new JCheckBox("Enable attendance bonus",settings.attendanceBonusEnabled);bonusPercent=new JCheckBox("% of Basic Pay",settings.bonusIsPercentage);bonusHelper=new JLabel();bonusPercent.addActionListener(e->helper());int row=0;row=row(c,row,"Weekly off days/month",weekOff);row=row(c,row,"Public holidays/month",holidays);row=row(c,row,"Max Casual Leave (CL) allowed/month",cl);row=row(c,row,"Max Earned Leave (EL) allowed/month",el);row=row(c,row,"Maximum CL Carry Forward",clCarry);row=row(c,row,"Maximum EL Carry Forward",elCarry);row=row(c,row,"Overtime rate per hour",otRate);row=row(c,row,"Attendance threshold (%)",threshold);c.gridx=0;c.gridy=row;add(new JLabel("Attendance bonus"),c);c.gridx=1;add(bonus,c);c.gridx=2;add(bonusPercent,c);c.gridx=3;add(bonusHelper,c);helper();row++;row=row(c,row,"Late-arrival grace minutes",late);c.gridx=1;c.gridy=row;add(bonusEnabled,c);JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));JButton save=new JButton("Save Attendance Rules"),cancel=new JButton("Cancel");save.addActionListener(e->save());cancel.addActionListener(e->reload());actions.add(save);actions.add(cancel);c.gridx=1;c.gridy=row+1;c.gridwidth=2;add(actions,c);}
    private void helper(){bonusHelper.setText(bonusPercent.isSelected()?"(% of Basic Salary)":"(Fixed Amount)");}
    private JTextField f(Object value){return new JTextField(value instanceof Number?Money.text(((Number)value).doubleValue()):String.valueOf(value),12);}private int row(GridBagConstraints c,int row,String label,JTextField field){c.gridx=0;c.gridy=row;add(new JLabel(label),c);c.gridx=1;add(field,c);return row+1;}
    private void reload(){AttendanceSettings saved=dao.load();settings=saved;weekOff.setText(String.valueOf(saved.weeklyOffDays));holidays.setText(String.valueOf(saved.publicHolidays));cl.setText(String.valueOf(saved.casualLeaveLimit));el.setText(String.valueOf(saved.earnedLeaveLimit));clCarry.setText(Money.text(saved.maximumClCarryForward));elCarry.setText(Money.text(saved.maximumElCarryForward));otRate.setText(Money.text(saved.overtimeRatePerHour));threshold.setText(Money.text(saved.attendanceThresholdPercent));bonus.setText(Money.text(saved.bonusIsPercentage?saved.attendanceBonusPercent:saved.attendanceBonusAmount));late.setText(String.valueOf(saved.lateArrivalGraceMinutes));bonusEnabled.setSelected(saved.attendanceBonusEnabled);bonusPercent.setSelected(saved.bonusIsPercentage);helper();}
    private void save(){try{settings.weeklyOffDays=Integer.parseInt(weekOff.getText());settings.publicHolidays=Integer.parseInt(holidays.getText());settings.casualLeaveLimit=Integer.parseInt(cl.getText());settings.earnedLeaveLimit=Integer.parseInt(el.getText());settings.maximumClCarryForward=nonNegative(clCarry,"Maximum CL Carry Forward");settings.maximumElCarryForward=nonNegative(elCarry,"Maximum EL Carry Forward");settings.overtimeRatePerHour=Double.parseDouble(otRate.getText());settings.attendanceThresholdPercent=Double.parseDouble(threshold.getText());settings.attendanceBonusEnabled=bonusEnabled.isSelected();settings.bonusIsPercentage=bonusPercent.isSelected();if(settings.bonusIsPercentage)settings.attendanceBonusPercent=Double.parseDouble(bonus.getText());else settings.attendanceBonusAmount=Double.parseDouble(bonus.getText());settings.lateArrivalGraceMinutes=Integer.parseInt(late.getText());dao.save(settings);PayrollEvents.dataChanged("settings");for(Employee employee:new EmployeeDAO().list("")){CTCStore.Value value=CTCStore.get(employee.getId());value.attendance=settings.attendanceBonusEnabled?(settings.bonusIsPercentage?settings.attendanceBonusPercent*employee.getBasicSalary()/100:settings.attendanceBonusAmount):0;}JOptionPane.showMessageDialog(this,"Attendance rules saved.");}catch(NumberFormatException|SQLException e){JOptionPane.showMessageDialog(this,e.getMessage()==null?"Enter valid numeric settings.":e.getMessage());}}
    private double nonNegative(JTextField value,String label){double number=Double.parseDouble(value.getText().trim());if(number<0)throw new NumberFormatException(label+" cannot be negative.");return number;}
}
