import javax.swing.*;import java.awt.*;import java.sql.SQLException;
public class AttendanceSettingsPanel extends JPanel {
    private final AttendanceSettingsDAO dao=new AttendanceSettingsDAO();private AttendanceSettings settings;private JTextField weekOff,holidays,cl,el,clCarry,elCarry;
    public AttendanceSettingsPanel(){setLayout(new GridBagLayout());GridBagConstraints c=new GridBagConstraints();c.insets=new Insets(7,7,7,7);c.fill=GridBagConstraints.HORIZONTAL;settings=dao.load();weekOff=f(settings.weeklyOffDays);holidays=f(settings.publicHolidays);cl=f(settings.casualLeaveLimit);el=f(settings.earnedLeaveLimit);clCarry=f(settings.maximumClCarryForward);elCarry=f(settings.maximumElCarryForward);int row=0;row=row(c,row,"Weekly off days/month",weekOff);row=row(c,row,"Public holidays/month",holidays);row=row(c,row,"Annual Casual Leave (CL) entitlement",cl);row=row(c,row,"Annual Earned Leave (EL) entitlement",el);row=row(c,row,"Maximum CL Carry Forward",clCarry);row=row(c,row,"Maximum EL Carry Forward",elCarry);JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0));JButton save=new JButton("Save Attendance Rules"),cancel=new JButton("Cancel"),edit=new JButton("Edit");save.addActionListener(e->save());cancel.addActionListener(e->reload());actions.add(save);actions.add(cancel);actions.add(edit);c.gridx=1;c.gridy=row;c.gridwidth=2;add(actions,c);}
    private JTextField f(Object value){return new JTextField(value instanceof Number?Money.text(((Number)value).doubleValue()):String.valueOf(value),12);}private int row(GridBagConstraints c,int row,String label,JTextField field){c.gridx=0;c.gridy=row;add(new JLabel(label),c);c.gridx=1;add(field,c);return row+1;}
    private void reload(){AttendanceSettings saved=dao.load();settings=saved;weekOff.setText(String.valueOf(saved.weeklyOffDays));holidays.setText(String.valueOf(saved.publicHolidays));cl.setText(String.valueOf(saved.casualLeaveLimit));el.setText(String.valueOf(saved.earnedLeaveLimit));clCarry.setText(Money.text(saved.maximumClCarryForward));elCarry.setText(Money.text(saved.maximumElCarryForward));}
    private void save(){try{settings.weeklyOffDays=whole(weekOff,"Weekly off days/month");settings.publicHolidays=whole(holidays,"Public holidays/month");settings.casualLeaveLimit=whole(cl,"Max Casual Leave (CL) allowed/month");settings.earnedLeaveLimit=whole(el,"Max Earned Leave (EL) allowed/month");settings.maximumClCarryForward=nonNegative(clCarry,"Maximum CL Carry Forward");settings.maximumElCarryForward=nonNegative(elCarry,"Maximum EL Carry Forward");dao.save(settings);PayrollEvents.dataChanged("settings");JOptionPane.showMessageDialog(this,"Attendance rules saved.");}catch(IllegalArgumentException e){JOptionPane.showMessageDialog(this,e.getMessage());}catch(SQLException e){ActivityLogger.log("Attendance Settings","SAVE FAILED",e.toString(),"FAILED");JOptionPane.showMessageDialog(this,"Attendance rules could not be saved. Please try again.");}}
    private int whole(JTextField value,String label){double number=nonNegative(value,label);if(number!=Math.floor(number))throw new IllegalArgumentException(label+" must be a whole non-negative number.");return (int)number;}
    private double nonNegative(JTextField value,String label){String text=value.getText().trim();if(text.isEmpty())throw new IllegalArgumentException(label+" must be a valid non-negative number.");try{double number=Double.parseDouble(text);if(!Double.isFinite(number)||number<0)throw new NumberFormatException();return number;}catch(NumberFormatException e){throw new IllegalArgumentException(label+" must be a valid non-negative number.");}}
}
