import javax.swing.*;import java.awt.*;import java.nio.file.*;
public final class BackupRestoreDialog extends JDialog{
 private final JTextField folder=new JTextField(28);private final JComboBox<Integer> interval=new JComboBox<>(new Integer[]{7,15,30});
 public BackupRestoreDialog(Window owner){super(owner,"Backup & Restore",ModalityType.APPLICATION_MODAL);folder.setText(BackupConfig.folder()==null?"":BackupConfig.folder().toString());interval.setSelectedItem(BackupConfig.intervalDays());JPanel form=new JPanel(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(8,8,8,8);g.fill=GridBagConstraints.HORIZONTAL;g.gridx=0;g.gridy=0;form.add(new JLabel("Backup folder:"),g);g.gridx=1;form.add(folder,g);JButton browse=new JButton("Browse");browse.addActionListener(e->chooseFolder());g.gridx=2;form.add(browse,g);g.gridx=0;g.gridy=1;form.add(new JLabel("Automatic interval:"),g);g.gridx=1;form.add(interval,g);JPanel buttons=new JPanel();JButton save=new JButton("Save"),backup=new JButton("Backup Now"),restore=new JButton("Restore from Backup");save.addActionListener(e->save());backup.addActionListener(e->backup());restore.addActionListener(e->restore());buttons.add(save);buttons.add(backup);buttons.add(restore);add(form,BorderLayout.CENTER);add(buttons,BorderLayout.SOUTH);pack();setLocationRelativeTo(owner);}
 private void chooseFolder(){JFileChooser c=new JFileChooser();c.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);if(c.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)folder.setText(c.getSelectedFile().getAbsolutePath());}
 private boolean save(){try{Path path=Path.of(folder.getText().trim());BackupConfig.folder(path);BackupConfig.intervalDays((Integer)interval.getSelectedItem());return true;}catch(Exception e){JOptionPane.showMessageDialog(this,"Choose a valid backup folder.");return false;}}
 private void backup(){if(!save())return;try{JOptionPane.showMessageDialog(this,"Backup created:\n"+BackupService.backup(BackupConfig.folder()));}catch(Exception e){JOptionPane.showMessageDialog(this,"Backup failed: "+e.getMessage());}}
 private void restore(){JFileChooser c=new JFileChooser();if(c.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;if(JOptionPane.showConfirmDialog(this,"Restore replaces the active database and local payroll files. Continue?","Confirm Restore",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;try{BackupService.restore(c.getSelectedFile().toPath());JOptionPane.showMessageDialog(this,"Restore completed. Restart the application.");}catch(Exception e){JOptionPane.showMessageDialog(this,"Restore failed: "+e.getMessage());}}
}
