import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.sql.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.zip.*;
public final class BackupService{
 public static Path backup(Path destination)throws Exception{if(destination==null)throw new IllegalArgumentException("Choose a backup folder.");Files.createDirectories(destination);Path output=destination.resolve("Payroll_Full_Backup_"+new SimpleDateFormat("yyyy-MM-dd_HHmmss").format(new java.util.Date())+".zip");try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(output))){writeDatabase(zip);Path home=Paths.get(System.getProperty("user.home"));try(DirectoryStream<Path> files=Files.newDirectoryStream(home,".payroll-*") ){for(Path file:files)if(Files.isRegularFile(file))add(zip,file,"local/"+file.getFileName());}String logo=CompanyDetailsStore.logoPath();if(logo!=null&&!logo.isBlank()&&Files.isRegularFile(Path.of(logo)))add(zip,Path.of(logo),"documents/logo-"+Path.of(logo).getFileName());}BackupConfig.completed();return output;}
public static void restore(Path archive)throws Exception{if(archive==null||!Files.isRegularFile(archive)||!archive.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".zip"))throw new IllegalArgumentException("Select a valid backup ZIP file.");Path temp=Files.createTempDirectory("payroll-restore-");try{try(ZipInputStream in=new ZipInputStream(Files.newInputStream(archive))){ZipEntry entry;boolean database=false;int entries=0;while((entry=in.getNextEntry())!=null){if(++entries>10000)throw new IOException("Invalid backup: too many archive entries.");String name=entry.getName();if(name==null||name.isBlank()||name.startsWith("/")||name.contains("..\\")||name.contains("../"))throw new IOException("Invalid backup: unsafe archive entry.");Path target=temp.resolve(name).normalize();if(entry.isDirectory())continue;if(!target.startsWith(temp))throw new IOException("Invalid backup: unsafe archive entry.");Files.createDirectories(target.getParent());Files.copy(in,target,StandardCopyOption.REPLACE_EXISTING);if("database.sql".equals(name))database=true;}if(!database||!Files.isRegularFile(temp.resolve("database.sql")))throw new IOException("Invalid backup: database.sql is missing.");}Path sql=temp.resolve("database.sql");restoreDatabase(Files.readString(sql,StandardCharsets.UTF_8));Path local=temp.resolve("local");if(Files.isDirectory(local))try(DirectoryStream<Path> files=Files.newDirectoryStream(local)){Path home=Paths.get(System.getProperty("user.home"));for(Path file:files)if(Files.isRegularFile(file)&&file.getFileName().toString().startsWith(".payroll-"))Files.copy(file,home.resolve(file.getFileName()),StandardCopyOption.REPLACE_EXISTING);}}finally{delete(temp);}}
 public static Path exportDatabaseCopy(Path destination)throws Exception{if(destination==null)throw new IllegalArgumentException("Choose a destination folder.");Files.createDirectories(destination);Path output=destination.resolve("Payroll_Database_Copy_"+new SimpleDateFormat("yyyy-MM-dd_HHmmss").format(new java.util.Date())+".db");synchronized(DBConnection.databaseLock()){try(Connection c=DBConnection.getConnection();Statement s=c==null?null:c.createStatement()){if(s==null)throw new SQLException("Database is unavailable.");String target=output.toAbsolutePath().toString().replace("'","''");s.execute("PRAGMA wal_checkpoint(FULL)");s.execute("VACUUM INTO '"+target+"'");}}return output;}
 private static void writeDatabase(ZipOutputStream zip)throws Exception{
  zip.putNextEntry(new ZipEntry("database.sql"));StringBuilder out=new StringBuilder("PRAGMA foreign_keys=OFF;\n");
  try(Connection c=DBConnection.getConnection();PreparedStatement tables=c==null?null:c.prepareStatement("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")){
   if(c==null||tables==null)throw new SQLException("Database is unavailable.");ResultSet definitions=tables.executeQuery();
   while(definitions.next()){
    String table=definitions.getString(1),safe=table.replace("\"","\"\"");String create=definitions.getString(2);if(create==null)continue;
    out.append("DROP TABLE IF EXISTS \"").append(safe).append("\";\n").append(create).append(";\n");
    try(Statement s=c.createStatement();ResultSet rows=s.executeQuery("SELECT * FROM \""+safe+"\"")){
     ResultSetMetaData md=rows.getMetaData();int count=md.getColumnCount();
     while(rows.next()){out.append("INSERT INTO \"").append(safe).append("\" VALUES(");for(int i=1;i<=count;i++){if(i>1)out.append(',');Object value=rows.getObject(i);if(value==null)out.append("NULL");else if(value instanceof Number)out.append(value);else out.append('\'').append(String.valueOf(value).replace("'","''")).append('\'');}out.append(");\n");}
    }
   }
  }
  out.append("PRAGMA foreign_keys=ON;\n");zip.write(out.toString().getBytes(StandardCharsets.UTF_8));zip.closeEntry();
 }
 private static void restoreDatabase(String sql)throws Exception{try(Connection c=DBConnection.getConnection();Statement s=c.createStatement()){if(c==null)throw new SQLException("Database is unavailable.");for(String statement:sql.split(";\\s*(?:\\r?\\n|$)")){String command=statement.trim();if(!command.isEmpty())s.execute(command);}}}
 private static void add(ZipOutputStream zip,Path file,String name)throws IOException{zip.putNextEntry(new ZipEntry(name));Files.copy(file,zip);zip.closeEntry();}
 private static void delete(Path path)throws IOException{if(!Files.exists(path))return;try(var list=Files.walk(path)){list.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(IOException ignored){}});}}
 private BackupService(){}
}
