import javax.swing.*;
import java.awt.*;
import java.sql.Timestamp;
import java.util.Arrays;

public class ChangePasswordPanel extends JPanel {
    public ChangePasswordPanel() { setLayout(new GridLayout(1, 2, 30, 0)); setBorder(BorderFactory.createEmptyBorder(24, 28, 24, 28)); buildLogin(); buildMaster(); }
    public void refresh() { }
    private JPanel card(String title) { JPanel panel = new JPanel(new GridBagLayout()); panel.setBorder(BorderFactory.createLineBorder(new Color(180, 180, 180), 1)); GridBagConstraints g = new GridBagConstraints(); g.gridx = 0; g.gridy = 0; g.gridwidth = 2; g.weightx = 1; g.fill = GridBagConstraints.HORIZONTAL; g.insets = new Insets(16, 12, 12, 12); JLabel heading = new JLabel(title, SwingConstants.CENTER); heading.setFont(new Font("SansSerif", Font.BOLD, 20)); heading.setForeground(new Color(30, 40, 60)); panel.add(heading, g); return panel; }
    private void row(JPanel panel, GridBagConstraints g, int y, String label, JComponent field) { g.gridx = 0; g.gridy = y + 1; g.gridwidth = 1; g.weightx = 0; g.fill = GridBagConstraints.NONE; JLabel text = new JLabel(label); text.setFont(new Font("SansSerif", Font.BOLD, 16)); panel.add(text, g); field.setFont(new Font("SansSerif", Font.PLAIN, 16)); g.gridx = 1; g.weightx = 1; g.fill = GridBagConstraints.HORIZONTAL; panel.add(field, g); }
    private JButton button(String text) { JButton button = new JButton(text); button.setFont(new Font("SansSerif", Font.BOLD, 15)); return button; }
    private void buildLogin() { JPanel panel = card("Application Login"); GridBagConstraints g = new GridBagConstraints(); g.insets = new Insets(8, 8, 8, 8); JTextField username = new JTextField(Session.currentUser == null ? "" : Session.currentUser, 18); JPasswordField current = new JPasswordField(18), next = new JPasswordField(18), confirm = new JPasswordField(18); row(panel, g, 0, "Username", username); row(panel, g, 1, "Current Password", current); row(panel, g, 2, "New Password", next); row(panel, g, 3, "Confirm Password", confirm); JButton change = button("Change Login Password"); change.addActionListener(e -> { String active = Session.currentUser; if (!UserAuthentication.verify(active, current.getPassword())) { JOptionPane.showMessageDialog(this, "Incorrect Current Password. Changes denied."); return; } if (!Arrays.equals(next.getPassword(), confirm.getPassword()) || !UserAuthentication.isPasswordCompliant(next.getPassword())) { JOptionPane.showMessageDialog(this, "Passwords must match and meet the password policy."); return; } if (!UserAuthentication.updateCredentials(active, username.getText(), next.getPassword())) { JOptionPane.showMessageDialog(this, "Could not update application credentials."); return; } AuditLogDAO.logActivity(Session.currentUser, "APP_PASSWORD_CHANGED", "Application login credentials updated", new Timestamp(System.currentTimeMillis())); ActivityLogger.log("Security", "APP PASSWORD CHANGED", "Application login credentials updated", "SUCCESS"); JOptionPane.showMessageDialog(this, "Application login credentials updated successfully."); current.setText(""); next.setText(""); confirm.setText(""); }); g.gridx = 1; g.gridy = 5; g.weightx = 1; g.fill = GridBagConstraints.NONE; panel.add(change, g); add(panel); }
    private void buildMaster() { JPanel panel = card("Master Data Login"); GridBagConstraints g = new GridBagConstraints(); g.insets = new Insets(8, 8, 8, 8); JPasswordField current = new JPasswordField(18), next = new JPasswordField(18), confirm = new JPasswordField(18); row(panel, g, 0, "Current Password", current); row(panel, g, 1, "New Password", next); row(panel, g, 2, "Confirm Password", confirm); JButton change = button("Change Master Data Password"); change.addActionListener(e -> { if (SecurityService.hasMasterPassword() && !SecurityService.verifyMasterPassword(current.getPassword())) { JOptionPane.showMessageDialog(this, "Incorrect Current Password. Changes denied."); return; } if (!Arrays.equals(next.getPassword(), confirm.getPassword())) { JOptionPane.showMessageDialog(this, "New Master Data passwords do not match."); return; } if (!SecurityService.setMasterPassword(next.getPassword())) { JOptionPane.showMessageDialog(this, "Could not update Master Data password."); return; } AuditLogDAO.logActivity(Session.currentUser, "MASTER_DATA_PASSWORD_CHANGED", "Master Data security password updated", new Timestamp(System.currentTimeMillis())); ActivityLogger.log("Security", "MASTER DATA PASSWORD CHANGED", "Master Data security password updated", "SUCCESS"); JOptionPane.showMessageDialog(this, "Master Data password updated successfully."); current.setText(""); next.setText(""); confirm.setText(""); }); g.gridx = 1; g.gridy = 4; g.weightx = 1; g.fill = GridBagConstraints.NONE; panel.add(change, g); add(panel); }
}
