import java.sql.*;
/** Shared allowance/deduction configuration persisted in SQLite. */
public final class CompanyPolicyStore {
 public static final String[] ALLOWANCES={"HRA","Attendance Bonus","Conveyance Allowance","Performance Pay","Medical Allowance","Special Allowance","Fixed Allowance"};public static final String[] DEDUCTIONS={"ESIC","EPF","Employer EPF","PT","TDS","Salary Advance"};
 private static String key(String group,String name){return group+":"+name;}private static String read(String group,String name){try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT rule_value FROM settings_attendance_leave_rules WHERE rule_name=?")){if(p==null)return null;p.setString(1,key(group,name));ResultSet r=p.executeQuery();return r.next()?r.getString(1):null;}catch(SQLException e){return null;}}private static void write(String group,String name,String value){try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("INSERT INTO settings_attendance_leave_rules(rule_name,rule_value) VALUES(?,?) ON CONFLICT(rule_name) DO UPDATE SET rule_value=excluded.rule_value")){if(p==null)return;p.setString(1,key(group,name));p.setString(2,value);p.executeUpdate();}catch(SQLException ignored){}}
 public static boolean hasAllowance(String n){return read("ALLOW",n)!=null;}public static double allowance(String n){try{return Double.parseDouble(read("ALLOW",n).split("\\|")[0]);}catch(Exception e){return 0;}}public static void allowance(String n,double v){write("ALLOW",n,Money.round(v)+"|"+(percentage(n)?1:0));}public static boolean percentage(String n){try{return "1".equals(read("ALLOW",n).split("\\|")[1]);}catch(Exception e){return false;}}public static void percentage(String n,boolean v){write("ALLOW",n,allowance(n)+"|"+(v?1:0));}public static boolean percentage(){return false;}public static void percentage(boolean v){}
 public static boolean hasDeduction(String n){return read("DEDUCT",n)!=null;}public static double deduction(String n){try{return Double.parseDouble(read("DEDUCT",n).split("\\|")[0]);}catch(Exception e){return 0;}}public static void deduction(String n,double v){write("DEDUCT",n,Money.round(v)+"|"+(deductionPercentage(n)?1:0));}public static boolean deductionPercentage(String n){try{return "1".equals(read("DEDUCT",n).split("\\|")[1]);}catch(Exception e){return false;}}public static void deductionPercentage(String n,boolean v){write("DEDUCT",n,deduction(n)+"|"+(v?1:0));}
 public static boolean restrictEpfToCeiling(){return "1".equals(read("CONFIG","restrictEpfCeiling"));}public static void restrictEpfToCeiling(boolean v){write("CONFIG","restrictEpfCeiling",v?"1":"0");}public static double otMultiplier(){return number("otMultiplier",2);}public static void otMultiplier(double v){write("CONFIG","otMultiplier",String.valueOf(v));}public static double maxOtLimit(){return number("maxOtLimit",30);}public static void maxOtLimit(double v){write("CONFIG","maxOtLimit",String.valueOf(v));}public static double maxTotalLimit(){return number("maxTotalLimit",200);}public static void maxTotalLimit(double v){write("CONFIG","maxTotalLimit",String.valueOf(v));}private static double number(String n,double d){try{return Double.parseDouble(read("CONFIG",n));}catch(Exception e){return d;}}private CompanyPolicyStore(){}
}
