import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.time.Duration;

/** Recovery is authorized by the licensing service; no recovery secret exists in this application. */
public final class CredentialRecoveryService {
    private static final String ENDPOINT=System.getProperty("payroll.license.url","https://payroll-license-api.yasl-server.workers.dev").replaceAll("/$","");
    private static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
    public static Result recover(String recoveryCode){if(recoveryCode==null||recoveryCode.isBlank())return denied("Enter the recovery code provided by support.");String key=LicenseService.savedLicenseKey();if(key.isBlank())return denied("This installation has no active license record.");try{String body="{\"licenseKey\":\""+json(key)+"\",\"machineId\":\""+LicenseService.machineId()+"\",\"recoveryCode\":\""+json(recoveryCode.trim())+"\"}";HttpRequest request=HttpRequest.newBuilder(URI.create(ENDPOINT+"/v1/recovery/verify")).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<String> response=HTTP.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2||!response.body().contains("\"valid\":true"))return denied("The recovery code is invalid, expired, or has already been used.");if(!resetLocalCredentials())return denied("Recovery was approved, but local credentials could not be updated.");ActivityLogger.log("Security","CREDENTIALS RESET","Support-authorized credential recovery completed","SUCCESS");return Result.allowed();}catch(Exception e){return denied("Could not verify the recovery code. Check the internet connection and try again.");}}
    public static Result checkForReset(){String key=LicenseService.savedLicenseKey();if(key.isBlank())return denied("This installation has no active license record.");try{String body="{\"licenseKey\":\""+json(key)+"\",\"machineId\":\""+LicenseService.machineId()+"\"}";HttpRequest request=HttpRequest.newBuilder(URI.create(ENDPOINT+"/v1/recovery/check")).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<String> response=HTTP.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100!=2||!response.body().contains("\"valid\":true"))return Result.denied("No credential reset is currently available for this Support ID.");if(!resetLocalCredentials())return denied("Reset was approved, but local credentials could not be updated.");ActivityLogger.log("Security","CREDENTIALS RESET","Support-authorized credential recovery completed","SUCCESS");return Result.allowed();}catch(Exception e){return denied("Could not check for a credential reset. Check the internet connection and try again.");}}
    private static Result denied(String message){ActivityLogger.log("Security","CREDENTIAL RECOVERY FAILED",message,"FAILED");return Result.denied(message);}
    private static boolean resetLocalCredentials(){synchronized(DBConnection.databaseLock()){try(Connection c=DBConnection.getConnection()){if(c==null)return false;c.setAutoCommit(false);try{UserAuthentication.resetForRecoveredInstallation(c);SecurityService.resetForRecoveredInstallation(c);c.commit();SecurityService.markConfigured();return true;}catch(Exception e){c.rollback();return false;}finally{c.setAutoCommit(true);}}catch(Exception ignored){return false;}}}
    private static String json(String value){return value.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
    public record Result(boolean recovered,String message){static Result allowed(){return new Result(true,"Credentials have been reset successfully. Please log in using the temporary credentials provided by support and change them from Settings.");}static Result denied(String message){return new Result(false,message);}}
    private CredentialRecoveryService(){}
}
