import javax.swing.table.DefaultTableModel;import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.time.*;import java.time.format.DateTimeFormatter;
/** Compact dependency-free CTC sheet PDF export. */
public final class CTCPDF{
 public static File create(Employee employee,DefaultTableModel model,File folder){try{if(folder==null)return null;folder.mkdirs();File out=new File(folder,safe(employee.getId())+"-CTC.pdf");StringBuilder c=new StringBuilder();
  text(c,"COST TO COMPANY",42,812,18,true);text(c,"Employee Details",42,785,13,true);
  String[][] details={{"Employee ID",textValue(employee.getId()),"Employee Name",textValue(employee.getName())},{"Designation",textValue(employee.getDesignation()),"Date of Birth",textValue(employee.getDob())},{"Age",age(employee.getDob()),"Date of Joining",textValue(employee.getJoiningDate())}};int top=775;for(int r=0;r<details.length;r++){int y=top-r*22,bottom=y-18,baseline=cellTextY(bottom,22,9);grid(c,40,bottom,515,22,new int[]{120,240,360,480,555});text(c,details[r][0],48,baseline,9,true);text(c,details[r][1],128,baseline,9,false);text(c,details[r][2],248,baseline,9,true);text(c,details[r][3],368,baseline,9,false);}
  int y=694,headerBottom=y-18,headerBaseline=cellTextY(headerBottom,22,10);grid(c,40,headerBottom,515,22,new int[]{40,310,440,555});text(c,"Component Category",48,headerBaseline,10,true);text(c,"Annual",382,headerBaseline,10,true);text(c,"Monthly Net Pay",453,headerBaseline,10,true);
  for(int r=0;r<model.getRowCount()&&y>125;r++){String label=value(model,r,0);if(!employee.isWagesStructure()&&label.trim().equals("Attendance Bonus"))continue;String annual=value(model,r,1),monthly=value(model,r,2);int bottom=y-39,baseline=cellTextY(bottom,21,9);grid(c,40,bottom,515,21,new int[]{40,310,440,555});text(c,label,48,baseline,9,false);right(c,432,baseline,annual,9);right(c,547,baseline,monthly,9);y-=21;}byte[] stream=c.toString().getBytes(StandardCharsets.ISO_8859_1);String pdf="%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 4 0 R/F2 5 0 R>>>>/Contents 6 0 R>>endobj\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica-Bold>>endobj\n6 0 obj<</Length "+stream.length+">>stream\n"+c+"\nendstream endobj\ntrailer<</Root 1 0 R>>\n%%EOF";Files.write(out.toPath(),pdf.getBytes(StandardCharsets.ISO_8859_1));return out;}catch(Exception ignored){return null;}}
 private static void grid(StringBuilder c,int x,int y,int width,int height,int[] lines){c.append("0 0 0 RG 0.6 w ").append(x).append(' ').append(y).append(' ').append(width).append(' ').append(height).append(" re S\n");for(int line:lines)if(line>x&&line<x+width)c.append(line).append(' ').append(y).append(" m ").append(line).append(' ').append(y+height).append(" l S\n");}
 private static int cellTextY(int bottom,int height,int size){int padding=5;return bottom+padding+Math.max(0,(height-padding*2-size)/2)+size-4;}
 private static void text(StringBuilder c,String value,int x,int y,int size,boolean bold){c.append("BT /").append(bold?"F2":"F1").append(' ').append(size).append(" Tf ").append(x).append(' ').append(y).append(" Td (").append(esc(value)).append(") Tj ET\n");}
 private static void right(StringBuilder c,int right,int y,String value,int size){text(c,value,Math.max(45,right-esc(value).length()*size/2),y,size,false);}
 private static String value(DefaultTableModel m,int r,int col){Object v=m.getValueAt(r,col);return v==null?"":String.valueOf(v);}
 private static String age(String dob){try{return String.valueOf(Period.between(LocalDate.parse(dob,DateTimeFormatter.ofPattern("dd-MM-uuuu")),LocalDate.now()).getYears());}catch(Exception e){return "";}}
 private static String safe(String value){return value==null?"":value.replaceAll("[^a-zA-Z0-9_-]","_");}private static String textValue(String value){return value==null?"":value;}private static String esc(String value){return String.valueOf(value).replace("\\","\\\\").replace("(","\\(").replace(")","\\)").replaceAll("[^\\x20-\\x7E]","");}private CTCPDF(){}
}
