import javax.swing.*;import javax.swing.event.*;import javax.swing.table.*;import java.awt.*;import java.awt.event.*;import java.time.*;import java.util.*;

public class CTCPanel extends JPanel {
    private static final int ROW_ARREARS=11;
    private final EmployeeDAO employees=new EmployeeDAO();private final CTCOtherEarningsDAO otherDAO=new CTCOtherEarningsDAO();private final AttendanceDAO attendanceDAO=new AttendanceDAO();private final AttendanceSettingsDAO attendanceSettingsDAO=new AttendanceSettingsDAO();private int allowanceYear=FinancialYear.currentStart(),otherYear=FinancialYear.currentStart();private JTabbedPane allowanceMonths,otherMonths;private JComboBox<Object> employeeSelector;
    public CTCPanel(){setLayout(new BorderLayout());JTabbedPane tabs=new JTabbedPane();tabs.addTab("Salary",salaryCtc());tabs.addTab("Revision",salaryRevision());add(tabs,BorderLayout.CENTER);addComponentListener(new ComponentAdapter(){public void componentShown(ComponentEvent e){refresh();}});}
    public void refresh(){if(employeeSelector!=null){Object selected=employeeSelector.getSelectedItem();employeeSelector.removeAllItems();employeeSelector.addItem("-- Select Employee --");for(Employee employee:employees.listActive(""))employeeSelector.addItem(employee);employeeSelector.setSelectedItem(selected);}if(allowanceMonths!=null)buildAllowanceTabs();if(otherMonths!=null)buildOtherTabs();}

    private JComponent salaryCtc(){
        JPanel panel=new JPanel(new BorderLayout(8,8)); panel.setBorder(BorderFactory.createEmptyBorder(10,12,10,12));
        employeeSelector=new JComboBox<>(); JComboBox<Object> selector=employeeSelector; selector.addItem("-- Select Employee --"); for(Employee employee:employees.listActive(""))selector.addItem(employee); selector.setSelectedIndex(0);
        JPanel top=new JPanel(new BorderLayout(10,8)); JPanel choose=new JPanel(new FlowLayout(FlowLayout.LEFT,8,0)); choose.add(new JLabel("Select Employee:")); selector.setPreferredSize(new Dimension(320,32)); choose.add(selector); top.add(choose,BorderLayout.NORTH);
        JTextField[] details={readonly(),readonly(),readonly(),readonly(),readonly(),readonly()}; for(JTextField field:details)field.setText("-"); String[] labels={"Employee ID","Name","Designation","Date of Birth","Age","Date of Joining"}; JPanel detailsPanel=new JPanel(new GridLayout(2,6,8,4)); for(int i=0;i<labels.length;i++){JPanel cell=new JPanel(new BorderLayout(2,2));cell.add(new JLabel(labels[i]),BorderLayout.NORTH);cell.add(details[i],BorderLayout.CENTER);detailsPanel.add(cell);} top.add(detailsPanel,BorderLayout.CENTER);
        String[] columns={"Component Category","Annual","Monthly Net pay"}; String[] categories={"Fixed Compensation","   Basic","Allowances","   HRA","   Attendance Bonus","   Conveyance Allowance","   Performance Pay","   Medical Allowance","   Special Allowance","   Fixed Allowance","Annual Component","   Arrears","   Annual Bonus","Expense to Company","   Employer Provident Fund","   ESIC Employer Share","   Health Insurance","Retirals","   Gratuity (Basic*15/26)","Total Annual CTC","Total Gross Salary","Less: Deductions","   Employee Provident Fund","   PT","   ESIC","   Income Tax / TDS","Net Pay"};
        Object[][] rows=new Object[categories.length][3];for(int i=0;i<categories.length;i++)rows[i][0]=categories[i]; final boolean[] calculated={false},updating={false},editing={false},restoring={false};final Object[][][] snapshot=new Object[1][][];
        DefaultTableModel model=new DefaultTableModel(rows,columns){private final Set<Integer> headings=new HashSet<>(Arrays.asList(0,2,10,13,17,19,20,21,26));private final Set<Integer> annualOnly=new HashSet<>(Arrays.asList(11,12,14,15,16,18));public boolean isCellEditable(int r,int c){return editing[0]&&c>0&&!headings.contains(r)&&!(c==2&&annualOnly.contains(r))&&(r==1||calculated[0]);}}; JTable table=new JTable(model);TableRowSorter<DefaultTableModel> ctcSorter=new TableRowSorter<>(model);table.setRowSorter(ctcSorter);UIStyleUtility.applyProfessionalTableStyle(table);table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);table.getColumnModel().getColumn(0).setPreferredWidth(430);table.getColumnModel().getColumn(1).setPreferredWidth(210);table.getColumnModel().getColumn(2).setPreferredWidth(210);table.getColumnModel().getColumn(1).setCellRenderer(ctcMoneyRenderer(selector));table.getColumnModel().getColumn(2).setCellRenderer(ctcMoneyRenderer(selector));table.getColumnModel().getColumn(1).setCellEditor(selectAllEditor());table.getColumnModel().getColumn(2).setCellEditor(selectAllEditor());
        JLabel overrideWarning=new JLabel("Not according to Settings");overrideWarning.setForeground(new Color(190,70,70));overrideWarning.setVisible(false);
        JButton editCancel=new JButton("Edit");editCancel.setEnabled(false);JButton calculate=new JButton("Calculate Allowances & Deductions"); calculate.setEnabled(false); calculate.addActionListener(e->{Employee employee=selectedEmployee(selector);if(employee==null){JOptionPane.showMessageDialog(this,"Select an employee first.");return;}double basic=ctcNumber(model,1,1),arrears=ctcNumber(model,ROW_ARREARS,1),annualBonus=ctcNumber(model,12,1);if(basic<=0){JOptionPane.showMessageDialog(this,"Enter Basic pay before calculating CTC.");return;}calculateCtc(model,basic,updating,employee);model.setValueAt(arrears,ROW_ARREARS,1);model.setValueAt(annualBonus,12,1);recalculateCtcTotals(model);if(!employee.isWagesStructure())model.setValueAt(0.0,4,1);calculated[0]=true;ActivityLogger.log("CTC","CTC CALCULATED",employee.getId(),"UPDATE");table.repaint();});
        JButton save=new JButton("Save CTC");save.setEnabled(false);save.addActionListener(e->{Employee employee=selectedEmployee(selector);if(employee==null)return;copyCtc(model,CTCStore.get(employee.getId()));CTCStore.flush();AutoSaveService.markDirty();editing[0]=false;save.setEnabled(false);editCancel.setText("Edit");calculate.setEnabled(false);ActivityLogger.log("CTC","CTC SHEET SAVED",employee.getId()+" - "+employee.getName(),"SUCCESS");});
        selector.addActionListener(e->{Employee employee=selectedEmployee(selector);ctcSorter.setRowFilter(employee!=null&&!employee.isWagesStructure()?new RowFilter<DefaultTableModel,Integer>(){public boolean include(Entry<? extends DefaultTableModel,? extends Integer> entry){return entry.getIdentifier()!=4;}}:null);calculated[0]=false;updating[0]=true;for(int r=0;r<model.getRowCount();r++){model.setValueAt(null,r,1);model.setValueAt(null,r,2);}if(employee!=null){details[0].setText(safe(employee.getId()));details[1].setText(safe(employee.getName()));details[2].setText(safe(employee.getDesignation()));details[3].setText(safe(employee.getDob()));details[4].setText(age(employee.getDob()));details[5].setText(safe(employee.getJoiningDate()));CTCStore.Value saved=CTCStore.get(employee.getId());if(saved.basic>0){loadSavedCtc(model,saved);if(!employee.isWagesStructure())model.setValueAt(0.0,4,1);calculated[0]=true;}overrideWarning.setVisible(hasVisibleAllowanceOverride(saved,employee));}else{for(JTextField f:details)f.setText("-");overrideWarning.setVisible(false);}updating[0]=false;model.fireTableDataChanged();table.repaint();calculate.setEnabled(employee!=null&&editing[0]);save.setEnabled(employee!=null&&editing[0]);});
        model.addTableModelListener(event->{if(event.getType()!=TableModelEvent.UPDATE||restoring[0]||updating[0]||!editing[0])return;int row=event.getFirstRow(),column=event.getColumn();if(row<0)return;updating[0]=true;try{if(column==2&&monthlyBackedByAnnual(row))model.setValueAt(Money.round(ctcNumber(model,row,2)*12),row,1);Employee employee=selectedEmployee(selector);if(employee!=null&&row>=3&&row<=9){CTCStore.Value value=CTCStore.get(employee.getId());markAllowanceOverride(value,row,model);overrideWarning.setVisible(hasVisibleAllowanceOverride(value,employee));overrideWarning.setToolTipText(overrideWarning.isVisible()?"One or more allowance values differ from Settings.":null);}recalculateCtcTotals(model);}finally{updating[0]=false;}table.repaint();});
        editCancel.addActionListener(e->{if(!editing[0]){snapshot[0]=copyModel(model);editing[0]=true;editCancel.setText("Cancel");calculate.setEnabled(true);save.setEnabled(true);}else{restoring[0]=true;UIStyleUtility.restoreTableValues(model,snapshot[0]);restoring[0]=false;editing[0]=false;editCancel.setText("Edit");calculate.setEnabled(false);save.setEnabled(false);}table.repaint();});JButton excel=new JButton("Export Excel");excel.addActionListener(e->exportCtcExcel(model,selectedEmployee(selector)));
        JButton pdf=new JButton("Download as PDF");pdf.addActionListener(e->downloadCtcPdf(model,selectedEmployee(selector)));
        selector.addActionListener(e->{editCancel.setEnabled(selectedEmployee(selector)!=null);});JScrollPane tableScroll=new JScrollPane(table);tableScroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);panel.add(top,BorderLayout.NORTH);panel.add(tableScroll,BorderLayout.CENTER);JPanel bottom=new JPanel(new BorderLayout());JPanel buttons=new JPanel(new FlowLayout(FlowLayout.RIGHT));buttons.add(calculate);buttons.add(pdf);buttons.add(excel);buttons.add(editCancel);buttons.add(save);bottom.add(buttons,BorderLayout.EAST);bottom.add(overrideWarning,BorderLayout.WEST);panel.add(bottom,BorderLayout.SOUTH);return panel;
    }

    private DefaultCellEditor selectAllEditor(){return new DefaultCellEditor(new JTextField()){public Component getTableCellEditorComponent(JTable table,Object value,boolean selected,int row,int column){JTextField field=(JTextField)super.getTableCellEditorComponent(table,value,selected,row,column);field.selectAll();return field;}};}
    private JTextField readonly(){JTextField field=new JTextField();field.setEditable(false);return field;}
    private Employee selectedEmployee(JComboBox<?> selector){Object selected=selector.getSelectedItem();return selected instanceof Employee?(Employee)selected:null;}
    private String safe(String value){return value==null?"":value;}
    private String age(String dob){try{return String.valueOf(Period.between(LocalDate.parse(dob,java.time.format.DateTimeFormatter.ofPattern("dd-MM-uuuu")),LocalDate.now()).getYears());}catch(Exception ignored){return "";}}
    private javax.swing.table.TableCellRenderer ctcMoneyRenderer(JComboBox<?> selector){return new DefaultTableCellRenderer(){public Component getTableCellRendererComponent(JTable table,Object value,boolean selected,boolean focused,int row,int column){super.getTableCellRendererComponent(table,value,selected,focused,row,column);if(value==null||"-".equals(value))setText(value==null?"":String.valueOf(value));else try{setText(Money.text(Double.parseDouble(String.valueOf(value))));}catch(Exception ignored){}Employee employee=selectedEmployee(selector);int modelRow=table.convertRowIndexToModel(row);boolean overridden=employee!=null&&isOverridden(CTCStore.get(employee.getId()),modelRow);setOpaque(true);if(!selected)setBackground(overridden?new Color(255,230,230):Color.WHITE);return this;}};}
    private boolean isOverridden(CTCStore.Value value,int row){return row==3&&value.hraOverride||row==4&&value.attendanceOverride||row==5&&value.conveyanceOverride||row==6&&value.performanceOverride||row==7&&value.medicalOverride||row==8&&value.specialOverride||row==9&&value.fixedOverride;}
    private static Object[][] copyRows(Object[][] source){Object[][] copy=new Object[source.length][];for(int row=0;row<source.length;row++)copy[row]=Arrays.copyOf(source[row],source[row].length);return copy;}
    private static Object[][] copyModel(DefaultTableModel model){Object[][] copy=new Object[model.getRowCount()][model.getColumnCount()];for(int row=0;row<copy.length;row++)for(int column=0;column<copy[row].length;column++)copy[row][column]=model.getValueAt(row,column);return copy;}
    private double ctcNumber(DefaultTableModel model,int row,int column){try{return Money.round(Double.parseDouble(String.valueOf(model.getValueAt(row,column)).trim()));}catch(Exception ignored){return 0;}}
    private double ctcAllowance(String key,double annualBasic){if(!CompanyPolicyStore.hasAllowance(key))return 0.0;double value=CompanyPolicyStore.allowance(key);return Money.round(CompanyPolicyStore.percentage(key)?annualBasic*value/100:value*12);}
    private void calculateCtc(DefaultTableModel model,double basic,boolean[] updating,Employee employee){CTCStore.Value custom=CTCStore.get(employee.getId());updating[0]=true;try{model.setValueAt(Money.round(basic),1,1);model.setValueAt(custom.hraOverride?Money.round(basic*custom.hraOverridePercent/100.0):ctcAllowance("HRA",basic),3,1);model.setValueAt(employee.isWagesStructure()?allowanceValue(custom.attendanceOverride,custom.attendance,"Attendance Bonus",basic):0,4,1);model.setValueAt(allowanceValue(custom.conveyanceOverride,custom.conveyance,"Conveyance Allowance",basic),5,1);model.setValueAt(allowanceValue(custom.performanceOverride,custom.performance,"Performance Pay",basic),6,1);model.setValueAt(allowanceValue(custom.medicalOverride,custom.medical,"Medical Allowance",basic),7,1);model.setValueAt(allowanceValue(custom.specialOverride,custom.special,"Special Allowance",basic),8,1);model.setValueAt(allowanceValue(custom.fixedOverride,custom.fixed,"Fixed Allowance",basic),9,1);model.setValueAt(0.0,11,1);model.setValueAt(0.0,12,1);double gross=ctcGross(model),employerEpfRate=CompanyPolicyStore.hasDeduction("Employer EPF")?CompanyPolicyStore.deduction("Employer EPF"):12.0,annualEsicThreshold=PayrollRulesStore.esicCeiling()*12.0;double employeeEpf=Math.round(PayrollCalculator.monthlyEpf(employee,basic/12.0)*12.0),employerEpf=Math.round(basic*employerEpfRate/100),employerEsic=gross<=annualEsicThreshold?Money.round(gross*PayrollRulesStore.esicEmployerRate()/100):0,employeeEsic=gross<=annualEsicThreshold?Money.round(gross*PayrollRulesStore.esicRate()/100):0;double ptSetting=CompanyPolicyStore.hasDeduction("PT")?CompanyPolicyStore.deduction("PT"):PayrollRulesStore.ptAmount(),monthlyPt=CompanyPolicyStore.deductionPercentage("PT")?Money.round(gross/12.0*ptSetting/100.0):(ptSetting>0?ptSetting:200.0);model.setValueAt(employerEpf,14,1);model.setValueAt(employerEsic,15,1);model.setValueAt(0.0,16,1);model.setValueAt(Money.round((basic/12.0)*(15.0/26.0)),18,1);model.setValueAt(employeeEpf,22,1);model.setValueAt(gross>0?Money.round(monthlyPt*12.0):0.0,23,1);model.setValueAt(employeeEsic,24,1);model.setValueAt(TDSCalculator.monthlyTds(gross)*12.0,25,1);recalculateCtcTotals(model);}finally{updating[0]=false;}}
    private double allowanceValue(boolean overridden,double custom,String name,double basic){return overridden?custom:ctcAllowance(name,basic);}
    private void markAllowanceOverride(CTCStore.Value value,int row,DefaultTableModel model){double basic=ctcNumber(model,1,1),current=ctcNumber(model,row,1);switch(row){case 3->{value.hraOverride=!sameAllowance(current,ctcAllowance("HRA",basic));value.hraOverridePercent=basic<=0?0:Money.round(current*100.0/basic);}case 4->value.attendanceOverride=!sameAllowance(current,ctcAllowance("Attendance Bonus",basic));case 5->value.conveyanceOverride=!sameAllowance(current,ctcAllowance("Conveyance Allowance",basic));case 6->value.performanceOverride=!sameAllowance(current,ctcAllowance("Performance Pay",basic));case 7->value.medicalOverride=!sameAllowance(current,ctcAllowance("Medical Allowance",basic));case 8->value.specialOverride=!sameAllowance(current,ctcAllowance("Special Allowance",basic));case 9->value.fixedOverride=!sameAllowance(current,ctcAllowance("Fixed Allowance",basic));}}
    private boolean sameAllowance(double left,double right){return Math.abs(left-right)<.005;}
    private boolean hasAllowanceOverride(CTCStore.Value value){return value.hraOverride||value.attendanceOverride||value.conveyanceOverride||value.performanceOverride||value.medicalOverride||value.specialOverride||value.fixedOverride;}
    private boolean hasVisibleAllowanceOverride(CTCStore.Value value,Employee employee){return value.hraOverride||(employee.isWagesStructure()&&value.attendanceOverride)||value.conveyanceOverride||value.performanceOverride||value.medicalOverride||value.specialOverride||value.fixedOverride;}
    private double ctcGross(DefaultTableModel model){double gross=ctcNumber(model,1,1);for(int row=3;row<=9;row++)gross+=ctcNumber(model,row,1);gross+=ctcNumber(model,ROW_ARREARS,1)+ctcNumber(model,12,1);return Money.round(gross);}
    private boolean monthlyBackedByAnnual(int row){return row==1||(row>=3&&row<=9)||(row>=22&&row<=25);}
    private void recalculateCtcTotals(DefaultTableModel model){double gross=ctcGross(model),annualCtc=gross+ctcNumber(model,12,1)+ctcNumber(model,14,1)+ctcNumber(model,15,1)+ctcNumber(model,16,1)+ctcNumber(model,18,1),ptSetting=CompanyPolicyStore.hasDeduction("PT")?CompanyPolicyStore.deduction("PT"):PayrollRulesStore.ptAmount(),monthlyPt=CompanyPolicyStore.deductionPercentage("PT")?Money.round(gross/12.0*ptSetting/100.0):(ptSetting>0?ptSetting:200.0);model.setValueAt(gross>0?Money.round(monthlyPt*12.0):0.0,23,1);model.setValueAt(TDSCalculator.monthlyTds(gross)*12.0,25,1);double deductions=ctcNumber(model,22,1)+ctcNumber(model,23,1)+ctcNumber(model,24,1)+ctcNumber(model,25,1);model.setValueAt(Money.round(annualCtc),19,1);model.setValueAt(Money.round(gross),20,1);model.setValueAt(Money.round(gross-deductions),26,1);Set<Integer> nonMonthly=new HashSet<>(Arrays.asList(ROW_ARREARS,12,14,15,16,18,19));for(int row=0;row<model.getRowCount();row++){if(new HashSet<>(Arrays.asList(0,2,10,13,17,21)).contains(row))model.setValueAt(null,row,2);else if(nonMonthly.contains(row))model.setValueAt("-",row,2);else model.setValueAt(Money.round(ctcNumber(model,row,1)/12.0),row,2);}}
    private void loadSavedCtc(DefaultTableModel model,CTCStore.Value v){double[] values={v.basic,v.hra,v.attendance,v.conveyance,v.performance,v.medical,v.special,v.fixed,v.arrears,v.annualBonus,v.employerEpf,v.employerEsic,v.healthInsurance,v.gratuity,v.employeeEpf,v.pt,v.esic,v.incomeTax};int[] rows={1,3,4,5,6,7,8,9,11,12,14,15,16,18,22,23,24,25};for(int i=0;i<rows.length;i++)model.setValueAt(Money.round(values[i]),rows[i],1);recalculateCtcTotals(model);}
    private void copyCtc(DefaultTableModel model,CTCStore.Value v){v.basic=ctcNumber(model,1,1);v.hra=ctcNumber(model,3,1);v.attendance=ctcNumber(model,4,1);v.conveyance=ctcNumber(model,5,1);v.performance=ctcNumber(model,6,1);v.medical=ctcNumber(model,7,1);v.special=ctcNumber(model,8,1);v.fixed=ctcNumber(model,9,1);v.arrears=ctcNumber(model,11,1);v.annualBonus=ctcNumber(model,12,1);v.employerEpf=ctcNumber(model,14,1);v.employerEsic=ctcNumber(model,15,1);v.healthInsurance=ctcNumber(model,16,1);v.gratuity=ctcNumber(model,18,1);v.employeeEpf=ctcNumber(model,22,1);v.pt=ctcNumber(model,23,1);v.esic=ctcNumber(model,24,1);v.incomeTax=ctcNumber(model,25,1);v.annualGrossSalary=ctcNumber(model,20,1);}
    private void exportCtcExcel(DefaultTableModel model,Employee employee){if(employee==null){JOptionPane.showMessageDialog(this,"Select an employee first.");return;}java.util.List<Object[]> rows=new ArrayList<>();for(int r=0;r<model.getRowCount();r++){String component=String.valueOf(model.getValueAt(r,0));if(!employee.isWagesStructure()&&component.trim().equals("Attendance Bonus"))continue;rows.add(new Object[]{component,model.getValueAt(r,1),model.getValueAt(r,2)});}PayrollExcel.exportWithDetails(this,"CTC",employee.getId()+"-CTC.xlsx",new String[]{"Employee ID",employee.getId(),"Employee Name",employee.getName(),"Designation",safe(employee.getDesignation()),"Date of Birth",safe(employee.getDob()),"Age",age(employee.getDob()),"Date of Joining",safe(employee.getJoiningDate())},new String[]{"Component Category","Annual","Monthly Net Pay"},rows);ActivityLogger.log("CTC","CTC EXPORTED TO EXCEL",employee.getId(),"SUCCESS");}
    private void downloadCtcPdf(DefaultTableModel model,Employee employee){if(employee==null){JOptionPane.showMessageDialog(this,"Select an employee first.");return;}JFileChooser chooser=new JFileChooser();chooser.setDialogTitle("Save CTC PDF");chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);if(chooser.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;java.io.File file=CTCPDF.create(employee,model,chooser.getSelectedFile());if(file==null)JOptionPane.showMessageDialog(this,"Could not create the CTC PDF.");else{ActivityLogger.log("CTC","CTC PDF EXPORTED",file.getAbsolutePath(),"SUCCESS");JOptionPane.showMessageDialog(this,"CTC PDF saved: "+file.getName());}}
    private JComponent monthlyAllowance(){JPanel panel=new JPanel(new BorderLayout());JComboBox<String> year=FinancialYear.selector(allowanceYear);JButton open=new JButton("Open Year");allowanceMonths=new JTabbedPane(JTabbedPane.TOP,JTabbedPane.WRAP_TAB_LAYOUT);allowanceMonths.addChangeListener(e->{loadAllowanceSelected();styleMonthLabels(allowanceMonths);});open.addActionListener(e->{allowanceYear=FinancialYear.parse((String)year.getSelectedItem());buildAllowanceTabs();});JPanel top=yearBar(year,open);panel.add(top,BorderLayout.NORTH);panel.add(allowanceMonths,BorderLayout.CENTER);buildAllowanceTabs();return panel;}
    private JComponent monthlyOther(){JPanel panel=new JPanel(new BorderLayout());JComboBox<String> year=FinancialYear.selector(otherYear);JButton open=new JButton("Open Year");otherMonths=new JTabbedPane(JTabbedPane.TOP,JTabbedPane.WRAP_TAB_LAYOUT);otherMonths.addChangeListener(e->{loadOtherSelected();styleMonthLabels(otherMonths);});open.addActionListener(e->{otherYear=FinancialYear.parse((String)year.getSelectedItem());buildOtherTabs();});panel.add(yearBar(year,open),BorderLayout.NORTH);panel.add(otherMonths,BorderLayout.CENTER);buildOtherTabs();return panel;}
    private JPanel yearBar(JComponent year,JButton open){JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));top.add(new JLabel("Financial Year:"));top.add(year);top.add(open);return top;}
    private void buildAllowanceTabs(){int selected=Math.max(0,allowanceMonths.getSelectedIndex());allowanceMonths.removeAll();for(int i=0;i<12;i++){YearMonth period=FinancialYear.month(allowanceYear,i);allowanceMonths.addTab(tab(period),new JPanel());setTab(allowanceMonths,i,period);}allowanceMonths.setSelectedIndex(Math.min(selected,11));styleMonthLabels(allowanceMonths);loadAllowanceSelected();}
    private void buildOtherTabs(){int selected=Math.max(0,otherMonths.getSelectedIndex());otherMonths.removeAll();for(int i=0;i<12;i++){YearMonth period=FinancialYear.month(otherYear,i);otherMonths.addTab(tab(period),new JPanel());setTab(otherMonths,i,period);}otherMonths.setSelectedIndex(Math.min(selected,11));styleMonthLabels(otherMonths);loadOtherSelected();}
    private void loadAllowanceSelected(){if(allowanceMonths==null||allowanceMonths.getSelectedIndex()<0)return;int index=allowanceMonths.getSelectedIndex();allowanceMonths.setComponentAt(index,allowanceSheet(FinancialYear.month(allowanceYear,index)));allowanceMonths.revalidate();allowanceMonths.repaint();}
    private void loadOtherSelected(){if(otherMonths==null||otherMonths.getSelectedIndex()<0)return;int index=otherMonths.getSelectedIndex();JComponent page=(JComponent)otherMonths.getComponentAt(index);if(page.getComponentCount()==0)otherMonths.setComponentAt(index,otherSheet(FinancialYear.month(otherYear,index)));}
    private String tab(YearMonth p){return p.getMonth().toString().substring(0,3);}private void setTab(JTabbedPane tabs,int index,YearMonth p){JLabel label=new JLabel(tab(p),SwingConstants.CENTER);label.setPreferredSize(new Dimension(80,30));label.setFont(new Font("SansSerif",Font.BOLD,15));label.setForeground(Color.WHITE);tabs.setTabComponentAt(index,label);}
    private void styleMonthLabels(JTabbedPane tabs){for(int i=0;i<tabs.getTabCount();i++)if(tabs.getTabComponentAt(i) instanceof JLabel label)label.setForeground(Color.WHITE);}
    private JComponent allowanceSheet(YearMonth period){String[] columns={"Employee ID","Employee Name","Basic Pay For Month","House Rent Allowance (HRA)","Attendance Bonus","Conveyance Allowance","Performance Pay","Medical Allowance","Special Allowance","Fixed Allowance","Total Allowances"};java.util.List<Employee> list=employees.listForMonth("",period);Object[][] rows=new Object[list.size()][11];for(int r=0;r<list.size();r++){Employee e=list.get(r);double hra=allowance("HRA",e,period),attendance=attendanceBonus(e,period),conveyance=allowance("Conveyance Allowance",e,period),performance=allowance("Performance Pay",e,period),medical=allowance("Medical Allowance",e,period),special=allowance("Special Allowance",e,period),fixed=allowance("Fixed Allowance",e,period);rows[r]=new Object[]{e.getId(),e.getName(),monthlyBasic(e,period),hra,attendance,conveyance,performance,medical,special,fixed,Money.round(hra+attendance+conveyance+performance+medical+special+fixed)};}TableSheet sheet=editableTable(rows,columns,1,period);JButton export=new JButton("Export Excel");export.addActionListener(e->{String[] h={"Employee ID","Employee Name","Basic Pay","HRA","Conveyance","Medical","Performance Pay","Special Allowance","Total Regular Gross"};java.util.List<Object[]> out=new ArrayList<>();for(int r=0;r<sheet.model.getRowCount();r++){double gross=n(sheet.model,r,2)+n(sheet.model,r,3)+n(sheet.model,r,5)+n(sheet.model,r,7)+n(sheet.model,r,6)+n(sheet.model,r,8);out.add(new Object[]{sheet.model.getValueAt(r,0),sheet.model.getValueAt(r,1),n(sheet.model,r,2),n(sheet.model,r,3),n(sheet.model,r,5),n(sheet.model,r,7),n(sheet.model,r,6),n(sheet.model,r,8),Money.round(gross)});}PayrollExcel.export(this,"CTC Allowances",period+"-Allowances.xlsx",h,out);});JPanel out=new JPanel(new BorderLayout());out.add(sheet.panel,BorderLayout.CENTER);JPanel south=new JPanel(new FlowLayout(FlowLayout.RIGHT));south.add(export);out.add(south,BorderLayout.SOUTH);return out;}
    private double allowance(String name,Employee e,YearMonth period){double basic=monthlyBasic(e,period),work=attendanceDAO.workingDays(period.toString()),payable=payableDays(e,period);if(basic<=0||work<=0||payable<=0||!CompanyPolicyStore.hasAllowance(name))return 0;double value=CompanyPolicyStore.allowance(name);return Money.round(CompanyPolicyStore.percentage(name)?value*basic/100:value*payable/period.lengthOfMonth());}
    private double payableDays(Employee e,YearMonth period){String month=period.toString();if(!attendanceDAO.hasSavedAttendance(e.getId(),month))return 0;double work=attendanceDAO.workingDays(month);if(work<=0)return 0;AttendanceRecord r=attendanceDAO.load(e.getId(),month);AttendanceSettings s=attendanceSettingsDAO.load();return Money.round(Math.max(0,work-r.absentDays-Math.max(0,r.paidLeaveDays-s.casualLeaveLimit)-Math.max(0,r.unpaidLeaveDays-s.earnedLeaveLimit)));}
    private double monthlyBasic(Employee e,YearMonth period){double workingDays=attendanceDAO.workingDays(period.toString());double payable=payableDays(e,period);return workingDays<=0||payable<=0?0:Money.round(SalaryRevisionStore.basicFor(e,period)*payable/workingDays);}
    private double attendanceBonus(Employee employee,YearMonth period){double work=attendanceDAO.workingDays(period.toString());double payable=payableDays(employee,period);return !employee.isWagesStructure()||work<=0||payable<work?0:PayrollRulesStore.attendanceBonus();}
    private JComponent otherSheet(YearMonth period){String[] columns={"Employee ID","Employee Name","OT Hours","OT Limit","OT Pay","Others","Total Other Earnings"};java.util.List<Employee> list=employees.listForMonth("",period);Object[][] rows=new Object[list.size()][7];for(int r=0;r<list.size();r++){Employee e=list.get(r);CTCStore.Value v=CTCStore.getOther(e.getId(),period.toString());double[] saved=otherDAO.load(e.getId(),period.toString());if(saved!=null)v.otHours=saved[0];v.otLimit=PayrollRulesStore.otLimit();v.otPay=otPay(e,period,v.otHours,v.otLimit);v.others=othersPay(e,period,v.otHours,v.otLimit);rows[r]=new Object[]{e.getId(),e.getName(),Money.round(v.otHours),Money.round(v.otLimit),Money.round(v.otPay),Money.round(v.others),Money.round(v.other())};}TableSheet sheet=editableTable(rows,columns,2,period);JButton save=new JButton("Save Other Earnings");save.addActionListener(e->saveOther(sheet.model,period));JPanel out=new JPanel(new BorderLayout());out.add(sheet.panel,BorderLayout.CENTER);JPanel bottom=new JPanel(new FlowLayout(FlowLayout.RIGHT));bottom.add(save);out.add(bottom,BorderLayout.SOUTH);return out;}
    private double otPay(Employee e,YearMonth period,double hours,double limit){double profileBasic=SalaryRevisionStore.basicFor(e,period),workingDays=attendanceDAO.workingDays(period.toString());if(!e.isWagesStructure()||profileBasic<=0||hours<=0||workingDays<=0)return 0;double effectiveOtRate=PayrollCalculator.effectiveOtRate(profileBasic,workingDays*PayrollRulesStore.workingHours());return Money.round(effectiveOtRate*Math.min(hours,limit));}
    private double othersPay(Employee e,YearMonth period,double hours,double limit){double profileBasic=SalaryRevisionStore.basicFor(e,period),workingDays=attendanceDAO.workingDays(period.toString());if(hours<limit||profileBasic<=0||workingDays<=0)return 0;double effectiveOtRate=PayrollCalculator.effectiveOtRate(profileBasic,workingDays*PayrollRulesStore.workingHours());return Money.round(effectiveOtRate*Math.max(0,hours-limit));}
    private TableSheet editableTable(Object[][] rows,String[] columns,int type,YearMonth period){DefaultTableModel model=new DefaultTableModel(rows,columns){public boolean isCellEditable(int row,int column){if(type==1)return column>=2&&column<10;return column==2;}};JTable table=new JTable(model);ExcelTableSupport.enableNumericMultiFill(table,false);table.setRowHeight(34);table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);for(int c=0;c<columns.length;c++){table.getColumnModel().getColumn(c).setPreferredWidth(c<2?180:(type==1?220:170));if(c>=2)table.getColumnModel().getColumn(c).setCellRenderer(Money.renderer());}DefaultCellEditor editor=new DefaultCellEditor(new JTextField()){public Component getTableCellEditorComponent(JTable t,Object v,boolean s,int r,int c){JTextField f=(JTextField)super.getTableCellEditorComponent(t,v,s,r,c);f.selectAll();return f;}};if(type==1)for(int c=2;c<10;c++)table.getColumnModel().getColumn(c).setCellEditor(editor);else table.getColumnModel().getColumn(2).setCellEditor(editor);final boolean[] updating={false};model.addTableModelListener(event->{if(event.getType()!=TableModelEvent.UPDATE||updating[0])return;int r=event.getFirstRow();CTCStore.Value v=type==1?CTCStore.get(String.valueOf(model.getValueAt(r,0))):CTCStore.getOther(String.valueOf(model.getValueAt(r,0)),period.toString());if(type==1){v.basic=n(model,r,2);v.hra=n(model,r,3);v.attendance=n(model,r,4);v.conveyance=n(model,r,5);v.performance=n(model,r,6);v.medical=n(model,r,7);v.special=n(model,r,8);v.fixed=n(model,r,9);updating[0]=true;model.setValueAt(Money.round(v.allowances()),r,10);updating[0]=false;CTCStore.flush();}else{v.otHours=n(model,r,2);v.otLimit=PayrollRulesStore.otLimit();java.util.List<Employee> found=employees.listByEmployeeId(String.valueOf(model.getValueAt(r,0)));v.otPay=found.isEmpty()?0:otPay(found.get(0),period,v.otHours,v.otLimit);v.others=found.isEmpty()?0:othersPay(found.get(0),period,v.otHours,v.otLimit);updating[0]=true;model.setValueAt(Money.round(v.otLimit),r,3);model.setValueAt(Money.round(v.otPay),r,4);model.setValueAt(Money.round(v.others),r,5);model.setValueAt(Money.round(v.other()),r,6);updating[0]=false;}AutoSaveService.markDirty();});model.fireTableDataChanged();JPanel panel=new JPanel(new BorderLayout());panel.add(EmployeeIdSearch.create(table,model),BorderLayout.NORTH);panel.add(new JScrollPane(table),BorderLayout.CENTER);return new TableSheet(panel,model);}
    private static class TableSheet{final JPanel panel;final DefaultTableModel model;TableSheet(JPanel panel,DefaultTableModel model){this.panel=panel;this.model=model;}}
    private double n(DefaultTableModel model,int row,int column){try{return Money.round(Double.parseDouble(String.valueOf(model.getValueAt(row,column))));}catch(Exception e){return 0;}}
    private void saveOther(DefaultTableModel model,YearMonth period){try{for(int row=0;row<model.getRowCount();row++){String id=String.valueOf(model.getValueAt(row,0));otherDAO.save(id,period.toString(),n(model,row,2),n(model,row,5));}model.fireTableDataChanged();loadOtherSelected();JOptionPane.showMessageDialog(this,"Other Earnings saved for "+period.getMonth()+" "+period.getYear()+".");}catch(Exception e){JOptionPane.showMessageDialog(this,"Could not save Other Earnings: "+e.getMessage());}}
    private JComponent salaryRevision(){String[] cols={"EID","EName","Basic Salary","Revised Salary","Effective From"};java.util.List<Employee> list=employees.listActive("");Object[][] rows=new Object[list.size()][5];for(int i=0;i<list.size();i++){Employee e=list.get(i);rows[i]=new Object[]{e.getId(),e.getName(),Money.round(e.getBasicSalary()),0.00,""};}final boolean[] editing={false};final Object[][][] snapshot={copyRows(rows)};DefaultTableModel model=new DefaultTableModel(rows,cols){public boolean isCellEditable(int r,int c){return editing[0]&&(c==3||c==4);}};JTable table=new JTable(model);table.setRowHeight(32);table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);for(int i=0;i<cols.length;i++)table.getColumnModel().getColumn(i).setPreferredWidth(i<2?180:220);JComboBox<String> choices=new JComboBox<>();choices.addItem("");for(int y=2000;y<=2050;y++)for(int m=1;m<=12;m++)choices.addItem(YearMonth.of(y,m).toString());table.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(choices));JButton editCancel=new JButton("Edit"),apply=new JButton("Save CTC");apply.setEnabled(false);editCancel.addActionListener(e->{if(!editing[0]){snapshot[0]=copyModel(model);editing[0]=true;editCancel.setText("Cancel");apply.setEnabled(true);}else{model.setDataVector(snapshot[0],cols);editing[0]=false;editCancel.setText("Edit");apply.setEnabled(false);}table.repaint();});apply.addActionListener(x->{try{int saved=0;for(int r=0;r<model.getRowCount();r++){double revised=Double.parseDouble(String.valueOf(model.getValueAt(r,3)));String selected=String.valueOf(model.getValueAt(r,4)).trim();if(revised==0&&selected.isEmpty())continue;if(revised<=0||selected.isEmpty())throw new IllegalArgumentException();java.util.List<Employee> found=employees.listByEmployeeId(String.valueOf(model.getValueAt(r,0)));if(!found.isEmpty()){SalaryRevisionStore.save(found.get(0),revised,YearMonth.parse(selected));saved++;}}PayrollEvents.attendanceSaved();snapshot[0]=copyModel(model);editing[0]=false;editCancel.setText("Edit");apply.setEnabled(false);JOptionPane.showMessageDialog(this,saved==0?"No salary revisions were entered.":saved+" salary revision(s) saved.");}catch(Exception ex){JOptionPane.showMessageDialog(this,"Enter a revised salary greater than 0 and select an Effective From month for each revision.");}});JPanel out=new JPanel(new BorderLayout());JPanel north=new JPanel(new BorderLayout());north.add(new JLabel("Revised Salary starts at 0.00 and remains inactive until you enter an amount and select an effective Month-Year."),BorderLayout.NORTH);north.add(EmployeeIdSearch.create(table,model),BorderLayout.SOUTH);out.add(north,BorderLayout.NORTH);out.add(new JScrollPane(table),BorderLayout.CENTER);JPanel south=new JPanel(new FlowLayout(FlowLayout.RIGHT));south.add(editCancel);south.add(apply);out.add(south,BorderLayout.SOUTH);return out;}
}
