import java.io.Serializable;import java.sql.*;import java.util.*;
/** Shared CTC values persisted in payroll.db. */
public final class CTCStore {
 public static class Value implements Serializable {private static final long serialVersionUID=1L;public double basic,hra,attendance,conveyance,performance,medical,special,fixed,otHours,otherHours,otLimit,otPay,others,arrears,annualBonus,employerEpf,employerEsic,healthInsurance,gratuity,employeeEpf,pt,esic,incomeTax,annualGrossSalary,hraOverridePercent;public boolean hraOverride,attendanceOverride,conveyanceOverride,performanceOverride,medicalOverride,specialOverride,fixedOverride;public double allowances(){return hra+attendance+conveyance+performance+medical+special+fixed;}public double totalAnnualGrossSalary(){return annualGrossSalary>0?annualGrossSalary:Money.round(basic+allowances()+arrears+annualBonus);}public double other(){return otPay+others;}}
 private static final Map<String,Value> data=new HashMap<>();private static final Map<String,Value> monthlyOther=new HashMap<>();
 public static synchronized Value get(String id){return data.computeIfAbsent(id,CTCStore::load);}
 public static synchronized Value getOther(String id,String month){return monthlyOther.computeIfAbsent(id+"|"+month,k->{Value v=new Value();double[] saved=new CTCOtherEarningsDAO().load(id,month);if(saved!=null){v.otHours=saved[0];v.others=saved[1];}return v;});}
 public static synchronized void flush(){try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO ctc(employee_id,employee_name,basic,hra,attendance_bonus,conveyance_allowance,performance_pay,medical_allowance,special_allowance,fixed_allowance,arrears,annual_bonus,employer_provident_fund,esic_employer_share,health_insurance,gratuity,total_annual_ctc,total_gross_salary,employee_provident_fund,pt,esic,income_tax_tds,net_pay) SELECT ?,employee_name,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM employee_master_data WHERE employee_id=? AND is_deleted=0 ON CONFLICT(employee_id) DO UPDATE SET basic=excluded.basic,hra=excluded.hra,attendance_bonus=excluded.attendance_bonus,conveyance_allowance=excluded.conveyance_allowance,performance_pay=excluded.performance_pay,medical_allowance=excluded.medical_allowance,special_allowance=excluded.special_allowance,fixed_allowance=excluded.fixed_allowance,arrears=excluded.arrears,annual_bonus=excluded.annual_bonus,employer_provident_fund=excluded.employer_provident_fund,esic_employer_share=excluded.esic_employer_share,health_insurance=excluded.health_insurance,gratuity=excluded.gratuity,total_annual_ctc=excluded.total_annual_ctc,total_gross_salary=excluded.total_gross_salary,employee_provident_fund=excluded.employee_provident_fund,pt=excluded.pt,esic=excluded.esic,income_tax_tds=excluded.income_tax_tds,net_pay=excluded.net_pay")){for(Map.Entry<String,Value> e:data.entrySet()){Value v=e.getValue();int i=1;p.setString(i++,e.getKey());for(double n:new double[]{v.basic,v.hra,v.attendance,v.conveyance,v.performance,v.medical,v.special,v.fixed,v.arrears,v.annualBonus,v.employerEpf,v.employerEsic,v.healthInsurance,v.gratuity,v.totalAnnualGrossSalary()+v.employerEpf+v.employerEsic+v.healthInsurance+v.gratuity,v.totalAnnualGrossSalary(),v.employeeEpf,v.pt,v.esic,v.incomeTax,v.totalAnnualGrossSalary()-v.employeeEpf-v.pt-v.esic-v.incomeTax})p.setDouble(i++,Money.round(n));p.setString(i,e.getKey());p.addBatch();}p.executeBatch();}c.commit();}catch(Exception ignored){}}
 public static synchronized void purgeEmployee(String id){data.remove(id);monthlyOther.keySet().removeIf(key->key.startsWith(id+"|"));}
 private static Value load(String id){Value v=new Value();Connection c=DBConnection.getConnection();if(c==null)return v;try(PreparedStatement p=c.prepareStatement("SELECT basic,hra,attendance_bonus,conveyance_allowance,performance_pay,medical_allowance,special_allowance,fixed_allowance,arrears,annual_bonus,employer_provident_fund,esic_employer_share,health_insurance,gratuity,employee_provident_fund,pt,esic,income_tax_tds FROM ctc WHERE employee_id=?")){p.setString(1,id);ResultSet r=p.executeQuery();if(r.next()){double[] a=new double[18];for(int i=0;i<a.length;i++)a[i]=r.getDouble(i+1);v.basic=a[0];v.hra=a[1];v.attendance=a[2];v.conveyance=a[3];v.performance=a[4];v.medical=a[5];v.special=a[6];v.fixed=a[7];v.arrears=a[8];v.annualBonus=a[9];v.employerEpf=a[10];v.employerEsic=a[11];v.healthInsurance=a[12];v.gratuity=a[13];v.employeeEpf=a[14];v.pt=a[15];v.esic=a[16];v.incomeTax=a[17];synchronizeOverrides(v);}}catch(SQLException ignored){}return v;}
 private static void synchronizeOverrides(Value v){double basic=v.basic;v.hraOverride=!same(v.hra,allowance("HRA",basic));v.hraOverridePercent=basic<=0?0:Money.round(v.hra*100.0/basic);v.attendanceOverride=!same(v.attendance,allowance("Attendance Bonus",basic));v.conveyanceOverride=v.performanceOverride=v.medicalOverride=v.specialOverride=v.fixedOverride=false;}
 private static double allowance(String name,double basic){if(!CompanyPolicyStore.hasAllowance(name))return 0;double value=CompanyPolicyStore.allowance(name);return Money.round(CompanyPolicyStore.percentage(name)?basic*value/100:value*12);}
 private static boolean same(double left,double right){return Math.abs(left-right)<.005;}
 private CTCStore(){}
}
