import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.*;
import java.awt.*;
import java.io.File;
import java.util.List;

public class DashboardPanel extends JPanel {
    private final EmployeeDAO employees=new EmployeeDAO();
    private final JLabel total=new JLabel("0"), active=new JLabel("0");
    private final DefaultTableModel model=new DefaultTableModel(new String[]{"Timestamp","Module","Action Performed","Performed By","IP / Session ID","Status"},0){public boolean isCellEditable(int r,int c){return false;}};
    private final JTable table=createTable(); private final JTextField search=new JTextField(20); private final JComboBox<String> range=new JComboBox<>(new String[]{"All Time","Today","Last 7 Days","Last 30 Days"});
    public DashboardPanel(PayrollSystemFrame frame) {
        super(new BorderLayout(8,8)); setBorder(UIStyleUtility.compactModuleBorder()); setDoubleBuffered(true);
        JPanel cards=new JPanel(new GridLayout(1,2,14,0)); cards.add(card("👥  Total Employees",total,"Registered in system",new Color(52,92,145))); cards.add(card("●  Active Employees",active,"Currently active",new Color(46,125,50))); add(cards,BorderLayout.NORTH);
        add(logs(),BorderLayout.CENTER);
        addComponentListener(new java.awt.event.ComponentAdapter(){public void componentShown(java.awt.event.ComponentEvent e){SwingUtilities.invokeLater(DashboardPanel.this::refresh);}});
    }
    private JTable createTable(){JTable value=new JTable(model);TabStyle.configureTable(value);return value;}
    private JPanel card(String heading,JLabel value,String note,Color accent) { JPanel p=new JPanel(); p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS)); p.setBackground(Color.WHITE); p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(230,230,230),1,true),BorderFactory.createEmptyBorder(16,18,16,18))); JLabel h=new JLabel(heading); h.setForeground(accent); h.setFont(new Font("SansSerif",Font.BOLD,15)); value.setFont(new Font("SansSerif",Font.BOLD,30)); value.setBorder(BorderFactory.createEmptyBorder(8,0,3,0)); JLabel sub=new JLabel(note); sub.setForeground(new Color(110,110,110)); p.add(h);p.add(value);p.add(sub);return p; }
    private JComponent logs() { JPanel p=new JPanel(new BorderLayout(8,8)); p.setBorder(BorderFactory.createTitledBorder("Security & System Activity Log")); JPanel filters=new JPanel(new FlowLayout(FlowLayout.LEFT,8,2)); filters.add(new JLabel("Search User / Keyword:"));filters.add(search);filters.add(new JLabel("Period:"));filters.add(range); JButton download=new JButton("Download Activity Log (.CSV)");download.addActionListener(e->export());filters.add(download);p.add(filters,BorderLayout.NORTH);table.setRowHeight(28);table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);table.setShowGrid(true);table.setShowHorizontalLines(true);table.setShowVerticalLines(true);table.setGridColor(new Color(180,180,180));table.getColumnModel().getColumn(5).setCellRenderer(new StatusRenderer());p.add(new JScrollPane(table),BorderLayout.CENTER);DocumentListener l=new DocumentListener(){public void insertUpdate(DocumentEvent e){reload();}public void removeUpdate(DocumentEvent e){reload();}public void changedUpdate(DocumentEvent e){reload();}};search.getDocument().addDocumentListener(l);range.addActionListener(e->reload());return p; }
    public void refresh() { List<Employee> all=employees.list(""); List<Employee> activeList=employees.listActive(""); total.setText(String.valueOf(all.size()));active.setText(String.valueOf(activeList.size())); reload(); }
    private void reload() { if(model==null)return; model.setRowCount(0); for(ActivityLogger.Entry e:ActivityLogger.find(search.getText(),String.valueOf(range.getSelectedItem()))) model.addRow(new Object[]{e.timestamp.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),e.module,e.action,e.user,e.session,e.status}); autoFitLogColumns(); }
    private void autoFitLogColumns() { FontMetrics metrics=table.getFontMetrics(table.getFont()); for(int col=0;col<table.getColumnCount();col++){int width=metrics.stringWidth(table.getColumnName(col))+28;for(int row=0;row<table.getRowCount();row++)width=Math.max(width,metrics.stringWidth(String.valueOf(table.getValueAt(row,col)))+28);table.getColumnModel().getColumn(col).setPreferredWidth(width);} }
    private void export() { JFileChooser chooser=new JFileChooser();chooser.setSelectedFile(new File("activity-log.csv"));if(chooser.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;try{ActivityLogger.exportCsv(chooser.getSelectedFile(),ActivityLogger.find(search.getText(),String.valueOf(range.getSelectedItem())));ActivityLogger.log("Dashboard","EXPORT AUDIT LOGS",chooser.getSelectedFile().getName(),"SUCCESS");reload();}catch(Exception ex){JOptionPane.showMessageDialog(this,"Could not export activity log: "+ex.getMessage());} }
    private static class StatusRenderer extends DefaultTableCellRenderer { public Component getTableCellRendererComponent(JTable t,Object v,boolean sel,boolean focus,int row,int col){JLabel l=(JLabel)super.getTableCellRendererComponent(t,v,sel,focus,row,col);String s=String.valueOf(v).toUpperCase(java.util.Locale.ROOT);l.setHorizontalAlignment(CENTER);l.setOpaque(true);if(s.contains("FAILED")||s.contains("LOGIN FAILED")||s.contains("SECURITY WARNING")){l.setBackground(new Color(0xF8,0xD7,0xDA));l.setForeground(new Color(0x84,0x20,0x29));}else if(s.equals("SUCCESS")||s.equals("LOGIN")||s.equals("APPLICATION START")){l.setBackground(new Color(0xD1,0xE7,0xDD));l.setForeground(new Color(0x0F,0x51,0x32));}else{l.setBackground(Color.WHITE);l.setForeground(Color.BLACK);}l.setFont(l.getFont().deriveFont(Font.BOLD,12f));return l;} }
}
