import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public final class DatabaseInitializer {
    public static void initialize(){
        ensureSQLiteTables();
        new EmployeeDAO();new AttendanceDAO();
        PayrollRulesStore.all();TaxSlabStore.list();
        DatabaseMigrations.apply();
    }
    public static void rebuildFromScratch(){try(Connection connection=DBConnection.getConnection();Statement statement=connection==null?null:connection.createStatement()){if(statement==null)return;List<String> tables=new ArrayList<>();try(ResultSet result=statement.executeQuery("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")){while(result.next())tables.add(result.getString(1));}statement.execute("PRAGMA foreign_keys = OFF");for(String table:tables)if(!"employees".equalsIgnoreCase(table)&&!"employee_master_data".equalsIgnoreCase(table))statement.executeUpdate("DROP TABLE IF EXISTS \""+table.replace("\"","\"\"")+"\"");statement.execute("PRAGMA foreign_keys = ON");}catch(Exception ignored){}initialize();}
    /** Creates a complete, empty schema for a first-time packaged installation. */
    private static void ensureSQLiteTables(){try(Connection connection=DBConnection.getConnection();Statement statement=connection==null?null:connection.createStatement()){
        if(statement==null)return;
        String[] schema={
            "CREATE TABLE IF NOT EXISTS employee_master_data(employee_id TEXT PRIMARY KEY,employee_name TEXT NOT NULL,gender TEXT,dob TEXT,department TEXT,designation TEXT,joining_date TEXT,leaving_date TEXT,status TEXT NOT NULL,salary_structure TEXT,pan TEXT,pan_doc_path TEXT,aadhaar TEXT,aadhaar_doc_path TEXT,esic TEXT,uan TEXT,bank_name TEXT,bank_acc TEXT,ifsc TEXT,email TEXT,phone TEXT,photo_path TEXT,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,epf_ceiling INTEGER NOT NULL DEFAULT 0,phone_ciphertext TEXT,pan_ciphertext TEXT,aadhaar_ciphertext TEXT)",
            "CREATE TABLE IF NOT EXISTS employees(id TEXT PRIMARY KEY,name TEXT,gender TEXT,dob TEXT,department TEXT,designation TEXT,joining_date TEXT,status TEXT,leaving_date TEXT,email TEXT,phone TEXT,pan TEXT,aadhaar TEXT,esic TEXT,uan TEXT,bank_name TEXT,bank_acc TEXT,ifsc TEXT,salary_structure TEXT,photo_path TEXT,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS attendance(employee_id TEXT,employee_name TEXT NOT NULL,month TEXT NOT NULL,fy TEXT NOT NULL,total_working_days REAL NOT NULL DEFAULT 0,absent_days REAL NOT NULL DEFAULT 0,cl REAL NOT NULL DEFAULT 0,el REAL NOT NULL DEFAULT 0,days_payable REAL NOT NULL DEFAULT 0,ot_hours REAL NOT NULL DEFAULT 0,other REAL NOT NULL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,PRIMARY KEY(employee_id,month,fy),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS ctc(employee_id TEXT PRIMARY KEY,employee_name TEXT NOT NULL,basic REAL DEFAULT 0,hra REAL DEFAULT 0,attendance_bonus REAL DEFAULT 0,conveyance_allowance REAL DEFAULT 0,performance_pay REAL DEFAULT 0,medical_allowance REAL DEFAULT 0,special_allowance REAL DEFAULT 0,fixed_allowance REAL DEFAULT 0,arrears REAL DEFAULT 0,annual_bonus REAL DEFAULT 0,employer_provident_fund REAL DEFAULT 0,esic_employer_share REAL DEFAULT 0,health_insurance REAL DEFAULT 0,gratuity REAL DEFAULT 0,total_annual_ctc REAL DEFAULT 0,total_gross_salary REAL DEFAULT 0,employee_provident_fund REAL DEFAULT 0,pt REAL DEFAULT 0,esic REAL DEFAULT 0,income_tax_tds REAL DEFAULT 0,net_pay REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS earnings_allowances(employee_id TEXT,employee_name TEXT NOT NULL,month TEXT NOT NULL,fy TEXT NOT NULL,hra REAL DEFAULT 0,attendance_bonus REAL DEFAULT 0,conveyance REAL DEFAULT 0,perofmance REAL DEFAULT 0,medical REAL DEFAULT 0,special REAL DEFAULT 0,fixed REAL DEFAULT 0,total_allowances REAL DEFAULT 0,ot_pay REAL DEFAULT 0,other_earnings REAL DEFAULT 0,total_other_earnings REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,PRIMARY KEY(employee_id,month,fy),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS deductions(employee_id TEXT,employee_name TEXT NOT NULL,month TEXT NOT NULL,fy TEXT NOT NULL,esic REAL DEFAULT 0,epf REAL DEFAULT 0,pt REAL DEFAULT 0,income_tax_tds REAL DEFAULT 0,salary_advance REAL DEFAULT 0,total_deductions REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,PRIMARY KEY(employee_id,month,fy),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS salary(employee_id TEXT,employee_name TEXT NOT NULL,month TEXT NOT NULL,fy TEXT NOT NULL,basic_pay REAL DEFAULT 0,total_allowances REAL DEFAULT 0,total_other_earnings REAL DEFAULT 0,gross_salary REAL DEFAULT 0,total_deductions REAL DEFAULT 0,net_salary REAL DEFAULT 0,payment_status TEXT DEFAULT 'Pending',is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,PRIMARY KEY(employee_id,month,fy),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS payslip(employee_id TEXT,employee_name TEXT NOT NULL,month TEXT NOT NULL,fy TEXT NOT NULL,basic_profile_ctc REAL DEFAULT 0,basic_for_month REAL DEFAULT 0,total_allowances REAL DEFAULT 0,total_other_earnings REAL DEFAULT 0,gross_salary REAL DEFAULT 0,total_deductions REAL DEFAULT 0,net_salary REAL DEFAULT 0,generated_date TEXT,pdf_path TEXT,preview_text TEXT,performance_pay REAL DEFAULT 0,manual_other_earnings REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,PRIMARY KEY(employee_id,month,fy),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS it_computation(computation_id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT NOT NULL,employee_name TEXT NOT NULL,month TEXT NOT NULL,financial_year TEXT NOT NULL,tax_regime TEXT,actual_amount REAL DEFAULT 0,projected_amount REAL DEFAULT 0,total_amount REAL DEFAULT 0,gross_salary REAL DEFAULT 0,less_exemption_u_s_10 REAL DEFAULT 0,net_salary REAL DEFAULT 0,less_deduction_u_s_16 REAL DEFAULT 0,standard_deduction REAL DEFAULT 0,tax_on_employment REAL DEFAULT 0,net_taxable_salary REAL DEFAULT 0,less_relief_u_s_87a REAL DEFAULT 0,tax_payable REAL DEFAULT 0,add_surcharge REAL DEFAULT 0,add_cess REAL DEFAULT 0,total_tax_payable REAL DEFAULT 0,total_tax_payable_rounded REAL DEFAULT 0,tax_recovered_till_previous_month REAL DEFAULT 0,tax_deducted_current_month REAL DEFAULT 0,total_tax_deducted REAL DEFAULT 0,balance_tax_payable_remaining_months REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT,FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)",
            "CREATE TABLE IF NOT EXISTS payroll_users(username TEXT PRIMARY KEY,password_hash TEXT NOT NULL,role_name TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS application_security(setting_id INTEGER PRIMARY KEY,password_hash TEXT NOT NULL)",
            "CREATE TABLE IF NOT EXISTS activity_log(log_id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp TEXT NOT NULL,module TEXT NOT NULL,action_performed TEXT NOT NULL,performed_by TEXT,ip_session_id TEXT,status TEXT)",
            "CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,user_name TEXT,action_name TEXT,employee_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)",
            "CREATE TABLE IF NOT EXISTS ctc_other_earnings(employee_id TEXT,month_key TEXT,ot_hours REAL,others REAL,PRIMARY KEY(employee_id,month_key))",
            "CREATE TABLE IF NOT EXISTS generated_payslips(employee_id TEXT,payroll_month TEXT,employee_name TEXT,pdf_path TEXT,preview_text TEXT,generated_date TEXT,net_salary REAL DEFAULT 0,performance_pay REAL DEFAULT 0,PRIMARY KEY(employee_id,payroll_month))",
            "CREATE TABLE IF NOT EXISTS monthly_attendance(employee_id TEXT,month_key TEXT,working_days REAL,weekly_off_days INTEGER,public_holidays INTEGER,present_days INTEGER,absent_days REAL,half_days REAL,paid_leave_days REAL,unpaid_leave_days REAL,overtime_hours REAL,late_arrivals INTEGER,early_departures INTEGER,days_payable REAL DEFAULT 0,other_hours REAL DEFAULT 0,PRIMARY KEY(employee_id,month_key))",
            "CREATE TABLE IF NOT EXISTS monthly_working_days(month_key TEXT PRIMARY KEY,working_days REAL NOT NULL)",
            "CREATE TABLE IF NOT EXISTS payroll_rules(rule_key TEXT PRIMARY KEY,rule_value REAL)",
            "CREATE TABLE IF NOT EXISTS payroll_settings(component_name TEXT PRIMARY KEY,enabled INTEGER,amount REAL,is_percentage INTEGER)",
            "CREATE TABLE IF NOT EXISTS payroll_tax_slabs(slab_order INTEGER PRIMARY KEY,slab_name TEXT,from_amount REAL,to_amount REAL,tax_rate REAL)",
            "CREATE TABLE IF NOT EXISTS settings_company_details(id INTEGER PRIMARY KEY AUTOINCREMENT,company_name TEXT NOT NULL,company_address TEXT,company_pan TEXT,company_tan TEXT,employee_id_prefix TEXT,company_logo_path TEXT,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_allowance_defaults(id INTEGER PRIMARY KEY AUTOINCREMENT,allowance_name TEXT NOT NULL UNIQUE,calculation_type TEXT,default_value REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_ot_earnings(id INTEGER PRIMARY KEY AUTOINCREMENT,ot_rate_multiplier REAL DEFAULT 1.0,max_ot_limit_hours REAL DEFAULT 0,max_total_extra_hours REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_attendance_leave_rules(id INTEGER PRIMARY KEY AUTOINCREMENT,rule_name TEXT NOT NULL UNIQUE,rule_value TEXT,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_deduction_rules(id INTEGER PRIMARY KEY AUTOINCREMENT,epf_employee_type TEXT,epf_employee_value REAL DEFAULT 0,epf_employer_type TEXT,epf_employer_value REAL DEFAULT 0,restrict_epf_statutory INTEGER DEFAULT 1,pt_calculation_type TEXT,esic_wage_threshold REAL DEFAULT 0,esic_employee_rate REAL DEFAULT 0,esic_employer_rate REAL DEFAULT 0,standard_deduction REAL DEFAULT 0,section_87a_limit REAL DEFAULT 0,health_education_cess_rate REAL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_tax_slabs(slab_id INTEGER PRIMARY KEY AUTOINCREMENT,slab_name TEXT,from_amount REAL DEFAULT 0,to_amount REAL DEFAULT 0,tax_rate REAL DEFAULT 0,slab_type TEXT DEFAULT 'TAX',is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_revised_salary(id INTEGER PRIMARY KEY AUTOINCREMENT,revision_rule TEXT,increment_value REAL DEFAULT 0,employee_id TEXT,original_basic REAL DEFAULT 0,revised_basic REAL DEFAULT 0,effective_month TEXT,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS settings_passwords(id INTEGER PRIMARY KEY AUTOINCREMENT,account_type TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,is_deleted INTEGER NOT NULL DEFAULT 0,deleted_at TEXT)",
            "CREATE TABLE IF NOT EXISTS attendance_settings(id INTEGER PRIMARY KEY,weekly_off_days INTEGER,public_holidays INTEGER,overtime_rate REAL,bonus_enabled INTEGER,bonus_threshold REAL,bonus_amount REAL,bonus_percent REAL,bonus_is_percent INTEGER,late_grace_minutes INTEGER,half_day_half INTEGER,casual_leave_limit INTEGER DEFAULT 0,earned_leave_limit INTEGER DEFAULT 0)",
            "CREATE TABLE IF NOT EXISTS leave_year_ledger(employee_id TEXT NOT NULL,financial_year TEXT NOT NULL,leave_type TEXT NOT NULL,opening_balance REAL NOT NULL DEFAULT 0,used_balance REAL NOT NULL DEFAULT 0,remaining_balance REAL NOT NULL DEFAULT 0,carried_forward REAL NOT NULL DEFAULT 0,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(employee_id,financial_year,leave_type),FOREIGN KEY(employee_id) REFERENCES employee_master_data(employee_id) ON DELETE CASCADE)"
        };
        for(String ddl:schema)statement.executeUpdate(ddl);
        for(String table:new String[]{"employee_master_data","attendance","ctc","earnings_allowances","deductions","salary","payslip","it_computation","settings_company_details","settings_allowance_defaults","settings_ot_earnings","settings_attendance_leave_rules","settings_deduction_rules","settings_tax_slabs","settings_revised_salary","settings_passwords"}){try{statement.executeUpdate("ALTER TABLE "+table+" ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}try{statement.executeUpdate("ALTER TABLE "+table+" ADD COLUMN deleted_at TEXT");}catch(Exception ignored){}}
    }catch(Exception ignored){}}
    private DatabaseInitializer() { }
}
