import javax.swing.*;import javax.swing.border.*;import javax.swing.event.*;import javax.swing.table.*;import java.awt.*;import java.time.*;

/** Financial-year deduction register with statutory ESIC and EPF reporting views. */
public class DeductionsPanel extends JPanel {
 private final EmployeeDAO employees=new EmployeeDAO();private final JTabbedPane months=new JTabbedPane();private final JPanel current=new JPanel(new BorderLayout());private int financialYear=FinancialYear.currentStart();private long loadGeneration;
 private static final String[] DEDUCTION_COLUMNS={"Employee ID","Employee Name","ESIC","EPF","PT","Income Tax / TDS","Salary Advance","Total Deductions"};
 public DeductionsPanel(){setLayout(new BorderLayout());JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));JComboBox<String> fy=FinancialYear.selector(financialYear);JButton open=new JButton("Open Year");open.addActionListener(e->{financialYear=FinancialYear.parse((String)fy.getSelectedItem());buildMonths();});top.add(new JLabel("Financial Year:"));top.add(fy);top.add(open);add(top,BorderLayout.NORTH);
     // This tabbed pane is used only as a month selector; reserve no space for
     // its otherwise-empty content area and keep APR through MAR in one strip.
     months.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);months.setPreferredSize(new Dimension(0,48));months.setMinimumSize(new Dimension(0,48));months.setMaximumSize(new Dimension(Integer.MAX_VALUE,48));months.setBorder(BorderFactory.createEmptyBorder(2,2,2,2));
     JPanel center=new JPanel(new BorderLayout());center.add(months,BorderLayout.NORTH);center.add(current,BorderLayout.CENTER);add(center,BorderLayout.CENTER);months.addChangeListener(e->{styleMonthLabels();loadView();});buildMonths();}
 public void refresh(){buildMonths();}
 private void buildMonths(){int selected=Math.max(0,months.getSelectedIndex());months.removeAll();for(int i=0;i<12;i++){YearMonth p=FinancialYear.month(financialYear,i);JPanel blank=new JPanel();blank.setOpaque(false);blank.setPreferredSize(new Dimension(0,0));months.addTab(FinancialYear.shortName(p),blank);JLabel tab=new JLabel(FinancialYear.shortName(p),SwingConstants.CENTER);tab.setOpaque(false);tab.setPreferredSize(new Dimension(80,34));tab.setFont(new Font("SansSerif",Font.BOLD,15));tab.setForeground(Color.WHITE);months.setTabComponentAt(i,tab);}months.setSelectedIndex(Math.min(selected,11));loadView();revalidate();repaint();}
 private YearMonth period(){return FinancialYear.month(financialYear,Math.max(0,months.getSelectedIndex()));}
 private void styleMonthLabels(){for(int i=0;i<months.getTabCount();i++)if(months.getTabComponentAt(i) instanceof JLabel label)label.setForeground(Color.WHITE);}
 private void loadView(){if(months.getSelectedIndex()<0)return;YearMonth requested=period();long generation=++loadGeneration;current.removeAll();current.add(new JLabel("Loading deductions…",SwingConstants.CENTER),BorderLayout.CENTER);current.revalidate();current.repaint();ApplicationTasks.execute(()->{java.util.List<Row> rows=rows(requested);SwingUtilities.invokeLater(()->{if(generation!=loadGeneration||!requested.equals(period()))return;current.removeAll();current.add(overall(requested,rows),BorderLayout.CENTER);current.revalidate();current.repaint();});});}
 private java.util.List<Row> rows(YearMonth p){java.util.List<Row> out=new java.util.ArrayList<>();AttendanceDAO attendance=new AttendanceDAO();AttendanceSettings settings=new AttendanceSettingsDAO().load();for(Employee e:employees.listForMonth("",p)){AttendanceRecord a=attendance.load(e.getId(),p.toString());double work=attendance.workingDays(p.toString());if(work<=0)work=a.workingDays;if(work<=0)work=p.lengthOfMonth();double days=attendance.hasSavedAttendance(e.getId(),p.toString())?LeaveBalanceService.payableDays(e,p,work,a.absentDays,a.paidLeaveDays,a.unpaidLeaveDays,settings):work;double ratio=Math.min(1,days/work),basic=Money.round(SalaryRevisionStore.basicFor(e,p)*ratio),wages=monthlyGross(e,p,basic,ratio,a);DeductionStore.Value expected=CtcDeductionCalculator.forMonth(e,p,ratio);DeductionStore.Value d=DeductionStore.get(e.getId(),p.toString());if(!DeductionStore.hasSaved(e.getId(),p.toString())||zero(d)){d.epf=expected.epf;d.esic=expected.esic;d.pt=expected.pt;d.tds=expected.tds;}out.add(new Row(e,days,wages,d,expected));}return out;}
 private double monthlyGross(Employee e,YearMonth p,double basic,double ratio,AttendanceRecord attendance){MonthlyEarningsStore.Value saved=MonthlyEarningsStore.get(e.getId(),p.toString());double hra=value(saved==null?0:saved.hra,"HRA",basic,40),bonus=value(saved==null?0:saved.attendance,"Attendance Bonus",basic,PayrollRulesStore.attendanceBonus()),conveyance=value(saved==null?0:saved.conveyance,"Conveyance Allowance",basic,PayrollRulesStore.conveyance()),performance=value(saved==null?0:saved.performance,"Performance Pay",basic,0),medical=value(saved==null?0:saved.medical,"Medical Allowance",basic,PayrollRulesStore.medical()),special=value(saved==null?0:saved.special,"Special Allowance",basic,15),fixed=value(saved==null?0:saved.fixed,"Fixed Allowance",basic,0);CTCStore.Value other=CTCStore.getOther(e.getId(),p.toString());double overtime=saved!=null&&saved.overtime!=0?saved.overtime:Money.round(PayrollCalculator.effectiveOtRate(basic,Math.max(1,attendance.workingDays)*PayrollRulesStore.workingHours())*Math.max(0,attendance.overtimeHours)),others=saved!=null&&saved.reimbursements!=0?saved.reimbursements:other.others;return Money.round(basic+hra+bonus+conveyance+performance+medical+special+fixed+overtime+others);}
 private double value(double saved,String name,double basic,double fallback){if(saved!=0)return saved;double configured=CompanyPolicyStore.allowance(name);boolean percentage=CompanyPolicyStore.percentage(name);if(configured<=0){configured=fallback;percentage="HRA".equals(name)||"Special Allowance".equals(name);}return Money.round(percentage?basic*configured/100:configured);}
 private static boolean zero(DeductionStore.Value value){return value.esic==0&&value.epf==0&&value.pt==0&&value.tds==0&&value.advance==0;}
private JComponent overall(YearMonth p,java.util.List<Row> list){
    Object[][] data=new Object[list.size()][DEDUCTION_COLUMNS.length],expected=new Object[list.size()][DEDUCTION_COLUMNS.length];
    for(int i=0;i<list.size();i++){Row r=list.get(i);data[i]=new Object[]{r.e.getId(),r.e.getName(),r.d.esic,r.d.epf,r.d.pt,r.d.tds,r.d.advance,r.d.total()};expected[i]=new Object[]{r.e.getId(),r.e.getName(),r.expected.esic,r.expected.epf,r.expected.pt,r.expected.tds,r.d.advance,0.0};}
    final boolean[] editing={false},restoring={false};final Object[][][] snapshot={copyRows(data)};DefaultTableModel model=new DefaultTableModel(data,DEDUCTION_COLUMNS){public boolean isCellEditable(int r,int c){return editing[0]&&c>=2&&c<=6&&c!=5;}};
    JTable table=table(model,2);for(int c=2;c<=6;c++)table.getColumnModel().getColumn(c).setCellEditor(numberEditor());for(int c=2;c<=5;c++)table.getColumnModel().getColumn(c).setCellRenderer(overrideRenderer(expected,c));
    JLabel warning=new JLabel("Warning: Value is not as per global settings.");warning.setForeground(new Color(190,70,70));warning.setVisible(hasOverrides(model,expected));final boolean[] updating={false};model.addTableModelListener(e->{if(e.getType()!=TableModelEvent.UPDATE||restoring[0]||updating[0]||!editing[0])return;int r=e.getFirstRow();String employeeId=String.valueOf(model.getValueAt(r,0));double tds=TDSCalculator.calculateMonthlyTDS(employeeId),total=Money.round(n(model,r,2)+n(model,r,3)+n(model,r,4)+tds+n(model,r,6));updating[0]=true;model.setValueAt(tds,r,5);model.setValueAt(total,r,7);updating[0]=false;warning.setVisible(hasOverrides(model,expected));table.repaint();});
    JComponent base=wrap(table,model);JButton editCancel=new JButton("Edit"),save=new JButton("Save"),export=new JButton("Export to Excel"), imported=new JButton("Import Excel");save.setEnabled(false);editCancel.addActionListener(e->{if(!editing[0]){snapshot[0]=copyModel(model);editing[0]=true;editCancel.setText("Cancel");save.setEnabled(true);}else{restoring[0]=true;UIStyleUtility.restoreTableValues(model,snapshot[0]);restoring[0]=false;editing[0]=false;editCancel.setText("Edit");save.setEnabled(false);}warning.setVisible(hasOverrides(model,expected));table.repaint();});save.addActionListener(e->{persistDeductions(model,p);DeductionStore.flush();AutoSaveService.markDirty();PayrollEvents.attendanceSaved();snapshot[0]=copyModel(model);editing[0]=false;editCancel.setText("Edit");save.setEnabled(false);warning.setVisible(hasOverrides(model,expected));JOptionPane.showMessageDialog(this,"Deductions saved.");});export.addActionListener(e->exportExcel(model,p));imported.addActionListener(e->importExcel(model,p));JPanel panel=(JPanel)base;JPanel top=(JPanel)panel.getComponent(0);Component[] filters=top.getComponents();top.removeAll();top.setLayout(new BorderLayout());JPanel searchRow=new JPanel(new FlowLayout(FlowLayout.LEFT));for(Component filter:filters)searchRow.add(filter);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT));actions.add(imported);actions.add(export);top.add(searchRow,BorderLayout.WEST);top.add(actions,BorderLayout.EAST);JPanel bottom=new JPanel(new BorderLayout());bottom.add(warning,BorderLayout.WEST);JPanel saveActions=new JPanel(new FlowLayout(FlowLayout.RIGHT));saveActions.add(editCancel);saveActions.add(save);bottom.add(saveActions,BorderLayout.EAST);panel.add(bottom,BorderLayout.SOUTH);return base;
}
 private static final String[] IMPORT_HEADERS={"Employee ID","Month","Year","Professional Tax","Income Tax / TDS","Other Deductions","Total Deductions"};
 private void persistDeductions(DefaultTableModel model,YearMonth period){for(int row=0;row<model.getRowCount();row++){DeductionStore.Value value=DeductionStore.get(String.valueOf(model.getValueAt(row,0)),period.toString());value.esic=n(model,row,2);value.epf=n(model,row,3);value.pt=n(model,row,4);value.tds=n(model,row,5);value.advance=n(model,row,6);}}
 private static Object[][] copyRows(Object[][] source){Object[][] copy=new Object[source.length][];for(int row=0;row<source.length;row++)copy[row]=java.util.Arrays.copyOf(source[row],source[row].length);return copy;}private static Object[][] copyModel(DefaultTableModel model){Object[][] copy=new Object[model.getRowCount()][model.getColumnCount()];for(int row=0;row<copy.length;row++)for(int column=0;column<copy[row].length;column++)copy[row][column]=model.getValueAt(row,column);return copy;}
 private void exportExcel(DefaultTableModel m,YearMonth p){java.util.List<Object[]> rows=new java.util.ArrayList<>();for(int r=0;r<m.getRowCount();r++)rows.add(new Object[]{m.getValueAt(r,0),p.getMonth(),p.getYear(),m.getValueAt(r,4),m.getValueAt(r,5),m.getValueAt(r,6),m.getValueAt(r,7)});PayrollExcel.export(this,"Deductions",p+"-Deductions.xlsx",IMPORT_HEADERS,rows);}
 private void importExcel(DefaultTableModel m,YearMonth p){try{PayrollExcel.Sheet s=PayrollExcel.importSheet(this);if(s==null)return;PayrollExcel.requireHeaders(s,IMPORT_HEADERS);int count=0;for(int i=1;i<s.rows.size();i++){java.util.List<String> v=s.rows.get(i);String id=PayrollExcel.cell(v,0);for(int r=0;r<m.getRowCount();r++)if(id.equals(String.valueOf(m.getValueAt(r,0)))){m.setValueAt(PayrollExcel.number(PayrollExcel.cell(v,3)),r,4);m.setValueAt(PayrollExcel.number(PayrollExcel.cell(v,4)),r,5);m.setValueAt(PayrollExcel.number(PayrollExcel.cell(v,5)),r,6);count++;break;}}DeductionStore.flush();JOptionPane.showMessageDialog(this,count+" deductions imported.");}catch(Exception ex){JOptionPane.showMessageDialog(this,ex.getMessage());}}
 private JComponent esic(YearMonth p){String[] cols={"Employee ID","IP Number","IP Name","Days Payable","Total Monthly Wages","ESIC Contribution"};java.util.List<Row> list=rows(p);Object[][] data=new Object[list.size()][6];for(int i=0;i<list.size();i++){Row r=list.get(i);data[i]=new Object[]{r.e.getId(),r.e.getEsicIpNumber(),r.e.getName(),r.days,r.wages,r.d.esic};}return wrap(table(new DefaultTableModel(data,cols){public boolean isCellEditable(int r,int c){return false;}},4),null);}
 private JComponent epf(YearMonth p){String[] cols={"Employee ID","UAN","Member Name","Gross Wage","EPF Wage","EPS Wage","EDLI Wage","EPF Contri Remitted (Col H)","EPS Contri Remitted (Col I)","EPF EPS Diff Remitted (Col J)"};java.util.List<Row> list=rows(p);Object[][] data=new Object[list.size()][10];for(int i=0;i<list.size();i++){Row r=list.get(i);double h=Money.round(r.d.epf),rate=PayrollRulesStore.epfRate(),cap=PayrollRulesStore.epfWageCap(),epfWage=rate<=0?0:(Math.abs(h-cap*rate/100)<.01?cap:Math.round(h*100/rate)),eps=Math.min(epfWage,cap),iValue=Math.round(eps*PayrollRulesStore.epsRate()/100),diff=Money.round(h-iValue);data[i]=new Object[]{r.e.getId(),epfUan(r.e),r.e.getName(),r.wages,epfWage,eps,eps,h,iValue,diff};}return wrap(table(new DefaultTableModel(data,cols){public boolean isCellEditable(int r,int c){return false;}},3),null);}
 private String epfUan(Employee employee){String uan=employee==null?"":employee.getUanNumber();return uan!=null&&uan.matches("\\d{12}")?uan:"";}
 private JTable table(DefaultTableModel model,int monetaryFrom){
  JTable table=new JTable(model);
  configureCellSelection(table);ExcelTableSupport.enableNumericMultiFill(table,false);UIStyleUtility.applyProfessionalTableStyle(table);
  for(int c=0;c<model.getColumnCount();c++){
   TableColumn column=table.getColumnModel().getColumn(c);
   if(c==0)column.setPreferredWidth(180);
   else if(c==1)column.setPreferredWidth(240);
   else column.setPreferredWidth(120);
   if(c>=monetaryFrom)column.setCellRenderer(Money.renderer());
  }
  int totalDeductions=model.findColumn("Total Deductions");
  if(totalDeductions>=0)table.getColumnModel().getColumn(totalDeductions).setCellRenderer(totalDeductionsRenderer());
  table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
  return table;
 }
 private TableCellRenderer totalDeductionsRenderer(){return new DefaultTableCellRenderer(){public Component getTableCellRendererComponent(JTable table,Object value,boolean selected,boolean focused,int row,int column){super.getTableCellRendererComponent(table,value instanceof Number?Money.text(((Number)value).doubleValue()):value,selected,focused,row,column);setHorizontalAlignment(SwingConstants.RIGHT);setFont(new Font("SansSerif",Font.BOLD,16));setForeground(Color.BLACK);setBackground(selected?table.getSelectionBackground():new Color(220,235,252));setBorder(new CompoundBorder(new MatteBorder(0,0,1,1,UIStyleUtility.GRID),BorderFactory.createEmptyBorder(0,8,0,12)));return this;}};}
 private TableCellRenderer overrideRenderer(Object[][] expected,int column){return new DefaultTableCellRenderer(){public Component getTableCellRendererComponent(JTable table,Object value,boolean selected,boolean focused,int row,int viewColumn){super.getTableCellRendererComponent(table,value instanceof Number?Money.text(((Number)value).doubleValue()):value,selected,focused,row,viewColumn);int modelRow=table.convertRowIndexToModel(row);setHorizontalAlignment(SwingConstants.RIGHT);setOpaque(true);setBackground(selected?table.getSelectionBackground():!same(value,expected[modelRow][column])?new Color(255,230,230):Color.WHITE);setBorder(new CompoundBorder(new MatteBorder(0,0,1,1,UIStyleUtility.GRID),BorderFactory.createEmptyBorder(0,8,0,12)));return this;}};}
 private boolean hasOverrides(DefaultTableModel model,Object[][] expected){for(int row=0;row<model.getRowCount();row++)for(int column=2;column<=5;column++)if(!same(model.getValueAt(row,column),expected[row][column]))return true;return false;}
 private boolean same(Object left,Object right){try{return Math.abs(Double.parseDouble(String.valueOf(left))-Double.parseDouble(String.valueOf(right)))<.005;}catch(Exception ignored){return String.valueOf(left).equals(String.valueOf(right));}}
 private void configureCellSelection(JTable table){TabStyle.configureTable(table);}
 private JComponent wrap(JTable table,DefaultTableModel model){if(model==null)model=(DefaultTableModel)table.getModel();JTextField search=new JTextField(20);TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<>(model);table.setRowSorter(sorter);search.getDocument().addDocumentListener(new DocumentListener(){private void filter(){String q=search.getText().trim();sorter.setRowFilter(q.isEmpty()?null:RowFilter.regexFilter("(?i)"+java.util.regex.Pattern.quote(q),0,1));}public void insertUpdate(DocumentEvent e){filter();}public void removeUpdate(DocumentEvent e){filter();}public void changedUpdate(DocumentEvent e){filter();}});JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));top.add(new JLabel("Search Employee ID / Name:"));top.add(search);JPanel out=new JPanel(new BorderLayout());out.setBorder(BorderFactory.createEmptyBorder());out.add(top,BorderLayout.NORTH);JScrollPane scroll=UIStyleUtility.frozenEmployeeColumns(table);scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);scroll.getHorizontalScrollBar().setUnitIncrement(24);out.add(scroll,BorderLayout.CENTER);return out;}
 private DefaultCellEditor numberEditor(){return new DefaultCellEditor(new JTextField()){public Component getTableCellEditorComponent(JTable t,Object v,boolean s,int r,int c){JTextField f=(JTextField)super.getTableCellEditorComponent(t,v,s,r,c);f.selectAll();return f;}};}
 private double n(DefaultTableModel m,int r,int c){try{return Money.round(Double.parseDouble(String.valueOf(m.getValueAt(r,c))));}catch(Exception e){return 0;}}
 private static final class Row{final Employee e;final double days;final double wages;final DeductionStore.Value d,expected;Row(Employee e,double days,double wages,DeductionStore.Value d,DeductionStore.Value expected){this.e=e;this.days=days;this.wages=wages;this.d=d;this.expected=expected;}}
}
