import java.io.Serializable;import java.sql.*;import java.time.YearMonth;import java.util.*;
/** Deduction values persisted in payroll.db. */
public final class DeductionStore {
 public static class Value implements Serializable {private static final long serialVersionUID=1L;public double esic,epf,pt,tds,advance;public double total(){return esic+epf+pt+tds+advance;}}
 private static final Map<String,Value> data=new HashMap<>();
 public static synchronized Value get(String id){return data.computeIfAbsent(id,k->new Value());}
 public static synchronized Value get(String id,String month){String key=id+"|"+month;if(data.containsKey(key))return data.get(key);Value v=load(id,month);if(v==null)v=new Value();data.put(key,v);return v;}
 public static boolean hasSaved(String id,String month){try{YearMonth m=YearMonth.parse(month);try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT 1 FROM deductions WHERE employee_id=? AND month=? AND fy=? AND is_deleted=0")){if(p==null)return false;p.setString(1,id);p.setString(2,m.getMonth().toString().substring(0,3));p.setString(3,FinancialYear.text(m.getMonthValue()>=4?m.getYear():m.getYear()-1));return p.executeQuery().next();}}catch(Exception ignored){return false;}}
 public static synchronized void flush(){try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO deductions(employee_id,employee_name,month,fy,esic,epf,pt,income_tax_tds,salary_advance,total_deductions) SELECT ?,employee_name,?,?,?,?,?,?,?,? FROM employee_master_data WHERE employee_id=? AND is_deleted=0 ON CONFLICT(employee_id,month,fy) DO UPDATE SET esic=excluded.esic,epf=excluded.epf,pt=excluded.pt,income_tax_tds=excluded.income_tax_tds,salary_advance=excluded.salary_advance,total_deductions=excluded.total_deductions")){for(Map.Entry<String,Value> e:data.entrySet()){int x=e.getKey().indexOf('|');if(x<1)continue;YearMonth m=YearMonth.parse(e.getKey().substring(x+1));Value v=e.getValue();int i=1;p.setString(i++,e.getKey().substring(0,x));p.setString(i++,m.getMonth().toString().substring(0,3));p.setString(i++,FinancialYear.text(m.getMonthValue()>=4?m.getYear():m.getYear()-1));for(double n:new double[]{v.esic,v.epf,v.pt,v.tds,v.advance,v.total()})p.setDouble(i++,Money.round(n));p.setString(i,e.getKey().substring(0,x));p.addBatch();}p.executeBatch();}c.commit();}catch(Exception ignored){}}
 public static synchronized void purgeEmployee(String id){data.keySet().removeIf(key->key.equals(id)||key.startsWith(id+"|"));}
 private static Value load(String id,String month){try{YearMonth m=YearMonth.parse(month);Connection c=DBConnection.getConnection();if(c==null)return null;try(PreparedStatement p=c.prepareStatement("SELECT esic,epf,pt,income_tax_tds,salary_advance FROM deductions WHERE employee_id=? AND month=? AND fy=?")){p.setString(1,id);p.setString(2,m.getMonth().toString().substring(0,3));p.setString(3,FinancialYear.text(m.getMonthValue()>=4?m.getYear():m.getYear()-1));ResultSet r=p.executeQuery();if(!r.next())return null;Value v=new Value();v.esic=r.getDouble(1);v.epf=r.getDouble(2);v.pt=r.getDouble(3);v.tds=r.getDouble(4);v.advance=r.getDouble(5);return v;}}catch(Exception ignored){return null;}}
 private DeductionStore(){}
}
