import javax.swing.*;
import java.awt.*;

/** Compact support-directed recovery screen; no code is entered by the client. */
public final class ForgotCredentialsFrame extends JFrame {
    private final JLabel status=new JLabel(" ",SwingConstants.CENTER);
    public ForgotCredentialsFrame(){super(Branding.APPLICATION_NAME+" - Credential Recovery");Branding.applyWindowIcon(this);setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);JPanel panel=new JPanel(new GridBagLayout());panel.setBorder(BorderFactory.createEmptyBorder(26,42,26,42));GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(7,8,7,8);g.fill=GridBagConstraints.HORIZONTAL;g.gridx=0;g.gridy=0;g.gridwidth=2;JLabel title=new JLabel("Forgot Username or Password?",SwingConstants.CENTER);title.setFont(title.getFont().deriveFont(Font.BOLD,22f));panel.add(title,g);g.gridy++;panel.add(new JLabel("Share this Support ID with YASL Support.",SwingConstants.CENTER),g);g.gridy++;JLabel supportId=new JLabel(LicenseService.supportId(),SwingConstants.CENTER);supportId.setFont(supportId.getFont().deriveFont(Font.BOLD,18f));panel.add(supportId,g);g.gridy++;JButton copy=new JButton("Copy ID");copy.addActionListener(e->Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new java.awt.datatransfer.StringSelection(LicenseService.supportId()),null));panel.add(copy,g);g.gridy++;JButton check=new JButton("Check for Credential Reset");check.addActionListener(e->check());panel.add(check,g);g.gridy++;JButton back=new JButton("Back to Login");back.addActionListener(e->dispose());panel.add(back,g);g.gridy++;JLabel safe=new JLabel("Your payroll data will remain safe.",SwingConstants.CENTER);safe.setForeground(new Color(80,80,80));panel.add(safe,g);g.gridy++;status.setForeground(Color.RED);status.setPreferredSize(new Dimension(500,24));panel.add(status,g);add(panel);pack();setMinimumSize(new Dimension(610,390));setResizable(false);setLocationRelativeTo(null);}
    private void check(){CredentialRecoveryService.Result result=CredentialRecoveryService.checkForReset();status.setText(result.message());if(result.recovered()){JOptionPane.showMessageDialog(this,result.message());dispose();}}
}
