import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/** Searchable FAQ and support details view; content is maintained in HelpContent. */
public final class HelpPanel extends JPanel {
    private final JTabbedPane tabs=new JTabbedPane();
    private final JPanel faqList=new JPanel();
    private final JScrollPane faqScroll=new JScrollPane(faqList);
    public HelpPanel(){super(new BorderLayout());tabs.addTab("FAQs",faqs());tabs.addTab("Contact Details",contactDetails());tabs.addTab("Database",new DatabaseViewerPanel());tabs.addChangeListener(e->{if(tabs.getSelectedIndex()==0)resetFaqScroll();});addComponentListener(new ComponentAdapter(){@Override public void componentShown(ComponentEvent e){resetFaqScroll();}});add(tabs,BorderLayout.CENTER);}
    private JComponent faqs(){JPanel root=new JPanel(new BorderLayout(0,8));root.setBorder(UIStyleUtility.compactModuleBorder());JPanel searchRow=new JPanel(new BorderLayout(8,0));searchRow.add(new JLabel("Search FAQs:"),BorderLayout.WEST);JTextField search=new JTextField();search.setToolTipText("Search questions and answers");searchRow.add(search,BorderLayout.CENTER);root.add(searchRow,BorderLayout.NORTH);faqList.setLayout(new BoxLayout(faqList,BoxLayout.Y_AXIS));root.add(faqScroll,BorderLayout.CENTER);JPanel footer=new JPanel();footer.setLayout(new BoxLayout(footer,BoxLayout.Y_AXIS));JLabel refreshHint=new JLabel("If the required value is not shown, refresh the current module or switch to another tab.");refreshHint.setAlignmentX(Component.LEFT_ALIGNMENT);footer.add(refreshHint);JLabel contact=contactLink();contact.setAlignmentX(Component.LEFT_ALIGNMENT);footer.add(contact);root.add(footer,BorderLayout.SOUTH);search.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){filter(search.getText());}public void removeUpdate(DocumentEvent e){filter(search.getText());}public void changedUpdate(DocumentEvent e){filter(search.getText());}});filter("");return root;}
    private void resetFaqScroll(){SwingUtilities.invokeLater(()->faqScroll.getVerticalScrollBar().setValue(0));}
    private void filter(String text){String query=text==null?"":text.trim().toLowerCase();faqList.removeAll();int matches=0;for(String[] faq:HelpContent.FAQS)if(query.isEmpty()||(faq[0]+" "+faq[1]).toLowerCase().contains(query)){faqList.add(faqCard(faq));faqList.add(Box.createVerticalStrut(8));matches++;}if(matches==0){JLabel none=new JLabel("No matching FAQ was found. Please contact the company.");none.setBorder(BorderFactory.createEmptyBorder(12,4,12,4));faqList.add(none);faqList.add(contactLink());}faqList.revalidate();faqList.repaint();resetFaqScroll();}
    private JComponent faqCard(String[] faq){JPanel card=new JPanel(new BorderLayout());card.setAlignmentX(Component.LEFT_ALIGNMENT);card.setMaximumSize(new Dimension(Integer.MAX_VALUE,160));card.setBorder(BorderFactory.createLineBorder(new Color(190,205,218)));JLabel question=new JLabel(faq[0]);question.setOpaque(true);question.setBackground(new Color(220,232,244));question.setForeground(new Color(26,46,64));question.setFont(question.getFont().deriveFont(Font.BOLD));question.setBorder(BorderFactory.createEmptyBorder(8,12,8,12));card.add(question,BorderLayout.NORTH);JTextArea answer=new JTextArea(faq[1]);answer.setEditable(false);answer.setLineWrap(true);answer.setWrapStyleWord(true);answer.setOpaque(false);answer.setBorder(BorderFactory.createEmptyBorder(8,12,10,12));card.add(answer,BorderLayout.CENTER);return card;}
    private JLabel contactLink(){JLabel link=new JLabel("<html><a href='contact'>Please contact the company.</a></html>");link.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));link.setToolTipText("Open Contact Details");link.addMouseListener(new MouseAdapter(){@Override public void mouseClicked(MouseEvent e){tabs.setSelectedIndex(1);}});return link;}
    private JComponent contactDetails(){JPanel panel=new JPanel(new GridBagLayout());panel.setBorder(UIStyleUtility.compactModuleBorder());GridBagConstraints c=new GridBagConstraints();c.insets=new Insets(10,8,10,8);c.anchor=GridBagConstraints.NORTHWEST;c.gridx=0;c.gridy=0;c.gridwidth=2;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;panel.add(new JLabel(Branding.logoIcon(440,228),SwingConstants.CENTER),c);c.gridwidth=1;c.gridy++;c.weightx=0;c.fill=GridBagConstraints.NONE;panel.add(staticText("COMPANY NAME:"),c);c.gridx=1;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;panel.add(infoBox("YASHASVI ACCOUNTING SOLUTIONS LLP"),c);c.gridx=0;c.gridy++;c.weightx=0;c.fill=GridBagConstraints.NONE;panel.add(staticText("COMPANY ADDRESS:"),c);c.gridx=1;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;panel.add(infoBox("<html>1530/2, GROUND FLOOR, YASHASWI, 6TH CROSS,<br>4TH BLOCK, DODDABOMASANDRA,<br>VIDYARANYAPURA POST, BENGALURU - 560097</html>"),c);c.gridx=0;c.gridy++;c.weightx=0;c.fill=GridBagConstraints.NONE;panel.add(staticText("EMAIL:"),c);c.gridx=1;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;panel.add(infoBox("connect@yasl.co.in"),c);c.gridx=0;c.gridy++;c.gridwidth=2;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;JLabel note=staticText("Our support team will respond within 24 hours.");note.setHorizontalAlignment(SwingConstants.CENTER);note.setForeground(new Color(80,80,80));panel.add(note,c);c.gridy++;c.weighty=1;panel.add(Box.createVerticalGlue(),c);return new JScrollPane(panel);}
    private JComponent infoBox(String text){JPanel box=new JPanel(new BorderLayout());box.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(190,205,218)),BorderFactory.createEmptyBorder(8,10,8,10)));box.setBackground(Color.WHITE);JLabel value=staticText(text);box.add(value,BorderLayout.CENTER);return box;}
    private JLabel staticText(String value){JLabel label=new JLabel(value);label.setFocusable(false);return label;}
}
