import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;

/** One-time account creation shown after licensing and before normal login. */
public final class InitialAdminSetupFrame extends JFrame {
    private final JTextField username=new JTextField(18);
    private final JPasswordField password=new JPasswordField(18),confirm=new JPasswordField(18),master=new JPasswordField(18),masterConfirm=new JPasswordField(18);
    private final JLabel message=new JLabel(" ",SwingConstants.CENTER);
    public InitialAdminSetupFrame(){super(Branding.APPLICATION_NAME+" - Create Account");Branding.applyWindowIcon(this);setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);addWindowListener(new WindowAdapter(){@Override public void windowClosing(WindowEvent e){Main.applicationClosing();}@Override public void windowGainedFocus(WindowEvent e){Main.revalidateLicenseWhenFocused();}});JPanel form=new JPanel(new GridBagLayout());form.setBorder(BorderFactory.createEmptyBorder(28,52,28,52));GridBagConstraints c=new GridBagConstraints();c.insets=new Insets(7,9,7,9);c.fill=GridBagConstraints.HORIZONTAL;c.gridx=0;c.gridy=0;c.gridwidth=2;JLabel title=new JLabel("Create Account",SwingConstants.CENTER);title.setFont(title.getFont().deriveFont(Font.BOLD,24f));form.add(title,c);c.gridy++;JLabel note=new JLabel("Create your login and Master Data credentials. You will sign in on the next screen.",SwingConstants.CENTER);form.add(note,c);c.gridwidth=1;c.gridy++;c.gridx=0;form.add(new JLabel("Username"),c);c.gridx=1;form.add(username,c);c.gridx=0;c.gridy++;form.add(new JLabel("Login Password"),c);c.gridx=1;form.add(password,c);c.gridx=0;c.gridy++;form.add(new JLabel("Confirm Login Password"),c);c.gridx=1;form.add(confirm,c);c.gridx=0;c.gridy++;form.add(new JLabel("Master Data Password"),c);c.gridx=1;form.add(master,c);c.gridx=0;c.gridy++;form.add(new JLabel("Confirm Master Data Password"),c);c.gridx=1;form.add(masterConfirm,c);c.gridx=0;c.gridy++;c.gridwidth=2;message.setForeground(Color.RED);form.add(message,c);c.gridy++;JButton create=new JButton("Create Account");create.addActionListener(e->createAccount());form.add(create,c);getRootPane().setDefaultButton(create);add(form);pack();setSize(new Dimension(760,520));setLocationRelativeTo(null);}
    private void createAccount(){char[] login=password.getPassword(),loginConfirm=confirm.getPassword(),md=master.getPassword(),mdConfirm=masterConfirm.getPassword();try{if(!UserAuthentication.isUsernameCompliant(username.getText())){message.setText("Username must contain at least 4 characters.");return;}if(!UserAuthentication.isPasswordCompliant(login)){message.setText("Login password must contain 8 to 16 characters.");return;}if(!Arrays.equals(login,loginConfirm)){message.setText("Login passwords do not match.");return;}if(!SecurityService.isMasterPasswordCompliant(md)){message.setText("Master Data password must be exactly 6 characters.");return;}if(!Arrays.equals(md,mdConfirm)){message.setText("Master Data passwords do not match.");return;}if(!UserAuthentication.createInitialCredentials(username.getText(),login,md)){message.setText("Could not create the account. It may already exist.");return;}login=null;md=null;dispose();Main.openLogin();}finally{if(login!=null)Arrays.fill(login,'\0');Arrays.fill(loginConfirm,'\0');if(md!=null)Arrays.fill(md,'\0');Arrays.fill(mdConfirm,'\0');}}
}
