import java.sql.*;import java.time.*;
/** Rebuilds annual leave balances from immutable employee-month attendance rows; replacing a row cannot duplicate usage. */
public final class LeaveLedgerService {
 public record Balance(double opening,double used,double remaining,double carried){}
 private LeaveLedgerService(){}
 public static Balance balance(Employee e,YearMonth through,boolean cl,AttendanceSettings s){int start=through.getMonthValue()<4?through.getYear()-1:through.getYear();String fy=start+"-"+(start+1);double carried=priorCarry(e.getId(),start,cl);double opening=Math.max(0,(cl?s.casualLeaveLimit:s.earnedLeaveLimit))+carried,used=0;AttendanceDAO dao=new AttendanceDAO();for(YearMonth m:FinancialYear.months(start)){if(m.isAfter(through))break;if(!eligible(e,m)||!dao.hasSavedAttendance(e.getId(),m.toString()))continue;AttendanceRecord r=dao.load(e.getId(),m.toString());used+=Math.max(0,cl?r.paidLeaveDays:r.unpaidLeaveDays);}double remaining=Math.max(0,opening-used),carry=Math.min(remaining,Math.max(0,cl?s.maximumClCarryForward:s.maximumElCarryForward));persist(e.getId(),fy,cl,opening,used,remaining,carry);return new Balance(opening,used,remaining,carry);}
 public static double payableDays(Employee e,YearMonth m,double working,double absent,double clUsed,double elUsed,AttendanceSettings s){Balance cl=balance(e,m,true,s),el=balance(e,m,false,s);double clBefore=Math.max(0,cl.used()-Math.max(0,clUsed)),elBefore=Math.max(0,el.used()-Math.max(0,elUsed));double clExcess=Math.max(0,clUsed-Math.max(0,cl.opening()-clBefore)),elExcess=Math.max(0,elUsed-Math.max(0,el.opening()-elBefore));return Math.max(0,working-Math.max(0,absent)-clExcess-elExcess);}
 private static boolean eligible(Employee e,YearMonth m){try{LocalDate d=m.atDay(1),end=m.atEndOfMonth();LocalDate join=LocalDate.parse(e.getJoiningDate(),java.time.format.DateTimeFormatter.ofPattern("dd-MM-uuuu"));if(join.isAfter(end))return false;String leaving=e.getEmploymentEndDate();return leaving==null||leaving.isBlank()||!LocalDate.parse(leaving,java.time.format.DateTimeFormatter.ofPattern("dd-MM-uuuu")).isBefore(d);}catch(Exception x){return true;}}
 private static double priorCarry(String id,int start,boolean cl){try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT carried_forward FROM leave_year_ledger WHERE employee_id=? AND financial_year=? AND leave_type=?")){if(p==null)return 0;p.setString(1,id);p.setString(2,(start-1)+"-"+start);p.setString(3,cl?"CL":"EL");ResultSet r=p.executeQuery();return r.next()?r.getDouble(1):0;}catch(Exception x){return 0;}}
 private static void persist(String id,String fy,boolean cl,double opening,double used,double remaining,double carried){try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("INSERT INTO leave_year_ledger(employee_id,financial_year,leave_type,opening_balance,used_balance,remaining_balance,carried_forward,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(employee_id,financial_year,leave_type) DO UPDATE SET opening_balance=excluded.opening_balance,used_balance=excluded.used_balance,remaining_balance=excluded.remaining_balance,carried_forward=excluded.carried_forward,updated_at=CURRENT_TIMESTAMP")){if(p==null)return;p.setString(1,id);p.setString(2,fy);p.setString(3,cl?"CL":"EL");p.setDouble(4,opening);p.setDouble(5,used);p.setDouble(6,remaining);p.setDouble(7,carried);p.executeUpdate();}catch(Exception ignored){}}
}
