import java.io.Serializable;
import java.sql.*;
import java.time.YearMonth;
import java.util.*;

/** Employee-specific editable earnings overrides used by every monthly payroll consumer. */
public final class MonthlyEarningsStore {
    public static final class Value implements Serializable { private static final long serialVersionUID = 1L; public double basic, hra, conveyance, attendance, performance, medical, special, fixed, arrears, overtime, exGratia, bonus, rewards, reimbursements; }
    private static final Map<String, Value> DATA = new HashMap<>();
    public static synchronized Value get(String employeeId, String month) { String key=employeeId+"|"+month; if(DATA.containsKey(key))return DATA.get(key); Value v=load(employeeId,month); if(v!=null)DATA.put(key,v); return v; }
    public static synchronized Value getOrCreate(String employeeId, String month) { return DATA.computeIfAbsent(employeeId + "|" + month, k -> new Value()); }
    public static synchronized void save() { try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO earnings_allowances(employee_id,employee_name,month,fy,hra,attendance_bonus,conveyance,perofmance,medical,special,fixed,total_allowances,ot_pay,other_earnings,total_other_earnings) SELECT ?,employee_name,?,?,?,?,?,?,?,?,?,?,?,?,? FROM employee_master_data WHERE employee_id=? AND is_deleted=0 ON CONFLICT(employee_id,month,fy) DO UPDATE SET hra=excluded.hra,attendance_bonus=excluded.attendance_bonus,conveyance=excluded.conveyance,perofmance=excluded.perofmance,medical=excluded.medical,special=excluded.special,fixed=excluded.fixed,total_allowances=excluded.total_allowances,ot_pay=excluded.ot_pay,other_earnings=excluded.other_earnings,total_other_earnings=excluded.total_other_earnings")){for(Map.Entry<String,Value> e:DATA.entrySet()){int split=e.getKey().indexOf('|');if(split<1)continue;String id=e.getKey().substring(0,split),monthKey=e.getKey().substring(split+1);YearMonth period=YearMonth.parse(monthKey);Value v=e.getValue();int i=1;p.setString(i++,id);p.setString(i++,period.getMonth().toString().substring(0,3));p.setString(i++,FinancialYear.text(period.getMonthValue()>=4?period.getYear():period.getYear()-1));double total=Money.round(v.hra+v.attendance+v.conveyance+v.performance+v.medical+v.special+v.fixed),other=Money.round(v.overtime+v.reimbursements);for(double n:new double[]{v.hra,v.attendance,v.conveyance,v.performance,v.medical,v.special,v.fixed,total,v.overtime,v.reimbursements,other})p.setDouble(i++,Money.round(n));p.setString(i,id);p.addBatch();}p.executeBatch();}c.commit();}catch(Exception ignored){ } }
    public static synchronized void purgeEmployee(String employeeId) { DATA.keySet().removeIf(key -> key.startsWith(employeeId + "|")); }
    private static Value load(String employeeId,String monthKey){try{YearMonth p=YearMonth.parse(monthKey);Connection c=DBConnection.getConnection();if(c==null)return null;try(PreparedStatement s=c.prepareStatement("SELECT hra,attendance_bonus,conveyance,perofmance,medical,special,fixed,ot_pay,other_earnings FROM earnings_allowances WHERE employee_id=? AND month=? AND fy=?")){s.setString(1,employeeId);s.setString(2,p.getMonth().toString().substring(0,3));s.setString(3,FinancialYear.text(p.getMonthValue()>=4?p.getYear():p.getYear()-1));ResultSet r=s.executeQuery();if(!r.next())return null;Value v=new Value();v.hra=r.getDouble(1);v.attendance=r.getDouble(2);v.conveyance=r.getDouble(3);v.performance=r.getDouble(4);v.medical=r.getDouble(5);v.special=r.getDouble(6);v.fixed=r.getDouble(7);v.overtime=r.getDouble(8);v.reimbursements=r.getDouble(9);return v;}}catch(Exception ignored){return null;}}
    private MonthlyEarningsStore() { }
}
