import java.sql.*;import java.util.*;import java.util.prefs.Preferences;

/** Central, persistent constants for the payroll formula engine. Database-backed when available. */
public final class PayrollRulesStore {
 private static final Preferences P=Preferences.userNodeForPackage(PayrollRulesStore.class);private static final Map<String,Double> DEFAULTS=new LinkedHashMap<>();
 static{DEFAULTS.put("workingHours",8.0);DEFAULTS.put("hraPercent",43.0358964153337);DEFAULTS.put("attendanceBonus",1200.0);DEFAULTS.put("conveyance",2030.0);DEFAULTS.put("medical",2030.0);DEFAULTS.put("specialBase",25126.0);DEFAULTS.put("otLimit",30.0);DEFAULTS.put("otMultiplier",2.0);DEFAULTS.put("esicCeiling",21000.0);DEFAULTS.put("esicRate",0.75);DEFAULTS.put("esicEmployerRate",3.25);DEFAULTS.put("standardDeduction",75000.0);DEFAULTS.put("rebate87aLimit",700000.0);DEFAULTS.put("cessRate",4.0);DEFAULTS.put("epfWageCap",15000.0);DEFAULTS.put("epfRate",12.0);DEFAULTS.put("epsRate",8.33);DEFAULTS.put("ptThreshold",25000.0);DEFAULTS.put("ptAmount",200.0);ensureTable();loadDatabase();}
 private static void ensureTable(){}
 private static void loadDatabase(){try(Connection c=DBConnection.getConnection();Statement s=c==null?null:c.createStatement()){if(s==null)return;try(ResultSet r=s.executeQuery("SELECT esic_wage_threshold,esic_employee_rate,esic_employer_rate,standard_deduction,section_87a_limit,health_education_cess_rate,epf_employee_value FROM settings_deduction_rules ORDER BY id LIMIT 1")){if(r.next()){P.putDouble("rule.esicCeiling",r.getDouble(1));P.putDouble("rule.esicRate",r.getDouble(2));P.putDouble("rule.esicEmployerRate",r.getDouble(3));P.putDouble("rule.standardDeduction",r.getDouble(4));P.putDouble("rule.rebate87aLimit",r.getDouble(5));P.putDouble("rule.cessRate",r.getDouble(6));P.putDouble("rule.epfRate",r.getDouble(7));}}}catch(SQLException ignored){}}
 public static synchronized double get(String key){double fallback=DEFAULTS.getOrDefault(key,0.0);return P.getDouble("rule."+key,fallback);}
 public static synchronized Map<String,Double> all(){Map<String,Double> out=new LinkedHashMap<>();for(String k:DEFAULTS.keySet())out.put(k,get(k));return out;}
 public static synchronized void save(Map<String,Double> values)throws SQLException{for(String k:DEFAULTS.keySet()){double value=values.getOrDefault(k,DEFAULTS.get(k));if(!Double.isFinite(value)||value<0)throw new IllegalArgumentException("Invalid value");P.putDouble("rule."+k,value);}try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);String set="epf_employee_value=?,esic_wage_threshold=?,esic_employee_rate=?,esic_employer_rate=?,standard_deduction=?,section_87a_limit=?,health_education_cess_rate=?";try(PreparedStatement u=c.prepareStatement("UPDATE settings_deduction_rules SET "+set+" WHERE id=(SELECT id FROM settings_deduction_rules WHERE is_deleted=0 ORDER BY id LIMIT 1)")){bind(u);if(u.executeUpdate()==0)try(PreparedStatement i=c.prepareStatement("INSERT INTO settings_deduction_rules(epf_employee_value,esic_wage_threshold,esic_employee_rate,esic_employer_rate,standard_deduction,section_87a_limit,health_education_cess_rate,is_deleted) VALUES(?,?,?,?,?,?,?,0)")){bind(i);i.executeUpdate();}}c.commit();}}
 private static void bind(PreparedStatement s)throws SQLException{s.setDouble(1,get("epfRate"));s.setDouble(2,get("esicCeiling"));s.setDouble(3,get("esicRate"));s.setDouble(4,get("esicEmployerRate"));s.setDouble(5,get("standardDeduction"));s.setDouble(6,get("rebate87aLimit"));s.setDouble(7,get("cessRate"));}
 public static double workingHours(){return get("workingHours");}public static double hraPercent(){return get("hraPercent");}public static double attendanceBonus(){return get("attendanceBonus");}public static double conveyance(){return get("conveyance");}public static double medical(){return get("medical");}public static double specialBase(){return get("specialBase");}public static double otLimit(){return CompanyPolicyStore.maxOtLimit();}public static double otMultiplier(){return CompanyPolicyStore.otMultiplier();}public static double esicCeiling(){return get("esicCeiling");}public static double esicRate(){return get("esicRate");}public static double esicEmployerRate(){return get("esicEmployerRate");}public static double standardDeduction(){return get("standardDeduction");}public static double rebate87aLimit(){return get("rebate87aLimit");}public static double cessRate(){return get("cessRate");}public static double epfWageCap(){return get("epfWageCap");}public static double epfRate(){return get("epfRate");}public static double epsRate(){return get("epsRate");}public static double ptThreshold(){return get("ptThreshold");}public static double ptAmount(){return get("ptAmount");}
 private PayrollRulesStore(){}
}
