import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.time.Year;
import java.time.YearMonth;
import java.awt.print.PrinterJob;
import javax.print.PrintServiceLookup;

/** Individual, bulk, and history payslip workflow. */
public class PayrollPanel extends JPanel {
    private final EmployeeDAO employees=new EmployeeDAO();
    private final PayslipHistoryDAO historyDAO=new PayslipHistoryDAO();
    private final JTabbedPane tabs=new JTabbedPane();
    private int individualYear=FinancialYear.currentStart(),bulkYear=FinancialYear.currentStart();
    private JTabbedPane individualMonths,bulkMonths;
    private PayslipHistoryPanel history;

    public PayrollPanel(PayrollSystemFrame frame){
        setLayout(new BorderLayout());setBorder(UIStyleUtility.compactModuleBorder());
        tabs.addTab("Generate Payslip",individual());
        tabs.addTab("Generate Bulk Payslip",bulk());
        history=new PayslipHistoryPanel();tabs.addTab("Payslip Generation History",history);
        add(tabs,BorderLayout.CENTER);
    }
    public void refreshEmployees(){buildIndividualMonths();buildBulkMonths();history.refresh();}
    private JComponent individual(){
        JPanel panel=new JPanel(new BorderLayout(8,8));
        JComboBox<String> year=FinancialYear.selector(individualYear);JButton open=new JButton("Open Year");
        open.addActionListener(e->{individualYear=FinancialYear.parse((String)year.getSelectedItem());buildIndividualMonths();});
        JPanel top=yearBar(year,open);panel.add(top,BorderLayout.NORTH);
        individualMonths=new JTabbedPane(JTabbedPane.TOP,JTabbedPane.WRAP_TAB_LAYOUT);individualMonths.addChangeListener(e->loadIndividualMonth());panel.add(individualMonths,BorderLayout.CENTER);buildIndividualMonths();
        return panel;
    }
    private void buildIndividualMonths(){
        if(individualMonths==null)return;int selected=Math.max(0,individualMonths.getSelectedIndex());individualMonths.removeAll();
        for(int i=0;i<12;i++){YearMonth period=FinancialYear.month(individualYear,i);individualMonths.addTab(shortMonth(period),loadingPanel("Loading payslip…"));setMonthTab(individualMonths,i,period);}individualMonths.setSelectedIndex(Math.min(selected,11));loadIndividualMonth();
        individualMonths.revalidate();individualMonths.repaint();
    }
    private JPanel loadingPanel(String text){JPanel panel=new JPanel(new GridBagLayout());panel.add(new JLabel(text));return panel;}
    private void loadIndividualMonth(){int index=individualMonths==null?-1:individualMonths.getSelectedIndex();if(index<0)return;JComponent current=(JComponent)individualMonths.getComponentAt(index);if(Boolean.TRUE.equals(current.getClientProperty("loading"))||current.getComponentCount()>1)return;current.putClientProperty("loading",Boolean.TRUE);int activeYear=individualYear;YearMonth period=FinancialYear.month(activeYear,index);ApplicationTasks.execute(()->{JComponent form=individualForm(period);SwingUtilities.invokeLater(()->{if(individualYear==activeYear&&individualMonths.getSelectedIndex()==index){TabStyle.apply(form);individualMonths.setComponentAt(index,form);}});});}
    private JComponent individualForm(YearMonth period){
        JPanel panel=new JPanel(new GridLayout(1,2,36,0));panel.setBorder(BorderFactory.createEmptyBorder(UIStyleUtility.MODULE_TOP_GAP,120,12,120));
        JComboBox<Object> selectedEmployee=new JComboBox<>();selectedEmployee.addItem("-- Select Employee --");for(Employee person:employees.listForMonth("",period))selectedEmployee.addItem(person);selectedEmployee.setSelectedIndex(0);
        JTextField basic=out(),monthly=out(),allowance=out(),otPay=out(),totalGross=out(),totalDeductions=out(),totalNet=out(),performance=out(),other=out();
        JPanel left=column(),right=column();addRow(left,"Employee ID",selectedEmployee);addRow(left,"Profile Basic Pay",basic);addRow(left,"Total Allowances",allowance);addRow(left,"Performance Pay",performance);addRow(left,"Gross Salary",totalGross);
        addRow(right,"Monthly Basic",monthly);addRow(right,"OT Pay",otPay);addRow(right,"Other Earnings",other);addRow(right,"Total Deductions",totalDeductions);addRow(right,"Net Salary",totalNet);panel.add(left);panel.add(right);
        final boolean[] loading={false},otherOverride={false};Runnable update=()->updateFields(selected(selectedEmployee),period,performance,other,otherOverride[0],basic,monthly,allowance,otPay,totalGross,totalDeductions,totalNet);
        selectedEmployee.addActionListener(e->{Employee person=selected(selectedEmployee);boolean wages=person!=null&&person.isWagesStructure();right.getComponent(2).setVisible(wages);otPay.setVisible(wages);MonthlyEarningsStore.Value earnings=person==null?null:MonthlyEarningsStore.get(person.getId(),period.toString());loading[0]=true;performance.setText(Money.text(earnings==null?0:earnings.performance));otherOverride[0]=false;other.setText(Money.text(earnings==null?0:earnings.overtime+earnings.reimbursements));loading[0]=false;update.run();right.revalidate();right.repaint();});
        javax.swing.event.DocumentListener performanceLive=new javax.swing.event.DocumentListener(){private void changed(){Employee person=selected(selectedEmployee);if(!loading[0]&&person!=null){PayslipPerformanceStore.put(person.getId(),period.toString(),amount(performance.getText()));update.run();}}public void insertUpdate(javax.swing.event.DocumentEvent e){changed();}public void removeUpdate(javax.swing.event.DocumentEvent e){changed();}public void changedUpdate(javax.swing.event.DocumentEvent e){changed();}};performance.getDocument().addDocumentListener(performanceLive);
        javax.swing.event.DocumentListener otherLive=new javax.swing.event.DocumentListener(){private void changed(){Employee person=selected(selectedEmployee);if(!loading[0]&&person!=null){otherOverride[0]=true;PayslipOtherEarningsStore.put(person.getId(),period.toString(),amount(other.getText()));update.run();}}public void insertUpdate(javax.swing.event.DocumentEvent e){changed();}public void removeUpdate(javax.swing.event.DocumentEvent e){changed();}public void changedUpdate(javax.swing.event.DocumentEvent e){changed();}};other.getDocument().addDocumentListener(otherLive);
        JPanel out=new JPanel(new BorderLayout());out.add(panel,BorderLayout.CENTER);JPanel actions=new JPanel();JButton preview=new JButton("Preview Payslip"),print=new JButton("Print Payslip"),download=new JButton("Generate & Download PDF");preview.addActionListener(e->previewSelected(selected(selectedEmployee),period,amount(performance.getText()),amount(other.getText()),otherOverride[0]));print.addActionListener(e->printSelected(selected(selectedEmployee),period,amount(performance.getText()),amount(other.getText()),otherOverride[0]));download.addActionListener(e->downloadSelected(selected(selectedEmployee),period,amount(performance.getText()),amount(other.getText()),otherOverride[0]));actions.add(preview);actions.add(print);actions.add(download);out.add(actions,BorderLayout.SOUTH);update.run();return out;
    }
    private JComponent bulk(){
        JPanel panel=new JPanel(new BorderLayout(8,8));JComboBox<String> year=FinancialYear.selector(bulkYear);JButton open=new JButton("Open Year");
        open.addActionListener(e->{bulkYear=FinancialYear.parse((String)year.getSelectedItem());buildBulkMonths();});
        panel.add(yearBar(year,open),BorderLayout.NORTH);bulkMonths=new JTabbedPane(JTabbedPane.TOP,JTabbedPane.WRAP_TAB_LAYOUT);bulkMonths.addChangeListener(e->loadBulkMonth());panel.add(bulkMonths,BorderLayout.CENTER);buildBulkMonths();return panel;
    }
    private void buildBulkMonths(){
        if(bulkMonths==null)return;int selected=Math.max(0,bulkMonths.getSelectedIndex());bulkMonths.removeAll();
        for(int i=0;i<12;i++){YearMonth period=FinancialYear.month(bulkYear,i);bulkMonths.addTab(shortMonth(period),loadingPanel("Loading payslips…"));setMonthTab(bulkMonths,i,period);}bulkMonths.setSelectedIndex(Math.min(selected,11));loadBulkMonth();bulkMonths.revalidate();bulkMonths.repaint();
    }
    private void loadBulkMonth(){int index=bulkMonths==null?-1:bulkMonths.getSelectedIndex();if(index<0)return;JComponent current=(JComponent)bulkMonths.getComponentAt(index);if(Boolean.TRUE.equals(current.getClientProperty("loading"))||current.getComponentCount()>1)return;current.putClientProperty("loading",Boolean.TRUE);int activeYear=bulkYear;YearMonth period=FinancialYear.month(activeYear,index);ApplicationTasks.execute(()->{JComponent sheet=bulkSheet(period);SwingUtilities.invokeLater(()->{if(bulkYear==activeYear&&bulkMonths.getSelectedIndex()==index){TabStyle.apply(sheet);bulkMonths.setComponentAt(index,sheet);}});});}
    private JComponent bulkSheet(YearMonth period){
        java.util.List<Employee> list=employees.listForMonth("",period);Object[][] rows=new Object[list.size()][5];
        for(int i=0;i<list.size();i++){Employee person=list.get(i);PayrollCalculator.Result result=PayslipPDF.result(person,period);rows[i]=new Object[]{Boolean.FALSE,person.getId(),person.getName(),person.getDesignation()+" / "+person.getDepartment(),Money.round(result.net)};}
        DefaultTableModel model=new DefaultTableModel(rows,new String[]{"Select","Employee ID","Employee Name","Designation / Department","Net Payable Salary"}){public Class<?> getColumnClass(int c){return c==0?Boolean.class:(c==4?Double.class:String.class);}public boolean isCellEditable(int r,int c){return c==0;}};
        JTable table=new JTable(model);table.getColumnModel().getColumn(4).setCellRenderer(Money.renderer());UIStyleUtility.applyProfessionalTableStyle(table);
        JCheckBox all=new JCheckBox("Select All");all.addActionListener(e->{for(int r=0;r<model.getRowCount();r++)model.setValueAt(all.isSelected(),r,0);});
        JButton generate=new JButton("Generate Bulk Payslip"),generateSelected=new JButton("Generate Selected Payslips"),printAll=new JButton("Print All Payslips");generate.addActionListener(e->generateBulk(model,period));generateSelected.addActionListener(e->generateBulk(model,period));printAll.addActionListener(e->printAll(period));
        JTextField search=new JTextField(18);javax.swing.table.TableRowSorter<DefaultTableModel> sorter=new javax.swing.table.TableRowSorter<>(model);table.setRowSorter(sorter);search.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){private void filter(){String q=search.getText().trim();sorter.setRowFilter(q.isEmpty()?null:javax.swing.RowFilter.regexFilter("(?i)"+java.util.regex.Pattern.quote(q),1,2));}public void insertUpdate(javax.swing.event.DocumentEvent e){filter();}public void removeUpdate(javax.swing.event.DocumentEvent e){filter();}public void changedUpdate(javax.swing.event.DocumentEvent e){filter();}});
        JPanel top=new JPanel(new BorderLayout());JPanel filters=new JPanel(new FlowLayout(FlowLayout.LEFT));filters.add(new JLabel("Search Employee:"));filters.add(search);filters.add(all);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT));actions.add(generate);actions.add(generateSelected);actions.add(printAll);top.add(filters,BorderLayout.WEST);top.add(actions,BorderLayout.EAST);JPanel out=new JPanel(new BorderLayout());out.add(top,BorderLayout.NORTH);out.add(new JScrollPane(table),BorderLayout.CENTER);return out;
    }
    private void generateBulk(DefaultTableModel model,YearMonth period){
        java.util.List<Employee> picked=new java.util.ArrayList<>();for(int r=0;r<model.getRowCount();r++)if(Boolean.TRUE.equals(model.getValueAt(r,0))){java.util.List<Employee> found=employees.listByEmployeeId(String.valueOf(model.getValueAt(r,1)));if(!found.isEmpty())picked.add(found.get(0));}
        if(picked.isEmpty()){message("Select at least one employee.");return;}JFileChooser chooser=new JFileChooser();chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if(chooser.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;File folder=new File(chooser.getSelectedFile(),period.getMonth()+"-"+period.getYear());folder.mkdirs();int count=0;
        final int[] generated={0};
        ApplicationTasks.execute(()->{for(Employee person:picked){PayrollCalculator.Result result=PayslipPDF.result(person,period);File temp=PayslipPDF.create(person,result,folder,period);if(temp==null)continue;String name=safeName(person.getId())+"-"+safeName(person.getName())+"-"+period.getMonth()+"-"+period.getYear()+".pdf";File target=new File(folder,name);try{Files.move(temp.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING);historyDAO.save(new PayslipRecord(person.getId(),person.getName(),period.toString(),target.getAbsolutePath(),PayslipPDF.previewText(person,result,period),Money.round(result.net),0));ActivityLogger.log("Payslip","BULK PAYSLIP GENERATED",person.getId()+" - "+period,"SUCCESS");generated[0]++;}catch(Exception ignored){}}SwingUtilities.invokeLater(()->{history.refresh();message(generated[0]+" payslips saved in "+folder.getAbsolutePath());});});
    }
    private void printAll(YearMonth period){File outputDir=new File("Payslips"+File.separator+bulkYear+File.separator+period);if(!outputDir.exists()&&!outputDir.mkdirs()){message("Could not create the payslip output folder.");return;}PrinterJob batchJob=PrinterJob.getPrinterJob();if(batchJob==null||PrintServiceLookup.lookupDefaultPrintService()==null){System.err.println("No default print service found.");message("No default print service found.");return;}if(!batchJob.printDialog())return;ApplicationTasks.execute(()->{int printed=0;for(Employee person:employees.listForMonth("",period)){PayrollCalculator.Result result=PayslipPDF.result(person,period);File pdf=PayslipPDF.create(person,result,outputDir,period);if(pdf==null)continue;try{if(Desktop.isDesktopSupported()&&Desktop.getDesktop().isSupported(Desktop.Action.PRINT)){Desktop.getDesktop().print(pdf);printed++;}}catch(Exception ex){ex.printStackTrace();}}final int count=printed;AuditLogDAO.logActivity(Session.currentUser,"BULK_PAYSLIP_PRINT","Triggered bulk print for month: "+period,new java.sql.Timestamp(System.currentTimeMillis()));ActivityLogger.log("Payslip","BULK PAYSLIP PRINT","Triggered bulk print for month: "+period,"SUCCESS");SwingUtilities.invokeLater(()->message(count+" payslips sent to the printer queue."));});}
    private JPanel yearBar(JComponent year,JButton open){JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));bar.add(new JLabel("Financial Year:"));bar.add(year);bar.add(open);return bar;}
    private String shortMonth(YearMonth period){return period.getMonth().toString().substring(0,3);}
    private void setMonthTab(JTabbedPane pane,int index,YearMonth period){JLabel tab=new JLabel(shortMonth(period),SwingConstants.CENTER);tab.setPreferredSize(new Dimension(80,30));tab.setFont(new Font("SansSerif",Font.BOLD,15));tab.setForeground(Color.WHITE);pane.setTabComponentAt(index,tab);}
    private JTextField out(){JTextField field=new JTextField(16);field.setEditable(false);return field;}
    private JTextField moneyInput(){JTextField field=new JTextField("0.00",16);field.addFocusListener(new java.awt.event.FocusAdapter(){public void focusGained(java.awt.event.FocusEvent e){field.selectAll();}});return field;}
    private JPanel column(){JPanel panel=new JPanel(new GridBagLayout());panel.setOpaque(false);return panel;}
    private void addRow(JPanel panel,String label,JComponent value){GridBagConstraints c=new GridBagConstraints();c.gridy=panel.getComponentCount()/2;c.insets=new Insets(8,8,8,8);c.fill=GridBagConstraints.HORIZONTAL;c.gridx=0;c.weightx=.42;panel.add(new JLabel(label),c);c.gridx=1;c.weightx=.58;panel.add(value,c);}
    private Employee selected(JComboBox<Object> combo){Object value=combo.getSelectedItem();return value instanceof Employee?(Employee)value:null;}
    private DefaultCellEditor selectAllMoneyEditor(){JTextField field=new JTextField();field.addFocusListener(new java.awt.event.FocusAdapter(){public void focusGained(java.awt.event.FocusEvent e){field.selectAll();}});return new DefaultCellEditor(field){public Component getTableCellEditorComponent(JTable table,Object value,boolean isSelected,int row,int column){Component component=super.getTableCellEditorComponent(table,value,isSelected,row,column);SwingUtilities.invokeLater(field::selectAll);return component;}};}
    private int row(JPanel p,GridBagConstraints c,int r,String a,JComponent av,String b,JComponent bv){c.gridwidth=1;c.gridy=r;c.gridx=0;p.add(new JLabel(a),c);c.gridx=1;p.add(av,c);c.gridx=2;p.add(new JLabel(b),c);c.gridx=3;p.add(bv,c);return r+1;}
    private double automaticOtherEarnings(Employee person,YearMonth period){PayslipPDF.result(person,period,0,0);return CTCStore.getOther(person.getId(),period.toString()).others;}
    private void updateFields(Employee person,YearMonth period,JTextField performance,JTextField manualOther,boolean otherOverride,JTextField basic,JTextField monthly,JTextField allowance,JTextField otPay,JTextField totalGross,JTextField totalDeductions,JTextField totalNet){if(person==null){for(JTextField field:new JTextField[]{basic,monthly,allowance,otPay,totalGross,totalDeductions,totalNet})field.setText("0.00");return;}PayrollCalculator.Result r=PayslipPDF.result(person,period);basic.setText(Money.text(SalaryRevisionStore.basicFor(person,period)));monthly.setText(Money.text(r.earnings.get("Monthly Basic Pay")));allowance.setText(Money.text(r.earnings.get("Total Allowances")));otPay.setText(person.isWagesStructure()?Money.text(r.earnings.get("OT Pay")):"");totalGross.setText(Money.text(r.gross));totalDeductions.setText(Money.text(r.deductions.get("Total Deductions")));totalNet.setText(Money.text(r.net));}
    private void previewSelected(Employee person,YearMonth period,double performance,double other,boolean otherOverride){if(person==null){message("Select an employee.");return;}JScrollPane view=new JScrollPane(new PayslipTemplatePanel(person,PayslipPDF.result(person,period),period));view.setPreferredSize(new Dimension(900,760));JOptionPane.showMessageDialog(this,view,"Payslip Preview",JOptionPane.PLAIN_MESSAGE);}
    private void printSelected(Employee person,YearMonth period,double performance,double other,boolean otherOverride){if(person==null){message("Select an employee.");return;}PayrollCalculator.Result result=PayslipPDF.result(person,period);File pdf=PayslipPDF.create(person,result,null,period);if(pdf==null){message("Could not create PDF for printing.");return;}try{if(!Desktop.isDesktopSupported()||!Desktop.getDesktop().isSupported(Desktop.Action.PRINT))throw new UnsupportedOperationException();Desktop.getDesktop().print(pdf);ActivityLogger.log("Payslip","PAYSLIP PRINT REQUESTED",person.getId()+" - "+period,"SUCCESS");}catch(Exception e){e.printStackTrace();message("Printing is not available on this system.");}}
    private void downloadSelected(Employee person,YearMonth period,double performance,double other,boolean otherOverride){if(person==null){message("Select an employee.");return;}PayrollCalculator.Result result=PayslipPDF.result(person,period);File pdf=PayslipPDF.create(person,result,null,period);if(pdf==null){if(PayslipPDF.lastFailureIsFileLocked())JOptionPane.showMessageDialog(this,"Cannot write PDF. Please close any open PDF file viewer and try again.","File Access Error",JOptionPane.ERROR_MESSAGE);else message("Could not create PDF. Check the console for details.");return;}JFileChooser chooser=new JFileChooser();chooser.setSelectedFile(new File(safeName(person.getId())+"-"+safeName(person.getName())+"-"+period.getMonth()+"-"+period.getYear()+".pdf"));if(chooser.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)try{Files.copy(pdf.toPath(),chooser.getSelectedFile().toPath(),StandardCopyOption.REPLACE_EXISTING);historyDAO.save(new PayslipRecord(person.getId(),person.getName(),period.toString(),chooser.getSelectedFile().getAbsolutePath(),PayslipPDF.previewText(person,result,period),Money.round(result.net),0));ActivityLogger.log("Payslip","PAYSLIP PDF EXPORTED",person.getId()+" - "+period,"SUCCESS");history.refresh();}catch(FileNotFoundException x){x.printStackTrace();JOptionPane.showMessageDialog(this,"Cannot write PDF. Please close any open PDF file viewer and try again.","File Access Error",JOptionPane.ERROR_MESSAGE);}catch(Exception x){x.printStackTrace();if(x instanceof java.nio.file.AccessDeniedException)JOptionPane.showMessageDialog(this,"Cannot write PDF. Please close any open PDF file viewer and try again.","File Access Error",JOptionPane.ERROR_MESSAGE);else message("PDF download failed.");}}
    private static double amount(String value){try{return Money.round(Double.parseDouble(value.trim()));}catch(Exception ignored){return 0;}}
    private static String safeName(String text){return text==null?"Employee":text.replaceAll("[^a-zA-Z0-9_-]","_");}
    private void message(String text){JOptionPane.showMessageDialog(this,text);}
}
