import java.util.*;import java.util.prefs.Preferences;
/** Persistent friendly payroll formula definitions, evaluated without scripts or macros. */
public final class PayrollFormulaStore{
 private static final Preferences P=Preferences.userNodeForPackage(PayrollFormulaStore.class);private static final Map<String,String> D=new LinkedHashMap<>();
 static{D.put("HRA","ROUND(Basic_Pay_For_Month * (HRA_Percent / 100), 0)");D.put("Attendance Bonus","IF(Days_Payable == 0 OR Leave_Taken > 0, 0, Attendance_Bonus_Amount)");D.put("Conveyance","IF(Basic_Pay_For_Month == 0, 0, Conveyance_Amount)");D.put("Medical","IF(Basic_Pay_For_Month == 0, 0, Medical_Amount)");D.put("Special Allowance Base","Employee_Monthly_CTC - (Base_Basic + Base_HRA + Base_Conveyance + Base_Medical + Base_Fixed_Allowances)");D.put("Special Allowance","ROUND((Special_Allowance_Base / Total_Working_Days) * Days_Payable, 0)");D.put("OT Pay","ROUND(MIN(OT_Hours, OT_Limit) * ((Basic_Pay_For_Month / Total_Days_In_Month / Working_Hours) * OT_Multiplier), 0)");D.put("Others","IF(OT_Hours < OT_Limit, 0, ROUND((OT_Hours - OT_Limit) * ((Base_Basic_Pay / Total_Days_In_Month / Working_Hours) * OT_Multiplier), 0))");D.put("ESIC","IF(Days_Payable == 0 OR Gross_Wages > ESIC_Ceiling, 0, CEIL(Gross_Wages * (ESIC_Rate / 100)))");D.put("EPF","ROUND(MIN(Gross_Wages, EPF_Wage_Cap) * (EPF_Rate / 100), 2)");D.put("PT","IF(Days_Payable == 0 OR Applicable_Gross <= PT_Threshold, 0, PT_Amount)");}
 public static String get(String key){return P.get("formula."+key,D.getOrDefault(key,""));}public static Map<String,String> all(){Map<String,String> r=new LinkedHashMap<>();for(String k:D.keySet())r.put(k,get(k));try{for(String k:P.keys())if(k.startsWith("formula.")){String name=k.substring(8);r.put(name,P.get(k,""));}}catch(Exception ignored){}return r;}public static void save(Map<String,String> values){try{for(String k:P.keys())if(k.startsWith("formula.")&&!values.containsKey(k.substring(8)))P.remove(k);}catch(Exception ignored){}for(Map.Entry<String,String> e:values.entrySet())if(!e.getKey().trim().isEmpty()&&!e.getValue().trim().isEmpty())P.put("formula."+e.getKey().trim(),e.getValue().trim());}
 public static double eval(String key,Map<String,Double> values,double fallback){try{return new Parser(get(key),values).parse();}catch(Exception e){return fallback;}}
 private static final class Parser{final String s;final Map<String,Double> v;int p;Parser(String s,Map<String,Double>v){int q=s.indexOf('=');this.s=(q>=0?s.substring(q+1):s).trim();this.v=v;}double parse(){double x=or();ws();if(p!=s.length())throw new IllegalArgumentException();return x;}double or(){double x=and();while(word("OR")){double y=and();x=x!=0||y!=0?1:0;}return x;}double and(){double x=cmp();while(word("AND")){double y=cmp();x=x!=0&&y!=0?1:0;}return x;}double cmp(){double x=add();for(;;){if(op("==")){x=x==add()?1:0;}else if(op(">=")){x=x>=add()?1:0;}else if(op("<=")){x=x<=add()?1:0;}else if(op(">")){x=x>add()?1:0;}else if(op("<")){x=x<add()?1:0;}else return x;}}double add(){double x=mul();for(;;){if(op("+"))x+=mul();else if(op("-"))x-=mul();else return x;}}double mul(){double x=atom();for(;;){if(op("*"))x*=atom();else if(op("/"))x/=atom();else return x;}}double atom(){ws();if(op("(")){double x=or();need(")");return x;}if(p<s.length()&&(Character.isDigit(s.charAt(p))||s.charAt(p)=='.')){int a=p;while(p<s.length()&&(Character.isDigit(s.charAt(p))||s.charAt(p)=='.'))p++;return Double.parseDouble(s.substring(a,p));}String id=id();if(id.isEmpty())throw new IllegalArgumentException();if(op("(")){java.util.List<Double>a=new ArrayList<>();if(!op(")")){do{a.add(or());}while(op(","));need(")");}if(id.equalsIgnoreCase("IF"))return a.get(0)!=0?a.get(1):a.get(2);if(id.equalsIgnoreCase("ROUND"))return a.size()>1&&a.get(1)==0?Math.round(a.get(0)):Math.round(a.get(0)*100)/100.0;if(id.equalsIgnoreCase("MIN"))return Math.min(a.get(0),a.get(1));if(id.equalsIgnoreCase("CEIL"))return Math.ceil(a.get(0));throw new IllegalArgumentException();}return v.getOrDefault(id,0.0);}String id(){ws();int a=p;while(p<s.length()&&(Character.isLetterOrDigit(s.charAt(p))||s.charAt(p)=='_'))p++;return s.substring(a,p);}boolean op(String x){ws();if(s.regionMatches(true,p,x,0,x.length())){p+=x.length();return true;}return false;}boolean word(String x){ws();int e=p+x.length();if(s.regionMatches(true,p,x,0,x.length())&&(e==s.length()||!Character.isLetterOrDigit(s.charAt(e)))){p=e;return true;}return false;}void need(String x){if(!op(x))throw new IllegalArgumentException();}void ws(){while(p<s.length()&&Character.isWhitespace(s.charAt(p)))p++;}}
 private PayrollFormulaStore(){}
}
