import javax.swing.*;import java.awt.*;import java.util.*;
/** Minimal Formula Manager: named Excel-style expressions plus the configured constants. */
public class PayrollRulesSettingsPanel extends JPanel{
 private final JPanel rows=new JPanel(new GridBagLayout());private final java.util.List<Row> formulaRows=new ArrayList<>();private final Map<String,JTextField> constants=new LinkedHashMap<>();
 private static final String[][] RULES={{"workingHours","Working Hours Per Day"},{"hraPercent","HRA Percentage"},{"attendanceBonus","Attendance Bonus Fixed Amount"},{"conveyance","Conveyance Allowance Fixed Amount"},{"medical","Medical Allowance Fixed Amount"},{"specialBase","Special Allowance Base Numerator"},{"otLimit","OT Hours Cap / Limit"},{"otMultiplier","OT Multiplier Rate"},{"esicCeiling","ESIC Gross Wage Ceiling"},{"esicRate","ESIC Employee Contribution Rate (%)"},{"epfWageCap","EPF Wage Cap"},{"epfRate","EPF Employee Rate (%)"},{"epsRate","EPS Employer Rate (%)"},{"ptThreshold","PT Wage Threshold"},{"ptAmount","PT Deduction Amount"}};
 public PayrollRulesSettingsPanel(){setLayout(new BorderLayout());JTabbedPane tabs=new JTabbedPane();tabs.addTab("Formula Manager",formulaManager());tabs.addTab("Variables & Constants",constants());add(tabs,BorderLayout.CENTER);}
 private JComponent formulaManager(){JPanel outer=new JPanel(new BorderLayout());JPanel header=new JPanel(new GridLayout(1,2,8,0));header.add(new JLabel("Formula Name / Component"));header.add(new JLabel("Formula Logic Expression"));outer.add(header,BorderLayout.NORTH);for(Map.Entry<String,String> e:PayrollFormulaStore.all().entrySet())addRow(e.getKey(),e.getValue(),false);JButton add=new JButton("+ Add New Custom Formula");add.addActionListener(e->{addRow("","",true);rows.revalidate();rows.repaint();});JButton save=new JButton("Save Settings");save.addActionListener(e->save());JPanel bottom=new JPanel(new FlowLayout(FlowLayout.CENTER));bottom.add(add);bottom.add(save);outer.add(new JScrollPane(rows),BorderLayout.CENTER);outer.add(bottom,BorderLayout.SOUTH);return outer;}
 private void addRow(String name,String formula,boolean custom){Row row=new Row(new JTextField(name,20),new JTextField(formula,62),custom);formulaRows.add(row);rebuildRows();}
 private void rebuildRows(){rows.removeAll();GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(4,6,4,6);g.fill=GridBagConstraints.HORIZONTAL;g.weightx=.25;for(int i=0;i<formulaRows.size();i++){Row r=formulaRows.get(i);g.gridy=i;g.gridx=0;rows.add(r.name,g);g.gridx=1;g.weightx=.75;rows.add(r.formula,g);g.weightx=0;g.gridx=2;if(r.custom){JButton del=new JButton("Delete");del.addActionListener(e->{formulaRows.remove(r);rebuildRows();});rows.add(del,g);}}rows.revalidate();rows.repaint();}
 private JComponent constants(){JPanel p=new JPanel(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,8,6,8);g.fill=GridBagConstraints.HORIZONTAL;for(int i=0;i<RULES.length;i++){g.gridy=i;g.gridx=0;p.add(new JLabel(RULES[i][1]),g);JTextField f=new JTextField(String.valueOf(PayrollRulesStore.get(RULES[i][0])),14);constants.put(RULES[i][0],f);g.gridx=1;p.add(f,g);}return new JScrollPane(p);}
 private void save(){try{Map<String,Double> values=new LinkedHashMap<>();for(Map.Entry<String,JTextField>e:constants.entrySet())values.put(e.getKey(),Double.parseDouble(e.getValue().getText().trim()));PayrollRulesStore.save(values);Map<String,String> fs=new LinkedHashMap<>();for(Row r:formulaRows){String n=r.name.getText().trim(),f=r.formula.getText().trim();if(n.isEmpty()||f.isEmpty())throw new IllegalArgumentException();fs.put(n,f);}PayrollFormulaStore.save(fs);PayrollEvents.attendanceSaved();JOptionPane.showMessageDialog(this,"Formula Manager saved.");}catch(Exception e){JOptionPane.showMessageDialog(this,"Enter a name and valid formula for every row, plus valid constants.");}}
 private static final class Row{final JTextField name,formula;final boolean custom;Row(JTextField n,JTextField f,boolean c){name=n;formula=f;custom=c;}}
}
