import javax.swing.*;import javax.swing.table.*;import java.awt.*;import java.io.*;import java.nio.file.*;import java.time.*;

/** Monthly history of generated payslips. */
public class PayslipHistoryPanel extends JPanel {
 private final PayslipHistoryDAO dao=new PayslipHistoryDAO();private final EmployeeDAO employees=new EmployeeDAO();private final JTabbedPane months=new JTabbedPane();private final JComboBox<String> year=FinancialYear.selector(FinancialYear.currentStart());
 public PayslipHistoryPanel(){setLayout(new BorderLayout(6,6));setBorder(UIStyleUtility.compactModuleBorder());JButton open=new JButton("Open Year");open.addActionListener(e->build());JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT,5,2));top.add(new JLabel("Payslip History - Financial Year:"));top.add(year);top.add(open);months.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);add(top,BorderLayout.NORTH);add(months,BorderLayout.CENTER);build();}
 public void refresh(){build();}
 private void build(){months.removeAll();int selected=FinancialYear.parse((String)year.getSelectedItem());for(int i=0;i<12;i++){YearMonth period=FinancialYear.month(selected,i);months.addTab(FinancialYear.shortName(period),sheet(period));JLabel tab=new JLabel(FinancialYear.shortName(period),SwingConstants.CENTER);tab.setPreferredSize(new Dimension(80,30));tab.setFont(new Font("SansSerif",Font.BOLD,15));tab.setForeground(Color.WHITE);months.setTabComponentAt(i,tab);}revalidate();repaint();}
 private JComponent sheet(YearMonth period){java.util.List<PayslipRecord> records=dao.list(period.toString());Object[][] rows=new Object[records.size()][5];for(int i=0;i<records.size();i++){PayslipRecord r=records.get(i);rows[i]=new Object[]{r.employeeId,r.employeeName,r.generatedDate,Money.round(r.netSalary),r};}DefaultTableModel model=new DefaultTableModel(rows,new String[]{"Employee ID","Employee Name","Generated Date","Net Salary","Actions"}){public boolean isCellEditable(int r,int c){return c==4;}};JTable table=new JTable(model);table.setShowGrid(true);table.setShowHorizontalLines(true);table.setShowVerticalLines(true);table.setGridColor(new Color(180,180,180));table.setBorder(BorderFactory.createLineBorder(new Color(160,160,160)));table.getColumnModel().getColumn(3).setCellRenderer(Money.renderer());UIStyleUtility.applyProfessionalTableStyle(table);table.getColumnModel().getColumn(4).setCellRenderer(new ActionsRenderer());table.getColumnModel().getColumn(4).setCellEditor(new ActionsEditor());return new JScrollPane(table);}
 private class ActionsRenderer extends JPanel implements TableCellRenderer{ActionsRenderer(){add(new JButton("View"));add(new JButton("Download"));}public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){return this;}}
 private class ActionsEditor extends AbstractCellEditor implements TableCellEditor{private PayslipRecord record;private final JPanel panel=new JPanel();ActionsEditor(){JButton view=new JButton("View"),download=new JButton("Download");view.addActionListener(e->{show(record);fireEditingStopped();});download.addActionListener(e->{download(record);fireEditingStopped();});panel.add(view);panel.add(download);}public Component getTableCellEditorComponent(JTable t,Object v,boolean s,int r,int c){record=(PayslipRecord)v;return panel;}public Object getCellEditorValue(){return record;}}
 private void show(PayslipRecord record){try{java.util.List<Employee> match=employees.listByEmployeeId(record.employeeId);if(match.isEmpty())throw new IllegalStateException();Employee person=match.get(0);YearMonth period=YearMonth.parse(record.month);JScrollPane preview=new JScrollPane(new PayslipTemplatePanel(person,PayslipPDF.result(person,period),period));preview.setPreferredSize(new Dimension(900,760));JOptionPane.showMessageDialog(this,preview,"Payslip Preview",JOptionPane.PLAIN_MESSAGE);}catch(Exception e){JOptionPane.showMessageDialog(this,"The employee profile for this payslip is no longer available.");}}
 private void download(PayslipRecord record){File source=new File(record.pdfPath);if(!source.isFile()){JOptionPane.showMessageDialog(this,"The generated PDF is no longer available.");return;}JFileChooser chooser=new JFileChooser();chooser.setSelectedFile(new File(source.getName()));if(chooser.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)try{Files.copy(source.toPath(),chooser.getSelectedFile().toPath(),StandardCopyOption.REPLACE_EXISTING);}catch(IOException e){JOptionPane.showMessageDialog(this,"Download failed.");}}
}
