import java.sql.*;import java.time.*;import java.util.*;
/** SQLite-backed payslip history. */
public class PayslipHistoryDAO {
 public PayslipHistoryDAO(){ensure();}
 private void ensure(){try(Connection c=DBConnection.getConnection();Statement s=c==null?null:c.createStatement()){if(s==null)return;for(String x:new String[]{"preview_text TEXT","performance_pay REAL DEFAULT 0","manual_other_earnings REAL DEFAULT 0"})try{s.executeUpdate("ALTER TABLE payslip ADD COLUMN "+x);}catch(SQLException ignored){}}catch(SQLException ignored){}}
 private static YearMonth period(String value){try{return YearMonth.parse(value);}catch(Exception e){return YearMonth.now();}}
 private static String fy(YearMonth p){return FinancialYear.text(p.getMonthValue()>=4?p.getYear():p.getYear()-1);}
 public void save(PayslipRecord r){YearMonth m=period(r.month);try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("INSERT INTO payslip(employee_id,employee_name,month,fy,net_salary,generated_date,pdf_path,preview_text,performance_pay) SELECT ?,employee_name,?,?,?,?,?,?,? FROM employee_master_data WHERE employee_id=? AND is_deleted=0 ON CONFLICT(employee_id,month,fy) DO UPDATE SET net_salary=excluded.net_salary,generated_date=excluded.generated_date,pdf_path=excluded.pdf_path,preview_text=excluded.preview_text,performance_pay=excluded.performance_pay")){if(p==null)return;int i=1;p.setString(i++,r.employeeId);p.setString(i++,m.getMonth().toString().substring(0,3));p.setString(i++,fy(m));p.setDouble(i++,r.netSalary);p.setString(i++,r.generatedDate);p.setString(i++,r.pdfPath);p.setString(i++,r.preview);p.setDouble(i++,r.performancePay);p.setString(i,r.employeeId);p.executeUpdate();}catch(SQLException ignored){}}
 public List<PayslipRecord> list(String month){List<PayslipRecord> out=new ArrayList<>();YearMonth m=period(month);try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT p.* FROM payslip p JOIN employee_master_data e ON e.employee_id=p.employee_id AND e.is_deleted=0 WHERE p.month=? AND p.fy=? ORDER BY p.employee_name")){if(p==null)return out;p.setString(1,m.getMonth().toString().substring(0,3));p.setString(2,fy(m));ResultSet r=p.executeQuery();while(r.next()){PayslipRecord x=new PayslipRecord(r.getString("employee_id"),r.getString("employee_name"),month,r.getString("pdf_path"),r.getString("preview_text"),r.getDouble("net_salary"),r.getDouble("performance_pay"));String date=r.getString("generated_date");if(date!=null)x.generatedDate=date;out.add(x);}}catch(SQLException ignored){}return out;}
 public void purgeEmployee(String employeeId)throws SQLException{}
}
