import java.sql.*;import java.time.*;import java.util.*;
/** Effective-dated employee salary revisions stored in payroll.db. */
public final class SalaryRevisionStore {
 public static final class Revision {final double original,revised;final String effective;Revision(double o,double r,YearMonth p){original=o;revised=r;effective=p.toString();}YearMonth period(){return YearMonth.parse(effective);}}
 static{migrate();}private SalaryRevisionStore(){}
 private static void migrate(){try(Connection c=DBConnection.getConnection();Statement s=c==null?null:c.createStatement()){if(s==null)return;for(String x:new String[]{"employee_id TEXT","original_basic REAL DEFAULT 0","revised_basic REAL DEFAULT 0","effective_month TEXT"})try{s.executeUpdate("ALTER TABLE settings_revised_salary ADD COLUMN "+x);}catch(SQLException ignored){}}catch(SQLException ignored){}}
 private static List<Revision> list(String id){List<Revision> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT original_basic,revised_basic,effective_month FROM settings_revised_salary WHERE employee_id=? ORDER BY effective_month")){if(p==null)return out;p.setString(1,id);ResultSet r=p.executeQuery();while(r.next())try{out.add(new Revision(r.getDouble(1),r.getDouble(2),YearMonth.parse(r.getString(3))));}catch(Exception ignored){}}catch(SQLException ignored){}return out;}
 public static synchronized double basicFor(Employee e,YearMonth period){List<Revision> list=list(e.getId());if(list.isEmpty()){double basic=e.getBasicSalary();if(basic>0)return basic;double annual=CTCStore.get(e.getId()).basic;return annual>0?Money.round(annual/12.0):0;}double value=list.get(0).original;for(Revision r:list)if(!period.isBefore(r.period()))value=r.revised;return value;}
 public static synchronized void save(Employee e,double revised,YearMonth effective){double original=basicFor(e,effective.minusMonths(1));try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);try(PreparedStatement u=c.prepareStatement("UPDATE settings_revised_salary SET original_basic=?,revised_basic=?,revision_rule=?,increment_value=? WHERE employee_id=? AND effective_month=?");PreparedStatement i=c.prepareStatement("INSERT INTO settings_revised_salary(employee_id,original_basic,revised_basic,effective_month,revision_rule,increment_value) VALUES(?,?,?,?,?,?)")){u.setDouble(1,original);u.setDouble(2,revised);u.setString(3,"EMPLOYEE_REVISION");u.setDouble(4,revised);u.setString(5,e.getId());u.setString(6,effective.toString());if(u.executeUpdate()==0){i.setString(1,e.getId());i.setDouble(2,original);i.setDouble(3,revised);i.setString(4,effective.toString());i.setString(5,"EMPLOYEE_REVISION");i.setDouble(6,revised);i.executeUpdate();}}c.commit();AutoSaveService.markDirty();}catch(SQLException ignored){}}
 public static synchronized void purgeEmployee(String employeeId){}
}
