import javax.swing.*;
import java.awt.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.sql.*;
import java.util.Arrays;
import java.util.prefs.Preferences;

/** Stores the Master Data password hash only; it never gates application launch. */
public final class SecurityService {
    private static final Preferences PREFS=Preferences.userNodeForPackage(SecurityService.class); private static final String KEY="master_password_hash", PROMPT_KEY="master_password_setup_prompted", SALT="PayrollSystem.MasterData.v1";
    private SecurityService(){}
    public static boolean hasMasterPassword(){return readHash()!=null;}
    public static void showInitialSetupPrompt(Component parent){if(hasMasterPassword()||PREFS.getBoolean(PROMPT_KEY,false))return;SwingUtilities.invokeLater(()->{Object[] options={"Set Master Data Password","Later"};int choice=JOptionPane.showOptionDialog(parent,"Master Data is protected. Set its password now, or continue and configure it later in Settings.","Master Data Password Setup",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[0]);PREFS.putBoolean(PROMPT_KEY,true);if(choice==0)showSetPasswordDialog(parent);});}
    public static void offerMasterDataSetup(Component parent){Object[] options={"Set Master Data Password Now","Cancel / Later"};int choice=JOptionPane.showOptionDialog(parent,"Master Data is protected. A Master Data password must be set before it can be opened.","Master Data Protected",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,options,options[0]);if(choice==0)showSetPasswordDialog(parent);}
    public static boolean showSetPasswordDialog(Component parent){JPasswordField password=new JPasswordField(18),confirm=new JPasswordField(18);JPanel panel=new JPanel(new GridLayout(2,2,8,8));panel.add(new JLabel("Password"));panel.add(password);panel.add(new JLabel("Confirm Password"));panel.add(confirm);int choice=JOptionPane.showConfirmDialog(parent,panel,"Set Master Data Password",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);if(choice!=JOptionPane.OK_OPTION)return false;if(password.getPassword().length<4){JOptionPane.showMessageDialog(parent,"Password must contain at least 4 characters.");return showSetPasswordDialog(parent);}if(!Arrays.equals(password.getPassword(),confirm.getPassword())){JOptionPane.showMessageDialog(parent,"Passwords do not match.");return showSetPasswordDialog(parent);}boolean saved=setMasterPassword(password.getPassword());JOptionPane.showMessageDialog(parent,saved?"Master Data password has been set.":"Could not save the Master Data password.");return saved;}
    public static boolean promptForPassword(String title){JPasswordField input=new JPasswordField();int result=JOptionPane.showConfirmDialog(null,input,title,JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);boolean allowed=result==JOptionPane.OK_OPTION&&verifyMasterPassword(input.getPassword());ActivityLogger.log("Security",allowed?"MASTER DATA LOGIN":"MASTER DATA LOGIN FAILED",title,allowed?"LOGIN":"SECURITY WARNING");return allowed;}
    public static boolean changePassword(char[] current,char[] next){return verifyMasterPassword(current)&&next.length>=4&&setMasterPassword(next);}
    public static boolean verifyMasterPassword(char[] password){String stored=readHash();return stored!=null&&stored.equals(hash(password));}
    public static boolean setMasterPassword(char[] password){if(password==null||password.length<4)return false;String hash=hash(password);try(Connection c=DBConnection.getConnection()){if(c!=null){ensureTable(c);try(PreparedStatement p=c.prepareStatement("INSERT INTO application_security(setting_id,password_hash) VALUES(1,?) ON CONFLICT(setting_id) DO UPDATE SET password_hash=excluded.password_hash")){p.setString(1,hash);p.executeUpdate();}}}catch(SQLException e){return false;}PREFS.put(KEY,hash);PREFS.putBoolean(PROMPT_KEY,true);return true;}
    private static String hash(char[] value){try{MessageDigest digest=MessageDigest.getInstance("SHA-256");byte[] bytes=digest.digest((SALT+new String(value)).getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte b:bytes)out.append(String.format("%02x",b));return out.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private static String readHash(){try(Connection c=DBConnection.getConnection()){if(c!=null){ensureTable(c);try(Statement s=c.createStatement();ResultSet result=s.executeQuery("SELECT password_hash FROM application_security WHERE setting_id=1")){if(result.next())return result.getString(1);}}}catch(SQLException ignored){}return PREFS.get(KEY,null);}
    private static void ensureTable(Connection c)throws SQLException{try(Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS application_security (setting_id INT PRIMARY KEY, password_hash VARCHAR(128) NOT NULL)");}}
}
