import javax.swing.*;import javax.swing.table.*;import java.awt.*;import java.util.*;
public final class SettingsEditGuard extends JPanel {
 private final JComponent content;private final JButton edit=new JButton("Edit");private boolean editing;private final Map<Component,Object> snapshot=new IdentityHashMap<>();
 public SettingsEditGuard(JComponent content){super(new BorderLayout());this.content=content;JPanel controls=new JPanel(new FlowLayout(FlowLayout.RIGHT));edit.addActionListener(e->{if(editing){restore();setEditing(false);}else{capture();setEditing(true);}});controls.add(edit);add(content,BorderLayout.CENTER);add(controls,BorderLayout.SOUTH);installLockAfterSave(content);setEditing(false);}
 public boolean isEditing(){return editing;}
 private void setEditing(boolean value){editing=value;setInputsEnabled(content,value);edit.setText(value?"Cancel":"Edit");}
 private void capture(){snapshot.clear();capture(content);}
 private void capture(Component c){if(c instanceof JTextField f)snapshot.put(c,f.getText());else if(c instanceof JTextArea a)snapshot.put(c,a.getText());else if(c instanceof JComboBox<?> b)snapshot.put(c,b.getSelectedIndex());else if(c instanceof JCheckBox b)snapshot.put(c,b.isSelected());else if(c instanceof JTable t&&t.getModel() instanceof DefaultTableModel m){Object[][] rows=new Object[m.getRowCount()][m.getColumnCount()];for(int r=0;r<m.getRowCount();r++)for(int col=0;col<m.getColumnCount();col++)rows[r][col]=m.getValueAt(r,col);snapshot.put(c,rows);}if(c instanceof Container n)for(Component x:n.getComponents())capture(x);}
 private void restore(){restore(content);}
 private void restore(Component c){Object v=snapshot.get(c);if(c instanceof JTextField f&&v instanceof String s)f.setText(s);else if(c instanceof JTextArea a&&v instanceof String s)a.setText(s);else if(c instanceof JComboBox<?> b&&v instanceof Integer i)b.setSelectedIndex(i);else if(c instanceof JCheckBox b&&v instanceof Boolean x)b.setSelected(x);else if(c instanceof JTable t&&v instanceof Object[][] rows&&t.getModel() instanceof DefaultTableModel m){m.setRowCount(0);for(Object[] row:rows)m.addRow(row);}if(c instanceof Container n)for(Component x:n.getComponents())restore(x);}
 private void installLockAfterSave(Component c){if(c instanceof JButton b&&b.getText().matches(".*(Save|Update|Apply|Change).*"))b.addActionListener(e->SwingUtilities.invokeLater(()->{if(editing){capture();setEditing(false);}}));if(c instanceof Container n)for(Component x:n.getComponents())installLockAfterSave(x);}
 private void setInputsEnabled(Component c,boolean enabled){if(c instanceof javax.swing.text.JTextComponent f){f.setEditable(enabled);f.setEnabled(enabled);}else if(c instanceof JComboBox<?>||c instanceof JSpinner||c instanceof JCheckBox||c instanceof JButton)c.setEnabled(enabled);if(c instanceof Container n)for(Component x:n.getComponents())setInputsEnabled(x,enabled);}
}
