import java.sql.*;import java.util.*;import java.util.regex.*;
public final class TaxSlabStore {public record Slab(String name,double from,double to,double rate){}private static final List<Slab> DEFAULTS=List.of(new Slab("₹0 – ₹4,00,000",0,400000,0),new Slab("₹4,00,001 – ₹8,00,000",400001,800000,5),new Slab("₹8,00,001 – ₹12,00,000",800001,1200000,10),new Slab("₹12,00,001 – ₹16,00,000",1200001,1600000,15),new Slab("₹16,00,001 – ₹20,00,000",1600001,2000000,20),new Slab("₹20,00,001 – ₹24,00,000",2000001,2400000,25),new Slab("₹24,00,001 – ₹10,00,00,000",2400001,100000000,30));static{migrate();}private TaxSlabStore(){}
 private static void migrate(){try(Connection c=DBConnection.getConnection();Statement s=c==null?null:c.createStatement()){if(s==null)return;try{s.executeUpdate("ALTER TABLE settings_tax_slabs ADD COLUMN slab_type TEXT DEFAULT 'TAX'");}catch(SQLException ignored){}try{s.executeUpdate("ALTER TABLE settings_tax_slabs ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0");}catch(SQLException ignored){}try{s.executeUpdate("ALTER TABLE settings_tax_slabs ADD COLUMN deleted_at TEXT");}catch(SQLException ignored){}s.executeUpdate("UPDATE settings_tax_slabs SET slab_type='TAX' WHERE slab_type IS NULL OR slab_type='' ");}catch(SQLException ignored){}}
 public static synchronized List<Slab> list(){List<Slab> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c==null?null:c.prepareStatement("SELECT slab_name,from_amount,to_amount,tax_rate FROM settings_tax_slabs WHERE slab_type='TAX' AND is_deleted=0 ORDER BY slab_id")){if(p!=null){ResultSet r=p.executeQuery();while(r.next())out.add(new Slab(r.getString(1),r.getDouble(2),r.getDouble(3),r.getDouble(4)));}}catch(SQLException ignored){}return out.isEmpty()?new ArrayList<>(DEFAULTS):out;}
 public static synchronized void save(List<Slab> slabs)throws SQLException{validate(slabs);try(Connection c=DBConnection.getConnection()){if(c==null)return;c.setAutoCommit(false);try(PreparedStatement hide=c.prepareStatement("UPDATE settings_tax_slabs SET is_deleted=1,deleted_at=CURRENT_TIMESTAMP WHERE slab_type='TAX' AND is_deleted=0");PreparedStatement add=c.prepareStatement("INSERT INTO settings_tax_slabs(slab_name,from_amount,to_amount,tax_rate,slab_type,is_deleted) VALUES(?,?,?,?, 'TAX',0)")){hide.executeUpdate();for(Slab s:slabs){add.setString(1,s.name());add.setDouble(2,s.from());add.setDouble(3,s.to());add.setDouble(4,s.rate());add.addBatch();}add.executeBatch();c.commit();}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}}
 public static void validate(List<Slab> slabs){if(slabs==null||slabs.isEmpty())throw new IllegalArgumentException("Add at least one tax slab.");List<Slab> ordered=new ArrayList<>(slabs);ordered.sort(Comparator.comparingDouble(Slab::from));double previous=-1;for(Slab s:ordered){if(s.name()==null||s.name().isBlank())throw new IllegalArgumentException("Slab Name is required.");if(!Double.isFinite(s.from())||!Double.isFinite(s.to())||s.from()<0||s.to()<s.from())throw new IllegalArgumentException("Each slab must have valid non-negative From and To values.");if(!Double.isFinite(s.rate())||s.rate()<0||s.rate()>100)throw new IllegalArgumentException("Tax Rate must be between 0% and 100%.");if(previous>=0&&s.from()!=previous+1)throw new IllegalArgumentException(s.from()<=previous?"Tax slabs must not overlap.":"Tax slabs must not leave a gap.");previous=s.to();}}
 public static double parseAmount(String text){String v=text==null?"":text.trim().toLowerCase(Locale.ROOT).replace("₹","").replace(",","");Matcher m=Pattern.compile("([0-9]+(?:\\.[0-9]+)?)\\s*(lakh|lakhs|crore|crores)?").matcher(v);if(!m.matches())throw new IllegalArgumentException("Enter a valid rupee, Lakh, or Crore amount.");double n=Double.parseDouble(m.group(1));String unit=m.group(2);return n*(unit==null?1:unit.startsWith("crore")?10000000:100000);}
 public static double[] parseRangeName(String name){String[] parts=(name==null?"":name.trim()).split("\\s*(?:–|—|-|to)\\s*",-1);if(parts.length!=2)throw new IllegalArgumentException("Enter the slab name as a valid range, for example ₹4 Lakh – ₹8 Lakh.");try{return new double[]{parseAmount(parts[0]),parseAmount(parts[1])};}catch(Exception e){throw new IllegalArgumentException("Enter the slab name as a valid range, for example ₹4 Lakh – ₹8 Lakh.");}}
 public static String displayName(double from,double to){return "₹"+format(from)+" – ₹"+format(to);}private static String format(double n){String raw=String.format(Locale.ROOT,"%.0f",n);StringBuilder out=new StringBuilder();for(int i=0;i<raw.length();i++){if(i>0&&((raw.length()-i)==3||((raw.length()-i)>3&&(raw.length()-i-3)%2==0)))out.append(',');out.append(raw.charAt(i));}return out.toString();}
 public static double monthlyTds(double monthlyWages){if(monthlyWages<=0)return 0;double taxable=Math.max(0,monthlyWages*12-PayrollRulesStore.standardDeduction());if(taxable<=PayrollRulesStore.rebate87aLimit())return 0;double tax=0;for(Slab s:list())tax+=Math.max(0,Math.min(taxable,s.to())-s.from()+1)*s.rate()/100;return Money.round(tax*(1+PayrollRulesStore.cessRate()/100)/12);}
}
