import java.nio.charset.StandardCharsets;
import java.security.*;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.sql.*;
import java.util.Arrays;
import java.util.Base64;
import java.util.concurrent.ConcurrentHashMap;

/** Local application credentials. Passwords are always PBKDF2 hashes. */
public final class UserAuthentication {
    private static final int ITERATIONS=600_000, KEY_BITS=256, MAX_FAILURES=5; private static final long LOCK_MILLIS=300_000L; private static final ConcurrentHashMap<String,Attempt> ATTEMPTS=new ConcurrentHashMap<>();
    public static boolean isUsernameCompliant(String username){return username!=null&&username.trim().length()>=4;}
    public static boolean isPasswordCompliant(char[] password){return password!=null&&password.length>=8&&password.length<=16;}
    public static boolean hasUsers(){try(Connection c=DBConnection.getConnection()){if(c==null)return false;ensureTable(c);try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT 1 FROM payroll_users LIMIT 1")){return r.next();}}catch(SQLException ignored){return false;}}
    /** Creates both credential sets atomically for a brand-new installation. */
    public static boolean createInitialCredentials(String username,char[] password,char[] masterPassword){return createInitialCredentials(username,password,masterPassword,false);}
    /** After a successful licence activation, replaces only old credential rows; payroll records remain intact. */
    static boolean createInitialCredentials(String username,char[] password,char[] masterPassword,boolean replaceExisting){String user=username==null?"":username.trim();try(Connection c=DBConnection.getConnection()){if(c==null||!isUsernameCompliant(user)||!isPasswordCompliant(password)||!SecurityService.isMasterPasswordCompliant(masterPassword))return false;ensureTable(c);SecurityService.ensureTable(c);c.setAutoCommit(false);try(Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT 1 FROM payroll_users LIMIT 1")){if(r.next()&&!replaceExisting){c.rollback();return false;}}if(replaceExisting)try(Statement s=c.createStatement()){s.executeUpdate("DELETE FROM payroll_users");}try(PreparedStatement userInsert=c.prepareStatement("INSERT INTO payroll_users(username,password_hash,role_name) VALUES(?,?,?)");PreparedStatement masterInsert=c.prepareStatement("INSERT INTO application_security(setting_id,password_hash) VALUES(1,?) ON CONFLICT(setting_id) DO UPDATE SET password_hash=excluded.password_hash")){userInsert.setString(1,user);userInsert.setString(2,encode(password));userInsert.setString(3,"Admin");userInsert.executeUpdate();masterInsert.setString(1,SecurityService.hashForStorage(masterPassword));masterInsert.executeUpdate();c.commit();SecurityService.markConfigured();return true;}catch(Exception e){c.rollback();return false;}finally{c.setAutoCommit(true);}}catch(Exception ignored){return false;}finally{clear(password,masterPassword);}}
    /** Kept for source compatibility; new setup must also create a Master Data password. */
    public static boolean createInitialAdmin(String username,char[] password){try{return false;}finally{clear(password);}}
    public static boolean verify(String username,char[] password){try(Connection c=DBConnection.getConnection()){if(c==null)return false;ensureTable(c);try(PreparedStatement p=c.prepareStatement("SELECT password_hash FROM payroll_users WHERE username=?")){p.setString(1,username==null?"":username.trim());ResultSet r=p.executeQuery();return r.next()&&matches(password,r.getString(1));}}catch(SQLException ignored){return false;}finally{clear(password);}}
    public static boolean login(String username,char[] password){String user=username==null?"":username.trim(),key=user.toLowerCase();Attempt attempt=ATTEMPTS.get(key);if(attempt!=null&&attempt.locked()){clear(password);return false;}if(!verify(user,password)){ATTEMPTS.compute(key,(ignored,old)->old==null?new Attempt(1):old.failed());return false;}ATTEMPTS.remove(key);Session.currentUser=user;Session.role="Admin";return true;}
    public static boolean updateCredentials(String currentUsername,String newUsername,char[] newPassword){String current=currentUsername==null?"":currentUsername.trim(),target=newUsername==null?"":newUsername.trim();try(Connection c=DBConnection.getConnection()){if(c==null||!isUsernameCompliant(target)||!isPasswordCompliant(newPassword))return false;ensureTable(c);c.setAutoCommit(false);try{if(!current.equals(target)){try(PreparedStatement exists=c.prepareStatement("SELECT 1 FROM payroll_users WHERE username=?")){exists.setString(1,target);if(exists.executeQuery().next()){c.rollback();return false;}}}try(PreparedStatement p=c.prepareStatement("UPDATE payroll_users SET username=?,password_hash=? WHERE username=?")){p.setString(1,target);p.setString(2,encode(newPassword));p.setString(3,current);if(p.executeUpdate()!=1){c.rollback();return false;}}c.commit();Session.currentUser=target;Session.role="Admin";return true;}catch(Exception e){c.rollback();return false;}finally{c.setAutoCommit(true);}}catch(Exception ignored){return false;}finally{clear(newPassword);}}
    static boolean resetForRecoveredInstallation(Connection c)throws Exception{ensureTable(c);try(Statement s=c.createStatement()){s.executeUpdate("DELETE FROM payroll_users");}try(PreparedStatement p=c.prepareStatement("INSERT INTO payroll_users(username,password_hash,role_name) VALUES(?,?,?)")){p.setString(1,"User");p.setString(2,encode("Welcome@123".toCharArray()));p.setString(3,"Admin");p.executeUpdate();}return true;}
    static void ensureTable(Connection c)throws SQLException{try(Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS payroll_users (username TEXT PRIMARY KEY,password_hash TEXT NOT NULL,role_name TEXT NOT NULL)");}}
    private static boolean matches(char[] value,String stored){try{if(stored!=null&&stored.startsWith("pbkdf2$")){String[] parts=stored.split("\\$",-1);if(parts.length!=4)return false;byte[] actual=derive(value,Base64.getDecoder().decode(parts[2]),Integer.parseInt(parts[1]));return MessageDigest.isEqual(actual,Base64.getDecoder().decode(parts[3]));}return MessageDigest.isEqual(legacy(new String(value)).getBytes(StandardCharsets.UTF_8),String.valueOf(stored).getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){return false;}}
    static String encode(char[] value)throws Exception{byte[] salt=new byte[16];new SecureRandom().nextBytes(salt);return "pbkdf2$"+ITERATIONS+"$"+Base64.getEncoder().encodeToString(salt)+"$"+Base64.getEncoder().encodeToString(derive(value,salt,ITERATIONS));}
    private static byte[] derive(char[] value,byte[] salt,int iterations)throws Exception{PBEKeySpec spec=new PBEKeySpec(value,salt,iterations,KEY_BITS);try{return SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();}finally{spec.clearPassword();}}
    private static String legacy(String value)throws Exception{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte b:bytes)out.append(String.format("%02x",b));return out.toString();}
    private static void clear(char[]... values){for(char[] value:values)if(value!=null)Arrays.fill(value,'\0');}
    private record Attempt(int failures,long lockedUntil){Attempt(int failures){this(failures,failures>=MAX_FAILURES?System.currentTimeMillis()+LOCK_MILLIS:0);}Attempt failed(){return new Attempt(failures+1);}boolean locked(){return lockedUntil>System.currentTimeMillis();}}
    private UserAuthentication(){}
}
